<!--
/**
 * Shipment UTR Number module
 * Author : Saurabh Sharma*/
-->
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-tax-rate-importExport"><?php echo Mage::helper('shipmentpayout')->__('Import from Shipment Payout UTR') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="box-left">
        <form id="import_form" action="<?php echo $this->getUrl('*/*/importutr') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('shipmentpayout')->__('Import from Shipment Payout UTR') ?></h4>
            </div>

            <fieldset>
            <table class="form-list" cellspacing="0">
                <colgroup class="label"/>
                <colgroup class="value"/>
                <tbody>
                    <!--<tr>
                        <td class="label">
                            <label><?php //echo Mage::helper('shipmentpayout')->__('Tracking Title') ?></label>
                        </td>
                        <td class="value">
                            <input type="text" name="import_shipmenttracking_tracking_title" class="input-file"/>
                        </td>
                    </tr>-->
                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('shipmentpayout')->__('Import File') ?></label>
                        </td>
                        <td class="value">
                            <input type="file" name="import_shipmentutr_file" class="input-file required-entry"/>
                            <p class="nm">
                                <small><?php echo Mage::helper('shipmentpayout')->__('Line format:'). ' "'.Mage::helper('shipmentpayout')->__('order id').'","'.Mage::helper('shipmentpayout')->__('UTR Number').'","'.Mage::helper('shipmentpayout')->__('Date in MM/dd/YYYY').'"'; ?></small>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td class="value">
                            <?php $button_label = Mage::helper('shipmentpayout')->__('Import'); ?>
                            <?php echo $this->getButtonHtml($button_label, "this.form.submit();displayLoadingMask();") ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            </fieldset>

        </form>
        <script type="text/javascript">
            var importForm = new varienForm('import_form');

            function displayLoadingMask()
            {
                var loaderArea = $$('#html-body .wrapper')[0]; // Blocks all page
                Position.clone($(loaderArea), $('loading-mask'), {offsetLeft:-2});
                toggleSelectsUnderBlock($('loading-mask'), false);
                Element.show('loading-mask');
            }
        </script>
    </div>
    <div class="clear"></div>
</div>
