<?php
$order =$this->getOrder();
$address=$order->getShippingAddress();
//echo $country_name = Mage::app()>getLocale()>getCountryTranslation($address['country_id']);
 $country_name = $address['country_id'];
if($country_name=='IN')
{?>
 <tr>
              <td bgcolor="#ffffff" style="padding:10px;">
                <table border="0" cellpadding="0" cellspacing="0" align="center" width="99%">
                  <tbody><tr>
                    <td width="300" valign="top" align="center" class="responsive-image">
                        <a href="https://play.google.com/store/apps/details?id=com.craftsvilla.app&amp;hl=en" style="border:none; outline:0; display:block;"><img src="http://i.imgur.com/pozZW6g.png" alt="" title="" style="border:none; width:100%;"></a>
                    </td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
<?php
}
else
{
    ?>

    <?php
}

//echo "<pre>"; print_r($order);exit;


?>
