<?php $_shipment=$this->getShipment() ?>
<?php $_order=$this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<?php $i=0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
       
            <?php  $test = $_item->getCourierName() ?>
            <?php 
            
            $aramex = "Aramex";
            $fedex = "Fedex";
            $dtdc = "Dtdc";
            	if($test == $aramex)
              	{
                    echo "https://www.aramex.com/express/track.aspx";
              	}
                  else
                  if($test == $fedex)
                  {
                        echo "https://www.fedex.com/apps/fedextrack/?action=track";
             	  }
                  else
                  if($test == $dtdc)
                  {
                   		echo "http://shipway.in/dotzot";
                  }
            ?>
 <?php endforeach ?>
   
<?php endif; ?>

