<div id="block_notice_feedbacks_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Feedbacks'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This page contains all feedbacks received from buyers and all seller responses to them.
    Use eBay Accounts dropdown to filter feedbacks by accounts.<br/>
    If a response to feedback was not automatically sent, you can send it manually by pressing the <u>Response</u> button on
    appropriate line and filling appeared form at the top of page.<br/><br/>
    <b>Note:</b> Auto Responses to feedbacks are sent according to the eBay Accounts settings in eBay > Configuration > eBay Accounts > Feedbacks.'); ?>
</div>