<?php
/******************************************************
 * @package MT OneStepCheckOut module for Magento 1.4.x.x and Magento 1.5.x.x
 * @version 1.5.2.1
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>
<div id="tool-tip-login" class="tool-tip-login" style="visibility:hidden;" onclick="login.hide();"></div>
<div id="tool-tip-login-form" class="tool-tip-login-form" style="display:none;">
    <div class="close-button">
        <a href="javascript:void(0);" onclick="login.hide();" title="<?php echo $this->__('Close') ?>"></a>
    </div>
    <div class="onestepcheckout-ajax-loader" id="onstepcheckout-login" style="display:none;"></div>
    <div class="login-form" id="onestepcheckout-login-form">
        <h4><?php echo $this->__('Login') ?></h4>
        <div id="onestepcheckout-error-message" class="onestepcheckout-error-message"></div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" onsubmit="login.login();return false;">
        <fieldset>
            <p><?php echo $this->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
                <li>
                    <div>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
                        <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    </div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
</div>
<div class="onestepcheckout-checkout-method">
    <?php echo $this->getChildHtml('login_before')?>
    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
    <a href="javascript:void(0);" onclick="login.show();"><?php echo $this->__('Already registered? Please log in below.') ?></a>
    <?php endif; ?>
</div>
<script type="text/javascript">
//<![CDATA[
    var login = new Login('<?php echo $this->getUrl('mtonestepcheckout/index/loginPost') ?>','300','300');
    var loginForm = new VarienForm('login-form', true);
//]]>
</script>
