<?php
/******************************************************
 * @package MT OneStepCheckOut module for Magento 1.4.x.x and Magento 1.5.x.x
 * @version 1.5.2.1
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>
<script type="text/javascript">
//<![CDATA[
    var payment = new Payment('<?php echo $this->getUrl('mtonestepcheckout/index/savePayment') ?>', <?php echo Mage::helper('mtonestepcheckout')->isUseAjaxSavePayment() ?>);
//]]>
</script>
<fieldset>
    <div class="onestepcheckout-ajax-loader" id="onestepcheckout-payment-ajax-loader" style="display:none;"></div>
    <dl class="sp-methods" id="checkout-payment-method-load" style="display:block;">
        <?php echo $this->getChildHtml('methods') ?>
    </dl>
</fieldset>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-300)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    payment.initWhatIsCvvListeners();
    payment.switchMethod(payment.currentMethod);
//]]>
</script>
