<?php
/******************************************************
 * @package MT OneStepCheckOut module for Magento 1.4.x.x and Magento 1.5.x.x
 * @version 1.5.2.1
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>

<?php //if(0):?>

<?php if(Mage::helper('mtonestepcheckout')->includeCoupon()): ?>
<!--div class="coupon">
    <span class="title"><?php echo $this->__('Discount Code') ?></span>
    <input id="coupon_code" type="text" <?php if($this->getQuote()->getCouponCode()): ?>disabled="disabled"<?php endif; ?> class="input-text" name="coupon_code" value="<?php echo $this->getQuote()->getCouponCode() ?>" />
    <a id="icon-coupon-add-remove" <?php if($this->getQuote()->getCouponCode()): ?>class="remove"<?php else: ?>class="check"<?php endif; ?> <?php if($this->getQuote()->getCouponCode()): ?>title="<?php echo $this->__('Remove') ?>"<?php else: ?>title="<?php echo $this->__('Apply coupon') ?>"<?php endif; ?> href="javascript:void(0);" onclick="review.coupon();"></a>
</div-->
<?php endif; ?>
<div class="onestepcheckout-ajax-loader" id="onestepcheckout-review-ajax-loader" style="display:none;"></div>
<div id="checkout-review-load" style="display:block;">
    <?php echo $this->getChildHtml('info') ?>
</div>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <button type="button" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="review.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        <?php $couponCode = 0;if($this->getQuote()->getCouponCode()) $couponCode = 1; ?>
        var review = new Review(
                    'onestepcheckout-form',
                    '<?php echo $this->getUrl('mtonestepcheckout/index/coupon') ?>',
                    '<?php echo $couponCode ?>',
                    '<?php echo $this->getUrl('mtonestepcheckout/index/updateQty') ?>',
                    '<?php echo $this->getUrl('mtonestepcheckout/index/saveOrder') ?>',
                    $('checkout-agreements')
                );
    //]]>
    </script>
</div>

<?php //endif;?>
