<?php
/******************************************************
 * @package MT OneStepCheckOut module for Magento 1.4.x.x and Magento 1.5.x.x
 * @version 1.5.2.1
 * @author http://www.magentheme.com
 * @copyright (C) 2011- MagenTheme.Com
 * @license PHP files are GNU/GPL
*******************************************************/
?>
<div class="onestepcheckout-ajax-loader" id="onestepcheckout-shipping-method-ajax-loader" style="display:none;"></div>
<div id="checkout-shipping-method-load" style="display:block;">
    <?php echo $this->getChildHtml('available') ?>
</div>
<script type="text/javascript">
//<![CDATA[
    var shippingMethod = new ShippingMethod(
                                    "<?php echo $this->getUrl('mtonestepcheckout/index/saveShippingMethod') ?>",
                                    <?php echo Mage::helper('mtonestepcheckout')->isReloadPayment() ?>
                                );
//]]>
</script>
