<style type="text/css">
body {
	font-size:11px;
	font-family:Arial, Helvetica, sans-serif;
	margin:0;
	padding:20px 0 0;
}
.table-border {
	font-family:Arial, Helvetica, sans-serif;
	font-size:11px;
	text-align:left;
	border-collapse:collapse;
}
.table-border tr, .table-border th {
	height:40px
}
.table-border tr th {
	border:#ccc 1px solid;
}
.table-border tr td {
	border:#ccc 1px solid;
}
.totals {
	font-size:13px;
	color:#000;
	font-weight:bold;
	padding-left:5px
}
.totals2 {
	text-align:right;
	font-size:13px;
	font-weight:bold;
	padding-right:5px
}
.totals3 {
	font-size:18px;
	border-top:1px dotted #ccc;
	background:#EDEEE7;
	padding-left:5px
}
.totals4 {
	text-align:right;
	font-size:18px;
	border-top:1px dotted #ccc;
	background:#EDEEE7;
	padding-right:5px
}
.txtRight {
	text-align:right;
	padding-right:10px
}
h2 {
	font-size:18px;
	padding:0 0 5px;
	margin:0
}
.vatdetails {
	font-size:10px;
}
.barcodetext {
	font-size:60px;
}
.barcode {
	font-size:20px;
	text-align:center;
	float:right;
}
.discrictcode {
	font-size:12px;
}
.authoriesd {
	font-weight:bold;
	padding:3px 0 0 0;
}
tr.bottumborder td {
	border-bottom:1px dotted #999;
}
.margintop {
	margin:0px 0 20px;
}
.vatdetails p {
	margin:0 0 5px;
}
.paddtop{ padding-top:10px;}
</style>
<script src="<?php echo $this->getSkinUrl('script/Free_3_of_9_400.font.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	Cufon.replace('.barcodetext', { fontFamily: 'Free 3 of 9' });
</script>
<?php $_order = $this->getOrder() ?>
    <?php $_invoice = $this->getInvoice() ?>
<?php if($_invoice): ?>
    <?php $_invoices = array($_invoice); ?>
<?php else: ?>
    <?php $_invoices = $_order->getInvoiceCollection() ?>
<?php endif; ?>
<?php foreach ($_invoices as $_invoice): ?>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td align="left" valign="top"><h2>SAANVI HOME SHOPPEE PVT LTD</h2>
        #2, CENTRIUM, FIRST FLOOR,<br />
        LOKHANDWALA, KANDIVLI (E)<br />
        MUMBAI 400101 </td>
        <td valign="top"><div class="vatdetails" align="right">
        <p> VAT TIN NO 27480861141V W.E.F. 1/10/2011<br />
        CST TIN NO 27480861141C W.E.F. 1/10/2011</p></div>
        </td>
    </tr>
    
	<tr>
		<td height="50" colspan="2">
        <img src="<?php echo $this->getSkinUrl('images/stroke-print.gif') ?>" width="800" height="16" />
        </td>
	</tr>
    
    <tr>
		<td valign="top">
        <p><strong style="font-size:13px">Address of customer:</strong><br />
		<?php $_billing = $_invoice->getbillingAddress() ?>
		<address><?php echo $_order->getBillingAddress()->format('html') ?></address></p>
        </td>
        <td align="right"><p><strong> <?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?><br />
              DATE: <?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?><br />
              </strong> </p>
              <p class="barcode"><span class="barcodetext">*58524409672*</span><br />
                *58524409672*</p></td>
	</tr>
    
	<tr>
		<td colspan="2">
			<table width="800" border="0" cellspacing="0" cellpadding="2" class="table-border margintop">
                <tr style="background:#EDEEE7">
	                <th>PAYMENT METHOD</th>
	                <th>SHIPPING METHOD</th>
                </tr>
                <tr>
    	            <td><?php echo $this->getPaymentInfoHtml() ?></td>
        	        <td><?php echo $_order->getShippingDescription() ?></td>
                </tr>
			</table>
			<table class="data-table" id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
			<col />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
            <thead>
                <tr style="background:#EDEEE7">
                    <th><?php echo $this->__('Product Name') ?></th>
                    <th><?php echo $this->__('SKU') ?></th>
                    <th class="a-right"><?php echo $this->__('Price') ?></th>
                    <th class="a-center"><span class="nobr"><?php echo $this->__('Qty Invoiced') ?></span></th>
                    <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
                </tr>
            </thead>
            <tfoot>
                <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
            </tfoot>
            <?php $_items = $_invoice->getItemsCollection(); ?>
            <?php $_count = $_items->count(); ?>
            <?php foreach ($_items as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
            <tbody>
                <?php echo $this->getItemHtml($_item) ?>
            </tbody>
            <?php endforeach; ?>
    		</table>
		</td>
	</tr>
    
	<tr>
		<td height="30" colspan="2">
			<table cellpadding="0" cellspacing="0" border="0" width="100%">
            	<tr>
                	<td width="565" valign="top">
                    	<div class="vatdetails paddtop">             
                        <p><strong>Prices inclusive of VAT</strong><br />
                        I / We hereby certify that my/our registration certificate under the Maharashtra
                        Value Added Tax Act, 2002 is in force on the date on which the sale of the
                        goods specified in this tax invoice is made by me / us and that the transaction of
                        sale covered by this tax invoice has been effected by me / us and it shall be
                        accounted for in the turnover of sales while filing of return and the due tax, if
                        any, payable on the sale has been paid or shall be paid.</p>
                        <p>CHEQUE PAYABLE TO "SAANVI HOME SHOPPEE PVT LTD"<br />
                        ICICI BANK A/C NO "103205000282"<br />
                        IFSC CODE "ICIC0001032"</p>
                        </div>
					</td>
                    <td valign="top">           
			  		<p align="right">FOR SAANVI HOME SHOPPEE PVT LTD</p>
              		<p align="right" class="authoriesd">AUTHORISED SIGNATORY</p>
                    </td>
				</tr>
			</table>
		</td>
	</tr>
    
	<tr>
		<td height="50" colspan="2" align="center">
			<img src="<?php echo $this->getSkinUrl('images/stroke-print-bottom.gif') ?>" width="800" height="16" />
		</td>
	</tr>
    
</table></body>
    <script type="text/javascript">decorateTable('my-invoice-table-<?php echo $_invoice->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php endforeach; ?>
<script type="text/javascript">window.print();</script>
