<div class="blogset"><img src="http://www.craftsvilla.com/media/wysiwyg/Look-of-the-week-end.jpg" width="160" alt="" class="forum floatl"/>
     <div class="block_content"> <span class="item mHide">
    	<h3><a href="http://blog.craftsvilla.com/craftsvilla-pick-weekend" title="Craftsvilla Pick for this Weekend" target="_blank">Craftsvilla Pick for this Weekend</a>
		</h3></span><p>Bored of those Western outfit and no clue how to dress up yourself this weekend and look stunning? Then here is your solution with Craftsvilla.com and YES!! we are back with the assorted selection of the products to make you look from just fab to Fabulous. Every weekend wait for something new along with new theme right [...]</p></div>
        <p class="article-more"><a href="http://blog.craftsvilla.com/craftsvilla-pick-weekend" title="Craftsvilla Pick for this Weekend" target="_blank">Read the post</a></p>
        </div>
