
<div>
    <div> 
		<div class="AccountLeftNavTop">
			<h3>My Dashboard</h3>
		</div>
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="AccLeftNav current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li class="AccLeftNav" <?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>


<!--added mehul 25-08-11-->
<!--<?php $_links = $this->getLinks(); ?>
<?php $_index = 1; ?>
<?php $_count = count($_links); ?>
<?php foreach ($_links as $_link): ?>
<?php $_last = ($_index++ >= $_count); ?>
<?php if ($this->isActive($_link)): ?>
<a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a>
<?php else: ?>
<a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a>
<?php endif; ?>
<?php endforeach; ?>
--><!-- end mehul -->