 <div class="header"><a title="CraftsVilla.com - The Marketplace to Discover India" class="icon icon-logo floatl spriteimg" href="<?php echo $this->getUrl();?>"></a>
  <p class="floatr secure_icon spriteimg"></p>
</div>
<!--facebook Tracking added by dileswar on dated 25-05-2013-->
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6007958119886';
fb_param.value = '0.00';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6007958119886&amp;value=0" /></noscript>