<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Ajaxcatalog
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */ 
?>

<div class="loader-label" id="loader_label">
    <img src="<?php echo $this->getSkinUrl('awajaxcatalog/images/ajax-loader.gif');  ?>" />
    <span class="loading"><?php echo $this->__('Loading...'); ?></span>
</div>
