<?php if (!$this->getRequest()->getParam('id')) { ?>

    <div id="block_notice_listing_add" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Add Listing'); ?>">
        <?php echo Mage::helper('M2ePro')->__('This section allows you to create a Listing. Listing is a group of items, which have the same 
		Attribute Set and were combined to be listed on eBay.<br/><br/>
        Creating a Listing requires four types of templates (Price, Listing, Description, Synchronization) to be created in advance,
        that allows reaching a high level of flexibility in listing and synchronization processes. <br/>
		It is also possible to create templates by clicking the <u>Add New</u> button next to the appropriate template. Do not forget to press
		the <u>Refresh</u> button after a new template creation in order to see the newly added template in the dropdown list.<br/>
        <br/>In Listing Configuration block you are required to choose appropriate Price, Listing and Description Templates,
        which determine how the items of this Listing will be presented on eBay.<br/>
        <br/>In Synchronization Settings block you are required to choose a Synchronization Template and its settings.
        This determines the actions, which should be done to the eBay Listings depending on any changes of their products happened in Magento,
        and of their templates that are used in the Listing Configuration settings.<br/>
        <br/>Products Filter block allows you to filter the products, which you would like to add to the Listing.
        The filtered products will be shown on the next page after the <u>Next</u> button is pressed at the top right corner.'); ?>
    </div>

<?php } ?>

<?php
    $formData = Mage::registry('M2ePro_data') ? Mage::registry('M2ePro_data') : array();
    $default = array(
        'title' => '',
        'store_id' => 0,
        'attribute_set_id' => -1,

        'selling_format_template_id' => 0,
        'listing_template_id' => 0,
        'description_template_id' => 0,
        'synchronization_template_id' => -1,
        
        'synchronization_start_type' => Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_IMMEDIATELY,
        'synchronization_start_through_metric' => Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS,
        'synchronization_start_through_value' => 1,
        'synchronization_start_date' => now(),
        
        'synchronization_stop_type' => Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_NEVER,
        'synchronization_stop_through_metric' => Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS,
        'synchronization_stop_through_value' => 1,
        'synchronization_stop_date' => now(),

        'source_products' => Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CUSTOM,
        'categories_add_action' => Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE,
        'categories_delete_action' => Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE,
        'hide_products_others_listings' => Ess_M2ePro_Model_Listings::HIDE_PRODUCTS_OTHERS_LISTINGS_NO
    );
    $formData = array_merge($default, $formData);

    if (!isset($formData['id'])) {
        $blockStoreSwitcher = $this->getLayout()->createBlock('M2ePro/adminhtml_storeSwitcher', '', array('id'=>'store_id','selected' => $formData['store_id']));
        $this->setChild('store_id', $blockStoreSwitcher);
    } else {
        $storeModel = Mage::getModel('core/store')->load($formData['store_id']);
        $formData['store_name'] = $storeModel->getWebsite()->getName();
        if (strtolower($formData['store_name']) != 'admin') {
            $formData['store_name'] .= ' -> '.$storeModel->getGroup()->getName();
            $formData['store_name'] .= ' -> '.$storeModel->getName();
        } else {
            $formData['store_name'] = $storeModel->getGroup()->getName();
        }
    }

    $formData['synchronization_start_date'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['synchronization_start_date']);
    $formData['synchronization_stop_date'] = Mage::helper('M2ePro')->gmtDateToTimezone($formData['synchronization_stop_date']);
    
    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // General for all tabs
    //-----------------------------
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/edit', array('id' => $this->getRequest()->getParam('id'))); ?>';

    M2ePro.url.getSellingFormatTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'SellingFormatTemplates','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC')); ?>';
    M2ePro.url.getListingTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'ListingsTemplates','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC')); ?>';
    M2ePro.url.getDescriptionTemplatesBySet = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAllByAttributeSetId',array('model'=>'DescriptionsTemplates','id_field'=>'id','data_field'=>'title','sort_field'=>'title','sort_dir'=>'ASC')); ?>';
    M2ePro.url.getSynchronizationTemplates = '<?php echo $this->getUrl('*/adminhtml_general/modelGetAll',array('model'=>'SynchronizationsTemplates','id_field'=>'id','data_field'=>'title')); ?>';

    M2ePro.formData.id = '<?php echo $this->getRequest()->getParam('id'); ?>';
    M2ePro.formData.title = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->escapeHtml($formData['title'])); ?>';
    M2ePro.formData.store_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['store_id']); ?>';
    M2ePro.formData.attribute_set_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['attribute_set_id']); ?>';

    M2ePro.formData.selling_format_template_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['selling_format_template_id']); ?>';
    M2ePro.formData.listing_template_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['listing_template_id']); ?>';
    M2ePro.formData.description_template_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['description_template_id']); ?>';
    M2ePro.formData.synchronization_template_id = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['synchronization_template_id']); ?>';

    M2ePro.text.title_not_unique_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The specified title is already used for other listing. Listing title must be unique.')); ?>';
    M2ePro.text.attribute_set_not_selected_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You should select Attribute Set first')); ?>';
    M2ePro.text.wrong_date_time_format_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Invalid date time format string.')); ?>';

    Event.observe(window, 'load', function() {

        ListingEditHandlersObj = new ListingEditHandlers();

        $('attribute_set_id').observe('change', ListingEditHandlersObj.attribute_set_change);
        
		if ($('attribute_set_id').value) {
            $('attribute_set_id').simulate('change');
        }

        $('synchronization_template_id').observe('change', ListingEditHandlersObj.synchronization_template_id_change)
        if ($('synchronization_template_id').value) {
            $('synchronization_template_id').simulate('change');
        }

        $('synchronization_start_type')
            .observe('change', ListingEditHandlersObj.synchronization_start_type_change)
            .simulate('change');

        $('synchronization_stop_type')
            .observe('change', ListingEditHandlersObj.synchronization_stop_type_change)
            .simulate('change');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

	<div class="entry-edit" id="magento_block_listing_edit_general">

		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Listing Configuration'); ?></h4>
		</div>

		<div class="fieldset">
			<div class="hor-scroll">

				<table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="title"><?php echo Mage::helper('M2ePro')->__('Title'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="title" name="title" value="<?php echo Mage::helper('M2ePro')->__($formData['title']); ?>" type="text" class="input-text required-entry M2ePro-listing-title" />
                            <p class="note">
							    <span><?php echo Mage::helper('M2ePro')->__('Short meaningful Listing title for your internal use.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="attribute_set_id"><?php echo Mage::helper('M2ePro')->__('Product Attribute Set'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if (!$isEdit) : ?>
                                <select id="attribute_set_id" name="attribute_set_id" class="select-main required-entry">
                                    <?php if ($formData['attribute_set_id'] == -1): ?>
                                        <option class="empty"></option>
                                    <?php endif ?>
                                    <?php foreach ($this->attributesSets as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if ($formData['attribute_set_id'] == $set['attribute_set_id']): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            <?php else: ?>
                                <select id="attribute_set_fake" name="attribute_set_fake" class="select-main" disabled="disabled">
                                    <?php foreach ($this->attributesSets as $set): ?>
                                        <option value="<?php echo $set['attribute_set_id']; ?>"<?php if ($formData['attribute_set_id'] == $set['attribute_set_id']): echo ' selected="selected"'; endif;?>><?php echo $set['attribute_set_name'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <input id="attribute_set_id" name="attribute_set_id" value="<?php echo $this->escapeHtml($formData['attribute_set_id']); ?>" type="hidden" />
                            <?php endif ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Attribute Set of products, which will be listed on eBay in this Listing.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="selling_format_template_id"><?php echo Mage::helper('M2ePro')->__('Selling Format Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="selling_format_template_id" name="selling_format_template_id" class="required-entry"></select>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_selling_format_template_button'); ?>
                            <?php echo $this->getChildHtml('reload_selling_format_templates_button'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="listing_template_id"><?php echo Mage::helper('M2ePro')->__('General Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="listing_template_id" name="listing_template_id" class="required-entry"></select>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_listing_template_button'); ?>
                            <?php echo $this->getChildHtml('reload_listing_templates_button'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="description_template_id"><?php echo Mage::helper('M2ePro')->__('Description Template'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="description_template_id" name="description_template_id" class="required-entry"></select>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_description_template_button'); ?>
                            <?php echo $this->getChildHtml('reload_description_templates_button'); ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('List of templates, which have previously chosen Attribute Set.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>
	
	<div class="entry-edit" id="magento_block_listing_edit_synchronization">

		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization Settings'); ?></h4>
		</div>

		<div class="fieldset">
			<div class="hor-scroll">

				<table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="synchronization_template_id"><?php echo Mage::helper('M2ePro')->__('Synchronization Template'); ?>: <span class="required">*</span></label>
						</td>
                        <td class="value">
                            <select id="synchronization_template_id" name="synchronization_template_id" class="required-entry">
                                <?php if ($formData['synchronization_template_id'] == -1): ?>
                                    <option class="empty"></option>
                                <?php endif ?>
                                <?php foreach ($this->synchronizationsTemplates as $item){ ?>
                                    <option value="<?php echo $item['id']; ?>" <?php if ($item['id'] == $formData['synchronization_template_id']) echo ' selected="selected"'; ?>><?php echo $item['title']; ?></option>
                                <?php } ?>
                            </select>
                            &nbsp;
                            <?php echo $this->getChildHtml('add_new_synchronization_template_button'); ?>
                            <?php echo $this->getChildHtml('reload_synchronization_templates_button'); ?>
							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('All Synchronization Templates you have created.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="synchronization_start_type"><?php echo Mage::helper('M2ePro')->__('Activation'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="synchronization_start_type" name="synchronization_start_type" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_IMMEDIATELY; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_IMMEDIATELY == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Immediately'); ?></option>
								<option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_THROUGH; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_THROUGH == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Delay After Listing Creation'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_DATE; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_DATE == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Since Date'); ?></option>
								<option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_NEVER; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_NEVER == $formData['synchronization_start_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Never'); ?></option></select>
							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time, when settings of chosen Synchronization Template take effect.'); ?></span>
                            </p>
						</td>
                    </tr>

                    <tr id="synchronization_start_through_value_container" <?php if ($formData['synchronization_start_type'] != Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_THROUGH) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_start_through_value"><?php echo Mage::helper('M2ePro')->__('Delay'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input id="synchronization_start_through_value" name="synchronization_start_through_value" value="<?php echo $formData['synchronization_start_through_value']; ?>" type="text" style="width: 200px;" class="input-text validate-digits M2ePro-required-when-visible" />
                            <select id="synchronization_start_through_metric" name="synchronization_start_through_metric" style="width: 70px;" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_DAYS == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Days'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_HOURS; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_HOURS == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Hours'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_MINUTES; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_THROUGH_METRIC_MINUTES == $formData['synchronization_start_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Minutes'); ?></option>
                            </select>
 							<p class="note">
                                 <span><?php echo Mage::helper('M2ePro')->__('In how many days, hours or minutes Synchronization Template settings should be activated.'); ?></span>
                            </p>
                       </td>
                    </tr>
                    
                    <tr id="synchronization_start_date_container" <?php if ($formData['synchronization_start_type'] != Ess_M2ePro_Model_Listings::SYNCHRONIZATION_START_TYPE_DATE) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_start_date"><?php echo Mage::helper('M2ePro')->__('Date'); ?>: <span class="required">*</span></label>
						</td>
                        <td class="value">
                            <input id="synchronization_start_date" name="synchronization_start_date" value="<?php echo $formData['synchronization_start_date']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "synchronization_start_date",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "synchronization_start_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Date and time when Synchronization Template should be activated.'); ?></span>
                            </p>
				        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="synchronization_stop_type"><?php echo Mage::helper('M2ePro')->__('Deactivation'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="synchronization_stop_type" name="synchronization_stop_type" class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_NEVER; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_NEVER == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Never'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_THROUGH; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_THROUGH == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Through Period After Activation'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_DATE; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_DATE == $formData['synchronization_stop_type']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('On Date'); ?></option>
                            </select>
							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Time, when settings of chosen Synchronization Template should be deactivated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="synchronization_stop_through_value_container" <?php if ($formData['synchronization_stop_type'] != Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_THROUGH) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_stop_through_value"><?php echo Mage::helper('M2ePro')->__('Period Value'); ?>: <span class="required">*</span></label>
						</td>
                        <td class="value">
                            <input id="synchronization_stop_through_value" name="synchronization_stop_through_value" value="<?php echo $formData['synchronization_stop_through_value']; ?>" type="text" style="width: 200px;" class="input-text validate-digits M2ePro-required-when-visible" />
							<select id="synchronization_stop_through_metric" name="synchronization_stop_through_metric" style="width: 70px;" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_DAYS == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Days'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_HOURS; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_HOURS == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Hours'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_MINUTES; ?>"<?php if (Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_THROUGH_METRIC_MINUTES == $formData['synchronization_stop_through_metric']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Minutes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('In how many days, hours or minutes after activation Synchronization Template settings should be deactivated.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="synchronization_stop_date_container" <?php if ($formData['synchronization_stop_type'] != Ess_M2ePro_Model_Listings::SYNCHRONIZATION_STOP_TYPE_DATE) echo ' style="display: none;"'; ?>>
                        <td class="label">
                            <label for="synchronization_stop_date"><?php echo Mage::helper('M2ePro')->__('Date'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <input id="synchronization_stop_date" name="synchronization_stop_date" value="<?php echo $formData['synchronization_stop_date']; ?>" type="text" class="input-text M2ePro-required-when-visible M2ePro-input-datetime" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Calendar.setup({
                                    inputField: "synchronization_stop_date",
                                    ifFormat: "%Y-%m-%e %H:%M:%S",
                                    showsTime: true,
                                    button: "synchronization_stop_date",
                                    align: "Bl",
                                    singleClick : true
                                });
                            //]]>
                            </script>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Date and time when Synchronization Template should be deactivated.'); ?></span>
                            </p>
					    </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_listing_edit_source_products">

		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Products Filter'); ?></h4>
		</div>

		<div class="fieldset">
			<div class="hor-scroll">

				<table class="form-list" cellspacing="0" cellpadding="0">

					<tr>
                        <td class="label">
                            <label for="store_id"><?php echo Mage::helper('M2ePro')->__('Store View'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php if (!$isEdit) { ?>
                                <?php echo $this->getChildHtml('store_id'); ?>
                            <?php } else { ?>
                                <?php echo $formData['store_name']; ?>
                            <?php } ?>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Store View the items' information should be taken from."); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label for="source_products"><?php echo Mage::helper('M2ePro')->__('Select from'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="source_products" name="source_products" <?php if ($isEdit): ?> disabled="disabled"<?php endif ?> class="required-entry">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CUSTOM; ?>"<?php if (Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CUSTOM == $formData['source_products']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Products List'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CATEGORIES; ?>"<?php if (Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CATEGORIES == $formData['source_products']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Categories'); ?></option>
                            </select>
							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Modes of the products selection.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <?php if ($isEdit && $formData['source_products'] == Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CATEGORIES): ?>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Selected Categories'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <?php if (count($this->selectedCategories)) { ?>
                                    <?php foreach ($this->selectedCategories as $selectedCategory) { ?>
                                        <strong><?php echo $selectedCategory; ?></strong><br />
                                    <?php } ?>
                                <?php } else { ?>
                                    <strong><?php echo Mage::helper('M2ePro')->__('Selected Categories Are No Longer Available'); ?></strong>
                                <?php } ?>
                            </td>
                        </tr>

                    <?php endif; ?>

					<tr>
                        <td class="label">
                            <label for="hide_products_others_listings"><?php echo Mage::helper('M2ePro')->__('Products Presented in Other Listings'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="hide_products_others_listings" name="hide_products_others_listings" class="required-entry" <?php if ($isEdit): ?> disabled="disabled"<?php endif ?>>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::HIDE_PRODUCTS_OTHERS_LISTINGS_NO; ?>"<?php if (Ess_M2ePro_Model_Listings::HIDE_PRODUCTS_OTHERS_LISTINGS_NO == $formData['hide_products_others_listings']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Show'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::HIDE_PRODUCTS_OTHERS_LISTINGS_YES; ?>"<?php if (Ess_M2ePro_Model_Listings::HIDE_PRODUCTS_OTHERS_LISTINGS_YES == $formData['hide_products_others_listings']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Do Not Show'); ?></option>
                            </select>
                            <p class="note"></p>
                        </td>
                    </tr>
					
                </table>

            </div>
        </div>

    </div>

    <?php if ($isEdit) : ?>
        <div class="entry-edit" id="magento_block_listings_edit_categories_product_actions" <?php if ($formData['source_products'] == Ess_M2ePro_Model_Listings::SOURCE_PRODUCTS_CUSTOM) echo ' style="display: none;"'; ?>>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Actions On Categories\' Products'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <tbody>

                            <tr id="categories_add_action_container">
                                <td class="label">
                                    <label for="categories_add_action"><?php echo Mage::helper('M2ePro')->__('New Product Added to Category'); ?>: <span class="required" style="float: right;">*</span></label>
                                </td>
                                <td class="value">
                                    <select id="categories_add_action" name="categories_add_action" class="M2ePro-required-when-visible">
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD_LIST; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD_LIST == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing And List on eBay'); ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Actions, which should be done to products added to categories.'); ?></span>
                                    </p>
                               </td>
                            </tr>

                            <tr id="categories_delete_action_container">
                                <td class="label">
                                    <label for="categories_delete_action"><?php echo Mage::helper('M2ePro')->__('Product Deleted from Category'); ?>: <span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <select id="categories_delete_action" name="categories_delete_action" class="M2ePro-required-when-visible">
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay'); ?></option>
                                        <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP_REMOVE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP_REMOVE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay And Delete from The Listing'); ?></option>
                                    </select>
                                    <p class="note">
                                        <span><?php echo Mage::helper('M2ePro')->__('Actions, which should be done to listed products deleted from categories.'); ?></span>
                                    </p>
                                </td>
                            </tr>

                        </tbody>

                    </table>

                </div>
            </div>

        </div>
    <?php endif; ?>

</form>