<div id="block_notice_listings_categories_tree" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Product Selection'); ?>">
	<?php echo Mage::helper('M2ePro')->__('The number shown next to each category is the quantity of products filtered by 
	Attribute Set and Products Filter settings.<br/><br/>
	There are two modes of products addition:
	<ul class="list">
        <li><b>All Products</b> - all products, which are included in selected categories, will be added to the Listing.</li>
        <li><b>Select Manually</b> - the list of products of chosen categories will be shown on the next page after the Next button is pressed at the top right corner.</li>
	</ul>
	<b>Note:</b> If a product belongs to different categories, it will be added to the Listing or shown for manual selection only once.<br/><br/>
	Two additional options New Product Added to Category and Product Deleted from Category allow choosing actions, 
	which could be automatically done to the products added to selected categories and to the products deleted from selected categories.'); ?>
</div>

<?php
    $selectedCategories = Mage::registry('temp_listing_categories');

    $selectedCategoriesProductsFrom = '';
    if (count(Mage::registry('temp_listing_categories')) == 0) {
        $selectedCategoriesProductsFrom = 'all';
    } else {
        $selectedCategoriesProductsFrom = 'manual';
    }

    $formData = Mage::registry('M2ePro_data') ? Mage::registry('M2ePro_data') : array();
    $default = array(
        'categories_add_action' => Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE,
        'categories_delete_action' => Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE
    );
    $formData = array_merge($default, $formData);
?>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
    }

    M2ePro.text.select_items_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Please select items.')); ?>';

    CategoriesTreeHandlersObj = new CategoriesTreeHandlers();

    Event.observe(window, 'load', function() {

        $('categories_products_from')
            .observe('change', CategoriesTreeHandlersObj.categories_products_from_change)
            .simulate('change');
    });

</script>

<div class="categories-side-col">
    <div class="tree-holder">
        <div id="tree-div" style="width: 100%; overflow: auto;"></div>
    </div>
</div>

<script type="text/javascript">

    var categories_selected_items = new Array();

    var initTreeSelectedNodes = new Array();

    <?php foreach ($selectedCategories as $category) { ?>
        categories_selected_items.push('<?php echo $category; ?>');
        initTreeSelectedNodes[initTreeSelectedNodes.length] = new Array();
        initTreeSelectedNodes[initTreeSelectedNodes.length-1][0] = '<?php echo $category; ?>';
        initTreeSelectedNodes[initTreeSelectedNodes.length-1][1] = null;
    <?php } ?>

    Ext.EventManager.onDocumentReady(function() {

        var tree = new Ext.tree.TreePanel('tree-div', {
            animate: true,
            enableDD: false,
            containerScroll: true,
            rootUIProvider: Ext.tree.CheckboxNodeUI,
            selModel: new Ext.tree.CheckNodeMultiSelectionModel(),
            rootVisible: false
        });

        tree.on('check', function(node) {
            if (node.attributes.checked) {
                CategoriesTreeHandlersObj.tree_categoryAdd(node.id, node);
            } else {
                CategoriesTreeHandlersObj.tree_categoryRemove(node.id, node);
            }
        }, tree);

        var root = new Ext.tree.TreeNode({
            text: 'root',
            draggable: false,
            checked: 'false',
            id: '__root__',
            uiProvider: Ext.tree.CheckboxNodeUI
        });

        tree.setRootNode(root);
        CategoriesTreeHandlersObj.tree_buildCategory(root, <?php echo $this->getTreeJson(); ?>);

        tree.render();
        root.expand();

        for (var j=0;j<initTreeSelectedNodes.length;j++) {
            if (initTreeSelectedNodes[j][1] != null)
                initTreeSelectedNodes[j][1].expand();
        }
    });

</script>

<div class="entry-edit" id="magento_block_listings_categories_tree_next_step">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Products Addition'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                    <tr>
                        <td class="label">
                            <label for="categories_products_from"><?php echo Mage::helper('M2ePro')->__('Add Products'); ?>: <span class="required">*</span></label>
						</td>
                        <td class="value">
                            <select id="categories_products_from" name="categories_products_from">
                                <option value="all"<?php if ('all' == $selectedCategoriesProductsFrom) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Products'); ?></option>
                                <option value="manual"<?php if ('manual' == $selectedCategoriesProductsFrom) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Select Manually'); ?></option>
                            </select>
							<p class="note">
							    <span><?php echo Mage::helper('M2ePro')->__('Mode of products addition from selected categories.'); ?></span>
							</p>
                        </td>
                    </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>

<div class="entry-edit" id="magento_block_listings_categories_tree_products_actions">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Actions On Categories\' Products'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tbody>

                    <tr id="categories_add_action_container">
                        <td class="label">
                            <label for="categories_add_action"><?php echo Mage::helper('M2ePro')->__('New Product Added to Category'); ?>: <span class="required" style="float: right;">*</span></label>
                        </td>
                        <td class="value">
                            <select id="categories_add_action" name="categories_add_action" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_NONE == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD_LIST; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_ADD_ACTION_ADD_LIST == $formData['categories_add_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Add to The Listing And List on eBay'); ?></option>
                            </select>
 							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Actions, which should be done to products added to categories.'); ?></span>
                            </p>
                       </td>
                    </tr>

                    <tr id="categories_delete_action_container">
                        <td class="label">
                            <label for="categories_delete_action"><?php echo Mage::helper('M2ePro')->__('Product Deleted from Category'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <select id="categories_delete_action" name="categories_delete_action" class="M2ePro-required-when-visible">
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_NONE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No Action'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay'); ?></option>
                                <option value="<?php echo Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP_REMOVE; ?>"<?php if (Ess_M2ePro_Model_Listings::CATEGORIES_DELETE_ACTION_STOP_REMOVE == $formData['categories_delete_action']) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Stop on eBay And Delete from The Listing'); ?></option>
                            </select>
 							<p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Actions, which should be done to listed products deleted from categories.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </tbody>

            </table>

        </div>
    </div>

</div>