<?php echo $this->getChildHtml('auth-redirect') ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
        <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Craftsvilla Refer A Friend</title>
        <link rel="icon" href="favicon.gif" type="image/x-icon" />
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <?php
    if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
        $redirectUrl = Mage::getBaseUrl();
        Mage::app()->getFrontController()->getResponse()->setRedirect($redirectUrl);
    }
    ?>
    <body<?php echo $this->getBodyClass() ?>>
        <?php echo $this->getChildHtml('ie') ?>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="algnCntr wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <div class="page">
                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container col1-layout">
                    <div class="main">
                        <div class="col-main">
                            <div class="bdyShadow2">
                                <div class="bodyWpr">
                                    <div class="innerTwo">
                                        <?php echo $this->getChildHtml('global_messages') ?>
                                        <?php echo $this->getChildHtml('content') ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
            <?php echo $this->getAbsoluteFooter(); ?>
        </div>
        <?php if($_SERVER['SERVER_ADDR'] == "10.134.214.27"){?>
        	<!-- script for visit tag of craftsvilla -->
        	<script type="text/javascript">
		        function _mt_ready(){
		        	if (typeof(MyThings) != "undefined") {
		        		MyThings.Track({
		        			EventType: MyThings.Event.Visit,
		        			Action: "300"
		        		});
		        	}
		        }
		        var mtHost = (("https:" == document.location.protocol) ? "https" : "http") + "://rainbow-in.mythings.com";
		        var mtAdvertiserToken = "1714-100-in";
		        document.write(unescape("%3Cscript src='" + mtHost + "/c.aspx?atok="+mtAdvertiserToken+"' type='text/javascript'%3E%3C/script%3E"));
	        </script>
	        <!-- ---------------------------------- -->
			<!--kissmetrics start -->
			<script type="text/javascript">
        var _kmq = _kmq || [];
        function _kms(u){
            setTimeout(function(){
                var s = document.createElement('script'); var f = document.getElementsByTagName('script')[0]; s.type = 'text/javascript'; s.async = true;
                s.src = u; f.parentNode.insertBefore(s, f);
            }, 1);
        }
        _kms('//i.kissmetrics.com/i.js');_kms('//doug1izaerwt3.cloudfront.net/319a0179551de1a2e35f62f9f246b81c015f96ea.1.js');
</script>
<?php
Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->getRequest()->getRequestUri());  //save requested URL for later redirection
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $email_unique1 = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
    ?>
    <script type="text/javascript">
             var _kmq = _kmq || []; 
            function _kms(u)
            { 
                setTimeout (function(){ var s = document.createElement('script'); 
                    var f = document.getElementsByTagName('script')[0]; 
                    s.type = 'text/javascript'; 
                    s.async = true; 
                    s.src = u; f.parentNode.insertBefore(s, f); }, 1); } _kms
            ('//i.kissmetrics.com/i.js');_kms
            ('//doug1izaerwt3.cloudfront.net/319a0179551de1a2e35f62f9f246b81c015f96ea.1.js'); 
            _kmq.push(['identify', '<?php echo $email_unique1; ?>']);

    </script>
<?php } ?>
			<!--kissmetrics end -->
			<!--chart beat -->

<script type="text/javascript">
    var _sf_async_config={uid:27315,domain:"craftsvilla.com"};
        function loadChartbeat() {
            window._sf_endpt=(new Date()).getTime();
            var e = document.createElement('script');
            e.setAttribute('language', 'javascript');
            e.setAttribute('type', 'text/javascript');
            e.setAttribute('src',
            (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") + "js/chartbeat.js");
            document.body.appendChild(e);
    }
var oldonload = window.onload;
window.onload = (typeof window.onload != 'function') ? loadChartbeat : function() { oldonload(); loadChartbeat(); };
</script>
<!-- end chart beat -->
<?php }?>
    </body>
</html>
