<div id="block_notice_ebay_listings" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('3rd Party Listings'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section contains eBay Listings, which belong to registered eBay Accounts (eBay > Configuration > eBay Accounts)
	and were listed not by M2E Pro extension.<br/>
	Use eBay Accounts and Marketplaces dropdowns to filter them.
	Also, you can manage these Listings on eBay by choosing appropriate options in the Actions dropdown in the top right corner of the grid.<br/><br/>
	<b>Note:</b> To import 3rd Party Listings the 3rd Party Listings Import should be enabled in account\'s settings 
	(eBay > Configuration > eBay Accounts > General tab) and the 3rd Party Listings Synchronization should be enabled 
	in eBay > Configuration > Synchronization.'); ?>
</div>