<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div>
        <?php if(!$_product->isGrouped()): ?>
        <li><label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" /></li>
        <?php endif; ?>
        <li><button type="button" title="<?php echo $buttonTitle ?>" class="addToCart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button></li>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>

