<!--<div class="clear"></div>
<br/>
<div class="fieldset" style="float:left;width:450px">
    <h2 class="legend"><?php echo $this->__('Connect with Facebook') ?></h1>
    <p><?php echo $this->__('Use your Facebook account to login or register within our store. You\'re just one click away.' ) ?></p>
    <button rel="facebook-connect" type="button" title="<?php echo $this->__('Connect with Facebook') ?>" class="loginFb"><span><span><?php echo $this->__(' ') ?></span></span></button>
    <br/><br/>
</div>
-->