<div class="wrapper">
    <div> <?php echo $this->getChildHtml('footer_block') ?> </div>
</div>
<div class="btmShadow"></div>
<div class="ftrCnr">
    <div class="cprts">
        <div class="pmt">Debit Cards, Net Banking - <br/>All Leading banks, Cash On Delivery</div>
        <div class="flw">
            <ul>
                <li id="flwTxt">Follow Us:</li>
                <li><a href="http://www.facebook.com/craftsvilla" target="_blank"><img src="<?php echo $this->getSkinUrl('images/fb.png') ?>" width="27" height="26" alt="Facebook" title="Facebook"/></a></li>
                <li><a href="http://www.twitter.com/craftsvilla" target="_blank"><img src="<?php echo $this->getSkinUrl('images/twitter.png') ?>" width="27" height="27" alt="Twitter" title="Twitter"/></a></li>
                <li><!--Gplus Code--><a class="gplusicon" href="https://plus.google.com/108801490299597047118?prsrc=3" style="text-decoration:none;" target="_blank"><img src="<?php echo $this->getSkinUrl('images/gplus.jpg') ?>" width="26" height="26" alt="Gplus" title="Gplus" /></a><!--Gplus Code end--></li>
                <li><a href="http://pinterest.com/craftsvilla/" target="_blank"><img src="<?php echo $this->getSkinUrl('images/pinit.jpg') ?>" width="26" height="26" alt="pinterest" title="pinterest"/></a></li>
            </ul>
        </div>
        <div class="rtTxt">© <a href="http://www.craftsvilla.com">craftsvilla.com.</a> All rights reserved.</div>
    </div>
    
    <p class="clear">certified payment gateway</p>
    
    
</div>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName('script')[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0012/1676.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
<!--<a href="http://www.slideshare.net/slideshow/embed_code/11381653" title="valentine's day catalog" class="vday" target="_blank"></a>-->

