<div class="wrapper">
	<div> <?php echo $this->getChildHtml('footer_block') ?> </div>
</div>
<div class="btmShadow"></div>
<div class="ftrCnr">
    <div class="cprts">
		<div class="pmt">Debit Cards, Net Banking - <br/>All Leading banks, Cash On Delivery</div>
    	<div class="flw">
    		<ul>
    			<li id="flwTxt">Follow Us:</li>
    			<li><a href="http://www.facebook.com/craftsvilla"><img src="<?php echo $this->getSkinUrl('images/fb.png')?>" width="27" height="26" alt="Facebook" title="Facebook"/></a></li>
    			<li><a href="http://www.twitter.com/craftsvilla"><img src="<?php echo $this->getSkinUrl('images/twitter.png')?>" width="27" height="27" alt="Twitter" title="Twitter"/></a></li>
    		</ul>
    	</div>
    	<div class="rtTxt">© <a href="http://www.craftsvilla.com">craftsvilla.com.</a> All rights reserved.</div>
    </div>
</div>

<!-- Google Analytics -->
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-20414065-1']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<!-- /Google Analytics -->
<!--chart beat -->
<script type="text/javascript">
var _sf_async_config={uid:27315,domain:"craftsvilla.com"};
(function(){
  function loadChartbeat() {
    window._sf_endpt=(new Date()).getTime();
    var e = document.createElement('script');
    e.setAttribute('language', 'javascript');
    e.setAttribute('type', 'text/javascript');
    e.setAttribute('src',
       (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") +
       "js/chartbeat.js");
    document.body.appendChild(e);
  }
  var oldonload = window.onload;
  window.onload = (typeof window.onload != 'function') ?
     loadChartbeat : function() { oldonload(); loadChartbeat(); };
})();

</script>
<!-- end chart beat -->
<!-- reinvigorate -->
<script type="text/javascript" src="http://include.reinvigorate.net/re_.js"></script><script type="text/javascript">
try {
reinvigorate.track("jq5u0-e693o5g99h");
} catch(err) {}
</script>
<!-- end reinvigorate -->