<?php if($this->getCollection()->getSize()): ?>
<?php
$_vendor = Mage::helper('umicrosite')->getCurrentVendor();
$_helpm = $this->helper('umicrosite');
$storeurl = $_helpm->getVendorUrl($_vendor->getData('vendor_id')); ?>

    <?php if($this->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

    <?php if($this->getShowAmounts()): ?>
    <p class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>
    <?php endif ?>

    <?php if($this->getShowPerPage()): ?>
    <div class="limiter">
        <label><?php echo $this->__('Show') ?></label>
        <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select> <?php echo $this->__('per page') ?>
    </div>
    <?php endif ?>

    <?php if($this->getLastPageNum()>1): ?>
    <div class="pages">
        <ol>
        <?php if (!$this->isFirstPage()): ?>
            <li>
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $storeurl."?p=".($this->getCurrentPage()-1) ?>" title="<?php echo $this->__('Previous') ?>">
                    <?php if(!$this->getAnchorTextForPrevious()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/previous-btn.gif') ?>" width="26" height="25" align="Previous" title="Previous" border="0" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $storeurl."?p=1" ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" title="" href="<?php echo $storeurl."?p=".$this->getPreviousJumpPage() ?>">...</a></li>
        <?php endif;?>
		<?php $_lastpage = $this->getLastPageNum(); ?>
        <?php $_secondlastpage = $this->getLastPageNum()-1; ?>
        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current"><?php echo $_page ?></li>
            <?php else: ?>
                <li><a href="<?php echo $storeurl."?p=".$_page ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" title="" href="<?php echo $storeurl."?p=".$this->getNextJumpPage() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?php echo $storeurl."?p=".$_lastpage ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>

        <?php if (!$this->isLastPage()): ?>
            <li>
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $storeurl."?p=".($this->getCurrentPage()+1) ?>" title="<?php echo $this->__('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/next-btn.gif') ?>" width="26" height="25" align="Next" title="Next" border="0" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>
        </ol>

    </div>
    <?php endif; ?>

    <?php if($this->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
