<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    
    $category_arr = $_product->getCategoryIds();
    
    unset($product_category_name);
    unset($product_vendor_name);

    if($category_arr[0] != 2)
    {
    	$_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
    } 
    else {
    	$_category = Mage::getModel('catalog/category')->load($category_arr[1]);
    }
    
    $product_category_name = $_category->getName();
     
    $product_vendor_name = Mage::helper('udropship')->getVendorName($_product->getUdropshipVendor());
?>
<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    $gallery = '<div class="product-img-more">';
//    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul>';
    $i = 1;
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(112) . '" width="112" height="112" alt="' . $this->htmlEscape($_image->getLabel() .'-'. $product_category_name . '-' . $product_vendor_name.'-'.$i).'" />'
                 .  '</a></li>';
    	$i++;
    }
    $gallery .= '</ul></div>';
}
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom spriteimg">
    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
    <?php
        $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel().'-'. $product_category_name . '-' . $product_vendor_name).'" title="'.$this->htmlEscape($this->getImageLabel().'-'. $product_category_name . '-' . $product_vendor_name).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
</p>
    <?php if(isset($gallery)): ?>
        <?php echo $gallery; ?>
    <?php endif; ?>
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>


