<?php if ($marketplaces = $this->getMarketplaces()): ?>

    <p class="switcher">

        <label for="marketplace_switcher"><?php echo $this->__('Choose eBay Marketplace'); ?>:</label>

        <select id="marketplace_switcher" name="marketplace_switcher" onchange="return switchMarketplace(this);">
            <?php if ($this->hasDefaultOption()): ?>
                <option value=""><?php echo $this->getDefaultMarketplaceName(); ?></option>
            <?php endif; ?>
            <?php foreach ($marketplaces as $marketplace): ?>
                <option value="<?php echo $marketplace->getId(); ?>"<?php if($this->getMarketplaceId() == $marketplace->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;<?php echo Mage::helper('M2ePro')->__($marketplace->getTitle()); ?></option>
            <?php endforeach; ?>
        </select>

    </p>

    <script type="text/javascript">

        function switchMarketplace(obj)
        {
            var marketplaceParam = obj.value ? 'marketplace/'+obj.value + '/' : '';

            if(obj.switchParams){
                marketplaceParam+= obj.switchParams;
            }

            <?php if($this->getUseConfirm()): ?>
                if(confirm("<?php echo $this->__('Please confirm marketplace switching. All data that hasn\'t been saved will be lost.'); ?>")){
                    setLocation('<?php echo $this->getSwitchUrl(); ?>'+marketplaceParam);
                    return true;
                }
                else {
                    obj.value = '<?php echo $this->getMarketplaceId(); ?>';
                }
                return false;
            <?php else: ?>
                setLocation('<?php echo $this->getSwitchUrl(); ?>'+marketplaceParam);
            <?php endif; ?>
        }

    </script>

<?php endif; ?>