<br>
<div class="box base-mini mini-related-items aw-arp-block">
    <div class="head">
        <h4><?php echo $this->getBlockName() ?></h4>
    </div>
    <div class="content aw-arp-content">
	<?php if($this->getCount()>0) : ?>
	<?php foreach ($this->getItems() as $item) : ?>
        <div class="aw-arp-item">
            <a href="<?php echo $item->getProductUrl()?>"><img src="<?php echo $this->helper('catalog/image')->init($item,'thumbnail')->resize(50)?>" alt="<?php echo $this->htmlEscape($item->getName())?>" width="50" height="50" /></a><br>
            <a href="<?php echo $item->getProductUrl()?>"><?php echo $this->htmlEscape($item->getName())?></a><br>
            <?php echo $this->getPriceHtml($item, true)?>
        </div>
	<?php endforeach; ?>
	<?php else : ?>
	<div class="aw-arp-noitems">No related products</div>
	<?php endif; ?>
        <div class="clear"></div>
    </div>
</div>
<style type="text/css">
.aw-arp-item {
    width: <?php echo ceil(100/($this->getCount()!=0 ? $this->getCount() : 1 ))-1?>%;
}
</style>
