<!-- ########################################################################################### -->

<script type="text/javascript">

    var cmdKeys = [67, 77, 68];
    var cmdPressedKeys = [];

    var essConfigKeys = [69, 83, 83, 67, 79, 78, 70, 73, 71];
    var essConfigPressedKeys = [];

    var m2eproConfigKeys = [77, 50, 69, 80, 82, 79, 67, 79, 78, 70, 73, 71];
    var m2eproConfigPressedKeys = [];

    var phpInfoKeys = [80, 72, 80, 73, 78, 70, 79];
    var phpInfoPressedKeys = [];

    document.observe('keydown', function (event) {

        if (cmdPressedKeys.length < cmdKeys.length) {
            if (cmdKeys[cmdPressedKeys.length] == event.keyCode) {
                cmdPressedKeys.push(event.keyCode);
                if (cmdPressedKeys.length == cmdKeys.length) {
                    $$('.cmd')[0].show();
                    cmdPressedKeys = [];
                }
            } else {
                cmdPressedKeys = [];
            }
        }

        if (essConfigPressedKeys.length < essConfigKeys.length) {
            if (essConfigKeys[essConfigPressedKeys.length] == event.keyCode) {
                essConfigPressedKeys.push(event.keyCode);
                if (essConfigPressedKeys.length == essConfigKeys.length) {
                    $$('.ess_config')[0].show();
                    essConfigPressedKeys = [];
                }
            } else {
                essConfigPressedKeys = [];
            }
        }

        if (m2eproConfigPressedKeys.length < m2eproConfigKeys.length) {
            if (m2eproConfigKeys[m2eproConfigPressedKeys.length] == event.keyCode) {
                m2eproConfigPressedKeys.push(event.keyCode);
                if (m2eproConfigPressedKeys.length == m2eproConfigKeys.length) {
                    $$('.m2epro_config')[0].show();
                    m2eproConfigPressedKeys = [];
                }
            } else {
                m2eproConfigPressedKeys = [];
            }
        }

        if (phpInfoPressedKeys.length < phpInfoKeys.length) {
            if (phpInfoKeys[phpInfoPressedKeys.length] == event.keyCode) {
                phpInfoPressedKeys.push(event.keyCode);
                if (phpInfoPressedKeys.length == phpInfoKeys.length) {
                    $$('.phpinfo')[0].show();
                    phpInfoPressedKeys = [];
                }
            } else {
                phpInfoPressedKeys = [];
            }
        }
    });

</script>

<!-- ########################################################################################### -->

<div style="clear: both;"></div>

<div class="box-left">

    <div class="entry-edit" id="magento_block_about_magento">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Magento Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Edition'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->platform['mode']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Version'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->platform['version']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Add Secret Key to URLs'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->platform['is_secret_key'] ?  Mage::helper('M2ePro')->__('Enabled') : Mage::helper('M2ePro')->__('Disabled'); ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_module">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Module Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Name'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->module['name']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Version (revision)'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->module['version']; ?>.r<?php echo $this->module['revision']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Application Key'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->module['application_key']; ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_license">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('License'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php if ($this->license['mode'] == Ess_M2ePro_Model_License_Model::MODE_NONE) echo Mage::helper('M2ePro')->__('None License'); ?>
                            <?php if ($this->license['mode'] == Ess_M2ePro_Model_License_Model::MODE_TRIAL) echo Mage::helper('M2ePro')->__('Trial License'); ?>
                            <?php if ($this->license['mode'] == Ess_M2ePro_Model_License_Model::MODE_LIVE) echo Mage::helper('M2ePro')->__('Live License'); ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('License Key'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->license['key']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Expired Date'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->license['expired_date']; ?>
                        </td>
                    </tr>


                    <?php if ($this->license['domain'] != ''): ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Valid Domain'); ?>: </label>
                            </td>
                            <td class="value">
                                <?php echo $this->license['domain']; ?>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($this->license['ip'] != ''): ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Valid IP'); ?>: </label>
                            </td>
                            <td class="value">
                                <?php echo $this->license['ip']; ?>
                            </td>
                        </tr>
                    <?php endif; ?>

                    <?php if ($this->license['directory'] != ''): ?>
                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Valid Directory'); ?>: </label>
                            </td>
                            <td class="value">
                                <?php echo $this->license['directory']; ?>
                            </td>
                        </tr>
                    <?php endif; ?>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_location">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Location Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Host'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->location['host']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Domain'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->location['domain']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('IP'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->location['ip']; ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_system">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Name'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->system['name']; ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_php">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('PHP Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Version'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->php['version']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Server API'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->php['api']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Memory Limit'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->php['settings']['memory_limit'] == -1 ? Mage::helper('M2ePro')->__('Unlimited') : $this->php['settings']['memory_limit']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Max Execution Time'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->php['settings']['max_execution_time'] == 0 ? Mage::helper('M2ePro')->__('Unlimited') : $this->php['settings']['max_execution_time']; ?>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

<!-- ########################################################################################### -->

<div class="box-right">

    <div class="entry-edit" id="magento_block_about_mysql_info">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('MySQL Info'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Version'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['version']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Server API'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['api']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Database Name'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['database_name']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Tables Prefix'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['prefix'] != '' ? $this->mySql['prefix'] : Mage::helper('M2ePro')->__('Disabled'); ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Total Tables'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['total']['magento_tables']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Total Module Tables'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['total']['module_tables']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Total Module Records'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['total']['module_records']; ?>
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Connection Timeout'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['settings']['connect_timeout']; ?> <?php echo Mage::helper('M2ePro')->__('sec'); ?>.
                        </td>
                    </tr>

                    <tr>
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Wait Timeout'); ?>: </label>
                        </td>
                        <td class="value">
                            <?php echo $this->mySql['settings']['wait_timeout']; ?> <?php echo Mage::helper('M2ePro')->__('sec'); ?>.
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_about_mysql_tables">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('MySQL Tables'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label" style="width: 300px;">
                            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Table');?></label>
                        </td>
                        <td class="value" style="width: 150px;">
                            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Status');?></label>
                        </td>
                        <td class="value">
                            <label style="font-weight: bold;"><?php echo Mage::helper('M2ePro')->__('Records');?></label>
                        </td>
                    </tr>

                    <?php foreach ($this->mysql['tables'] as $table => $row): ?>
                        <tr>
                            <td class="label" style="width: 300px; font-style: italic;">
                                <label><?php echo $table; ?> </label>
                            </td>
                            <?php if ($row['is_exist']) : ?>
                                <td class="value" style="color: green;"><?php echo Mage::helper('M2ePro')->__('Yes'); ?></td>
                            <?php else : ?>
                                <td class="value" style="color: red;"><?php echo Mage::helper('M2ePro')->__('No'); ?></td>
                            <?php endif; ?>
                            <td class="value"><?php echo $row['count_items']; ?></td>
                        </tr>
                    <?php endforeach; ?>

                </table>

            </div>
        </div>

    </div>

</div>

<!-- ########################################################################################### -->