<div id="block_notice_support" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Support'); ?>">
    <?php echo Mage::helper('M2ePro')->__('Please take a look at <a href="http://docs.m2epro.com/" target="_blank">Documentation</a> and <a href="http://support.m2epro.com/" target="_blank">Knoweldgebase</a>.
    Most probably it has the answer to your question(s).<br/>
	If you still have any questions, fill in the form below to contact our Customer Support. <br/><br/>
    <b>Note:</b> We provide support during our working hours: 10 a.m. - 6 p.m. (GMT+2), mon - fri.'); ?>
</div>

<script type="text/javascript">

    // General for all tabs
	//-----------------------------
	if (typeof M2ePro == 'undefined') {
		M2ePro = {};
		M2ePro.url = {};
		M2ePro.formData = {};
		M2ePro.customData = {};
		M2ePro.text = {};
	}

	M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';
	M2ePro.url.getUserVoiceData = '<?php echo $this->getUrl('*/*/getUserVoiceData'); ?>';

    M2ePro.text.nothing_was_found_text = '<?php echo Mage::helper('M2ePro')->__('No Articles Found.') ?>';

    Event.observe(window, 'load', function() {
        SupportHandlersObj = new SupportHandlers();
        SupportHandlersObj.getUserVoiceArticles();

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    //-----------------------------

</script>

<style type="text/css">
    .support-box-right {
        float: right;
        width: 65%;
    }
    .support-box-left {
        float: left;
        width: 32%;
    }
    ul .faq a, ul .faq a:hover {
        text-decoration: none;
    }
    ul .faq h4 {
        color: #007DBF;
    }
    ul .faq .answer {
        color: black;
        border: 1px dashed #D6D6D6;
        padding: 5px;
    }
    div.no-articles {
        text-align: center;
        font-weight: bold;
        color: gray;
    }
</style>

<div id="magento_block_support_faq_container" class="support-box-left" style="display: none;">

    <div class="entry-edit" id="magento_block_support_faq" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Frequently Asked Questions'); ?></h4>
        </div>

        <div class="fieldset fieldset-wide" style="min-height: 385px;">
            <div class="hor-scroll">

                <div id="magento_block_support_faq_search" style="padding-bottom: 10px;">

                    <form action="" onsubmit="SupportHandlersObj.searchUserVoiceArticles(); return false;">
                        <table class="form-list" cellspacing="0">

                            <tr>
                                <td class="label" style="width: 300px !important;">
                                    <input id="user_voice_search_query" name="user_voice_search_query" value="" type="text" class="input-text" style="width: 95% !important;"/>
                                </td>
                                <td class="value">
                                    <?php echo $this->getChildHtml('user_voice_search'); ?>
                                </td>
                            </tr>

                        </table>
                    </form>

                </div>

                <div id="magento_block_support_faq_data" style="max-height: 345px; overflow: auto;"></div>

            </div>
        </div>

    </div>

</div>

<div id="magento_block_support_general_container">

    <form id="<?php echo $this->getForm()->getId(); ?>" method="post" action="<?php echo $this->getForm()->getData('action'); ?>" enctype="multipart/form-data">

        <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

        <div class="entry-edit" id="magento_block_support_general" collapseable="no">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Send Message To Developers'); ?></h4>
            </div>

            <div class="fieldset fieldset-wide" style="min-height: 385px;">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0">

                        <tr>
                            <td class="label">
                                <label for="subject"><?php echo Mage::helper('M2ePro')->__('Subject'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="subject" name="subject" value="" type="text" class="input-text required-entry" style="width: 275px !important;"/>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label for="contact_mail"><?php echo Mage::helper('M2ePro')->__('Contact Mail'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="contact_mail" name="contact_mail" value="" type="text" class="input-text required-entry validate-email" style="width: 275px !important;"/>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label for="contact_name"><?php echo Mage::helper('M2ePro')->__('Contact Name'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="contact_name" name="contact_name" value="" type="text" class="input-text required-entry" style="width: 275px !important;"/>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label for="type"><?php echo Mage::helper('M2ePro')->__('Type'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <select id="type" name="type" class="select">
                                    <option value="inquiry"><?php echo Mage::helper('M2ePro')->__('Inquiry'); ?></option>
                                    <option value="defect" selected="selected"><?php echo Mage::helper('M2ePro')->__('Defect'); ?></option>
                                    <option value="feature"><?php echo Mage::helper('M2ePro')->__('Feature Request'); ?></option>
                                </select>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label for="description"><?php echo Mage::helper('M2ePro')->__('Description'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <textarea id="description" name="description" class="textarea required-entry"><?php echo Mage::helper('M2ePro')->__('
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please provide any additional information below.
                                '); ?></textarea>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label ><?php echo Mage::helper('M2ePro')->__('Attachments'); ?>:</label>
                            </td>
                            <td id="more" class="value">
                                <input name="files[]" type="file" /><br />
                            </td>
                        </tr>

                        <tr>
                            <td class="label">

                            </td>
                            <td class="value">
                                <?php echo $this->getChildHtml('more_attachments'); ?>
                                &nbsp;
                                <?php echo $this->getChildHtml('send_form'); ?>
                            </td>
                        </tr>

                    </table>

                </div>
            </div>

        </div>
    </form>

</div>