<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_Dropship
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>

<?php if ($_entity = $this->getEntity()): ?>
<?php
   	$_order_id = $_entity->getOrder();
		$_shippingAddress_value = $_order_id->getShippingAddress();
		$country_id_value = $_shippingAddress_value->getCountry_id();
    $autoRefundedamount = Mage::helper('udropship')->getrefundCv($_entity->getId());
    $helpc  =   Mage::helper('udropship');	
    $user = Mage::getSingleton('admin/session')->getUser(); //Added by Ankit for restriction on Damage/Lost in Transit
    $user = $user->email; //Added by Ankit for restriction on Damage/Lost in Transit
    $shipmentId         =   $_entity->getIncrementId();
    $shipmentDetail     =   Mage::getModel('sales/order_shipment')->load($_entity->getIncrementId());

    $vendorId           =   $_entity->getUdropshipVendor();
    $vendorDetails      =   Mage::getModel('udropship/vendor')->load($vendorId);
     $vendorPincode      =   $vendorDetails->getZip();
     $shipping_postcode  =   $_shippingAddress_value->getPostcode();
    #echo 'vendorId:'.$vendorId.'postalcode:'..':::'.$vendorPincode; exit;
     $servecable         =   $helpc->getServicesendd($shipping_postcode,$vendorPincode);
     $reverse_pick       =   $servecable->servicable;

    $rpu_status_arr    =   array('Return Requested','Return In Transit','Return Delivered','Return RTO');
		
?>

<?php $shipmentArray =  Mage::getSingleton('udropship/source')->setPath('shipment_statuses')->toOptionHash();
			$currentShipmentStatusId = $this->getEntity()->getUdropshipStatus() ;
			$currentShipmentStatus = $shipmentArray[$currentShipmentStatusId];
?>
        <!-- Add code for prevent change status when its set refund initiated (12)/COD RTO (25) -->
<?php $checkShipementStatus = array('12','25');
			$shipmentStatusId = $this->getEntity()->getUdropshipStatus() ;
			
			// access array
			$userAccess = array('robin.sequeria@craftsvilla.com','sameer.mantri@craftsvilla.com','Rohit@craftsvilla.com','anderson.kokken@craftsvilla.com','jyoti.arora@craftsvilla.com','tribhuvan@craftsvilla.com','niraj@craftsvilla.com','gaurav@craftsvilla.com','dilipcscare@craftsvilla.com','santoshc@craftsvilla.com','samidha@craftsvilla.com','Seemag@craftsvilla.com','poojaminac@craftsvilla.com','Ayeshab@craftsvilla.com');
			
		  $payOutUserAccess = array('pravin@craftsvilla.com','bhupendrar@craftsvilla.com','gitap@craftsvilla.com');
			
			$refundUserAccess = array('pravin@craftsvilla.com');
			
		/* disable shipment status which is older than 3 month */
		$monthDiff =  strtotime(date("Y-m-d", strtotime($_entity->getUpdatedAt())) . " +3 month");
		$finaldate =  date('Y-m-d H:i:s', $monthDiff);
		$todaydate = date('Y-m-d H:i:s',strtotime(date('Y-m-d H:i:s', strtotime(NOW()))));
			
		$inc_id = $_entity->getIncrementId();
		$read = Mage::getSingleton('core/resource')->getConnection('custom_db');
		$query = "select shipmentpayout_status from shipmentpayout where shipment_id=".$inc_id;
		$result = $read->query($query)->fetch();
		$read->closeConnection();
		
		$accessFlag = 0 ; $flag = 0; $payoutFlag = 0; $refundFlag = 0;
		$payoutStatus =  $result['shipmentpayout_status'];
		//var_dump($payoutStatus);
		
		if(in_array($shipmentStatusId,$checkShipementStatus))
		{
				if(in_array($user,$userAccess)) {
						$accessFlag = 0;
				} else {
						$accessFlag = 1;
				}
		}
		if($todaydate > $finaldate)
		{
				if(in_array($user,$userAccess)) {
						$flag = 0;
				} else {
						$flag = 1;
				}
		}
		if($payoutStatus == '1')
		{
				if(in_array($user,$payOutUserAccess)) {
						$payoutFlag = 0;
				} else {
						$payoutFlag = 1;
				}
		}
		
		if(in_array($user,$refundUserAccess)){
				$refundFlag = 0;
		} else {
				$refundFlag = 1;	
		}
		
?>

<!-- following shipment status removed

$_label == 'Shipped To Craftsvilla' || $_label == 'Pending Pickup' || $_label == 'Packing Slip Printed' ||  $_label == 'QC Rejected by Craftsvilla' || $_label == 'Partially Refund Initiated' || $_label == 'COD Manifest Shared' || 
$_label == 'COD Shipment Picked Up'|| $_label == 'Return Recieved From Customer' || $_label == 'Partially Recieved' || $_label == 'Returned By Customer' || $_label == 'Partially Shipped' || $_label == 'Received in Craftsvilla' ||

in_array($shipmentStatusId,$checkShipementStatus) || 
-->

	
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="comment_status"><?php echo Mage::helper('sales')->__('Status') ?></label><br/>

    
       <select name="comment[status]" class="select" id="comment_status" onchange="showfield(this.options[this.selectedIndex].value)" <?php if($accessFlag == '1' || $flag == '1' || $payoutFlag == '1') echo 'disabled' ?>>

	<?php 
 
      foreach (Mage::getSingleton('udropship/source')->setPath('shipment_statuses')->toOptionHash() as $_code=>$_label):
        		/*
        		*Craftsvilla Comment
        		*Changed Shipped to Shipped To Customer and added one more condition Shipped To Craftsvilla
        		*Added by Suresh on 31-05-2012
        		*/
        	
				if($_label == '' || $_label == 'Processing' || $_label == 'Shipped To Customer' || $_label == 'Delivered' || $_label == 'Refund Initiated' || $_label == 'Not Delivered' || $_label == 'Charge Back' || $_label == 'Canceled' || $_label == 'Product Out Of Stock' || $_label == 'Dispute Raised' || $_label == 'Shipment Delayed' || $_label == 'Refund To Do' || $_label == 'Accepted' || $_label == 'COD RTO' || $_label == 'Accept To Ship Directly To Customer'|| $_label == 'Handed To Courier' || $_label == 'Refund Voucher Requested' || $_label == 'Refund Voucher Sent' || $_label == 'PREPAID RTO' || ($_label=='Damage/Lost in transit' && $user == "pravin@craftsvilla.com" || $user == "tarun@craftsvilla.com" || $user == "Ayeshab@craftsvilla.com" || $user == "roshan@craftsvilla.com")): //Modifed by Ankit for restriction on Damage/Lost in Transit
        ?>
				   <option value="<?php echo $_code ?>"<?php if($_code==$this->getEntity()->getUdropshipStatus()): ?> selected="selected" <?php endif; ?>><?php echo $_label ?></option>
			  <!-- check for current status with allow status -->
				<?php  elseif($currentShipmentStatusId == $_code  && !in_array($_label,$rpu_status_arr)): ?>
					 <option value="<?php echo $_code ?>"<?php if($_code==$this->getEntity()->getUdropshipStatus()): ?> selected="selected" <?php endif; ?>><?php echo $_label ?></option>
				<?php endif; ?>
			   
				<?php
				   if($reverse_pick==1){
            if(in_array($_label,$rpu_status_arr)){
        ?>
            <option value="<?php echo $_code ?>"<?php if($_code==$this->getEntity()->getUdropshipStatus()): ?> selected="selected" <?php endif; ?>><?php echo $_label ?></option>
       <?php } } ?>
			  <?php endforeach; ?>
        </select>
<!--mstart-->
<select  id="disputeremarks"  name="disputeremarks"  style="display: none;margin-top:8px; width:203px; ">
	<option value="" >Select Reason</option>
	<option value="Bad Quality">Bad Quality</option>
	<option value="Damaged/ Defective">Damaged/ Defective</option>
	<option value="Not as per photo/ Description">Not as per photo/ Description</option>
	<option value="Did not like">Did not like</option>
	<option value="Late delivery">Late delivery</option>
	<option value="Stitched/ Unstitched">Stitched/ Unstitched</option>
	<option value="Multiple Quantity Ordered">Multiple Quantity Ordered</option>
	<option value="Other">Others (Please add in remarks)</option>
</select>
<!--mend-->
<br/>
<div id="returnRequest" style="display: none;margin-top:6px;margin-bottom:6px"></div>
       <?php //echo $this->getUrl('udropshipadmin/adminhtml_qcreject/qcreject/', array('shipment_id'=>$_entity->getId()));exit; ?>



	<!--Added By Dileswar on dated 30-03-2013 for add a extra text box to get the refund amount-->
		<!--mstart-->
				<div id="div1" style="display: none" >
						<label for='' style="width: 350px; margin: 5px;">Refund Amount of <font face="Tahoma" size="2" color="green"> Rs: <?php echo $autoRefundedamount?></label> </font><br>
						<input type="text" <?php if($refundFlag == 1) { echo 'readonly';} ?>  name="refundamount" value = "<?php echo $autoRefundedamount?>" id="refundamount" />				 </div>
		<!--mend-->
    <div id="div2"></div>
		<script type="text/javascript">
		    $('comment_status').origValue = $('comment_status').value
	  </script>

        </span>
          <form name="qcreject" action="<?php echo $this->getUrl('udropshipadmin/adminhtml_shipment/qcreject/', array('shipment_id'=>$_entity->getId())); ?>" method="post" enctype="multipart/form-data">
         Attach Image: <input type="file" name="import_image" class="input-file" id="import_image"/>
                <input type="submit" value="Send QC Reject" class="form-button" style="margin-top:5px"/>
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
               <!-- <textarea name="comment[comment]" rows="3" cols="5" style="height:3em; width:50%; display:none" id="comment_comment"></textarea>-->



    <span class="field-row">
        <label class="normal" for="comment_comment"><?php echo Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="comment_comment"></textarea>
    </span>

    <div class="f-left">
        <input name="comment[is_vendor_notified]" type="checkbox" id="vendor_comment_notify" value="1" /><label class="normal" for="vendor_comment_notify"> <?php echo Mage::helper('sales')->__('Notify Vendor by Email') ?></label><br />
        <input name="comment[is_visible_to_vendor]" type="checkbox" id="comment_visible" value="1" /><label class="normal" for="comment_visible"> <?php echo Mage::helper('sales')->__('Visible to Vendor') ?></label><br />
        <?php if ($this->canSendCommentEmail()): ?>
        <input name="comment[is_customer_notified]" type="checkbox" id="customer_comment_notify" value="1" /> <label class="normal" for="customer_comment_notify"><?php echo Mage::helper('sales')->__('Notify Customer') ?></label>
        <?php endif; ?>
    </div>
    <div class="f-right">
        <?php echo $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $_comment->getUdropshipStatus() ?></strong><br/>
            <small><?php echo $this->helper('udropship')->__('Vendor') ?>
            <strong class="subdue">
                <?php if ($_comment->getIsVendorNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
            </strong></small>
            <span class="separator">|</span>
            <small><?php echo $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
                <?php if ($_comment->getIsCustomerNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
            </strong></small>
            <br/>
            <?php echo Mage::helper('core')->htmlEscape($_comment->getComment(), array('b','br','strong','i','u')) ?>
        </li>
    <?php endforeach; ?>
    </ul>
    </form>
		
<?php
		$shipmentId = $this->getRequest()->getParam('shipment_id');
		$trackingCollection = Mage::getResourceModel('sales/order_shipment_track_collection')
												->addAttributeToSelect('*')
												->addAttributeToFilter('parent_id',$shipmentId);
		$trackId = $trackingCollection->getFirstItem();
		$trackid = $trackId['number'];
?>

<script type="text/javascript">
function submitComment() {
     var currentStatusId = '<?php echo $shipmentStatusId ?>'; 
		 var monthCheck = '<?php echo $flag ?>' ;
		 var payoutFlag = '<?php echo $payoutFlag ?>';
		 var userAccess = '<?php echo $accessFlag ?>';
		
		 if(((currentStatusId == '25' || currentStatusId == '12') && userAccess == '1') || monthCheck == '1' || payoutFlag == '1' )
     {
     alert('Futher Modification not allow at this stage.');
     return false ;
     }
     else if (validateShipmentStatusSubmit()) {
     submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getUrl('udropshipadmin/adminhtml_shipment/addComment', array('shipment_id'=>$_entity->getId())) ?>')
     }

    //if (validateShipmentStatusSubmit()) {
    //    submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getUrl('udropshipadmin/adminhtml_shipment/addComment', array('shipment_id'=>$_entity->getId())) ?>')
    //}
}

function validateShipmentStatusSubmit()
{
    if (<?php echo (int)Mage::helper('udropship')->isUdpoActive()?> == 0) return true;
    if ($('comment_status').value == $('comment_status').origValue) return true
    switch ($('comment_status').value) {
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_CANCELED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will cancel shipment (if possible).') ?>');
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_SHIPPED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as shipped to customer (and if possible change PO status as well).') ?>');
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_SHIPPED_CRAFTSVILLA ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as shipped to craftsvilla (and if possible change PO status as well).') ?>');
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_OUTOFSTOCK_CRAFTSVILLA ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as Product Out Of Stock') ?>');
		case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_DELIVERED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as delivered (and if possible change PO status as well).') ?>');

        default:
            return true;
    }
}
<!--Added By Dileswar on dated 30-03-2013 for add a extra text box to get the refund amount-->
function showfield(name)
		{
				if(name==23)
				{
		
				document.getElementById('div1').style.display = "block";
				}
		
				else
				{
				document.getElementById('div1').style.display = "none";
				}
				if(name==20)
				{
				document.getElementById('div2').innerHTML= '<input type="checkbox" name ="disputeMail" value = "" onclick="sendDisputeRaisedEmailtoCustomer();"> Send return address to customer</input><br/>';
				document.getElementById('disputeremarks').style.display = "block";
				}
				else
				{
					document.getElementById('div2').innerHTML='';
					document.getElementById('disputeremarks').style.display = "none";
				}
				if(name==37){
						document.getElementById('returnRequest').innerHTML='<select id="returnRequestRemark" name="returnRequestRemark"><option value="" >Select Reason</option><option value="Product different from picture / description">Product different from picture / description</option><option value="Wrong Size / Fitting">Wrong Size / Fitting</option><option value="Poor Quality">Poor Quality</option><option value="Change of Mind">Change of Mind</option><option value="Late Delivery">Late Delivery</option><option value="Other">Others (Please add in remarks)</option></select>';
						document.getElementById('returnRequest').style.display = "block";
				}
				else
				{
					document.getElementById('returnRequest').style.display = "none";
				}
		}


if ($('submit_comment_button')) {
    $('submit_comment_button').observe('click', function(event){
			var shipmentStatus = $('comment_status').value;
			var refundAccess = '<?php echo $refundFlag ?>';
			
			if(shipmentStatus == '23' && refundAccess == '1'){
				alert('Further Modification Not Allow');
				return false;
			}
			
			if(shipmentStatus == '6'){
				var reloadurl = '<?php echo $this->getUrl('udropshipadmin/adminhtml_shipment/senddRequestOnDelete', array('track_id'=>$trackid)) ?>';
				var trackNo = '<?php echo $trackid ?>';
				new Ajax.Request(reloadurl, {
						method: "get",
						requestHeaders: {Accept: "application/json"},
						parameters: {track_id:trackNo},
						onSuccess: function(transport) {
							var response = transport.responseText.evalJSON();
							if(response.error){
								/* condition when track not generated for shipment i.e order not accepted by vendor yet.
									 allow to cancelled shipment when tracking number not generated.
								*/
								if(response.track_no){
									alert(response.message);
								}
							}
							submitComment();
						},
						onFailure: function(transport) {
							var response = transport.responseText.evalJSON();
							if(response.error){
								alert(response.message);
							} else {
								submitComment();
							}
						}
				});
			} else {
					submitComment();
			}		    
		});
}

</script>



</div>
<?php endif; ?>
