<?php /*custom breadcrumbs*/

$hlp = Mage::helper('generalcheck');
$ismobile = $hlp->ismobile();

if(!$ismobile)
{?>

<br />


<div class="cart">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-title">
        <h1>You’re Purchasing:</h1>
	</div>
	
    <?php echo $this->getChildHtml('form_before') ?>
	<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
		<table width="72%" cellspacing="0" cellpadding="0" id="cart-table">
			<tr><td colspan="5"><div class="topLine"></div></td></tr>
			<tr height="26">
				<td width="20%">&nbsp;</td>
				<td width="30%" class="cartTableHead"><?php echo $this->__('DESCRIPTION') ?></td>
				<td width="11%" class="cartTableHead" align="center"><?php echo $this->__('QTY') ?></td>
				<td width="12%" class="cartTableHead" align="center"><?php echo $this->__('PRICE') ?></td>
				<td width="5%" class="cartTableHead" align="center"><?php echo $this->__('REMOVE') ?></td>
			</tr>
			<tr><td colspan="5"><div class="topLine"></div></td></tr>
			<tbody>
                          <?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endforeach  ?>
<script type="text/javascript">
					jQuery(document).ready(function(){
						jQuery('.num_up_cart').click(function(){
							var item_id = jQuery(this).parent().attr('data-id');
							var cur_value_plus = jQuery('#qty_cart_'+item_id).attr('value');
							jQuery('.num_down_cart').css('display','block');
							cur_value_plus++;
							jQuery('#qty_cart_'+item_id).attr('value',cur_value_plus);
						});
						jQuery('.num_down_cart').click(function(){
							var item_id = jQuery(this).parent().attr('data-id');
							var cur_value_plus = jQuery('#qty_cart_'+item_id).attr('value');
							cur_value_plus--;
							jQuery('#qty_cart_'+item_id).attr('value',cur_value_plus);
								if(cur_value_plus==1){
									jQuery('.num_down_cart').css('display','none');
								}
						});
					});
				</script>
	
			</tbody>
			<tr>
				<td colspan="5"><button type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="spriteimg updateCart"></button></td>
			</tr>
		</table>
	</form>
<div id="checkout-total">
		<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="spriteimg continue_shop" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"></button>
		<!--<div id="shipTo">
			<select name="shipTo-select" id="shipTo-select">
				<option value="Shipping To...">Shipping To...</option>
			</select>
		</div>-->
		<a href="#coupon" class="coupon">Apply Discount Code</a>
		<div id="coupon" style="display:none;"><?php echo $this->getChildHtml('coupon') ?></div>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('.coupon').fancybox();
			});
		</script>
		
		<?php echo $this->getChildHtml('totals'); ?>
		
		<?php if(!$this->hasError()): ?>
            
		<?php foreach ($this->getMethods('methods') as $method): ?>
			<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
		   <?php echo $methodHtml; ?>
			<?php endif; ?>
		<?php endforeach; ?>
		
		<?php endif; ?>
	</div>
	
	<div class="clear"></div>
	
    <?php $cat_id = 1137; // set desired category id
	$category = Mage::getModel('catalog/category')->load($cat_id);
	$_helper = $this->helper('catalog/output');
	//$_customerLoggedInFlag = Mage::getSingleton('customer/session')->isLoggedIn();

	$products1 = $category->getProductCollection()->addCategoryFilter($category)->addAttributeToSelect('*')->addAttributeToFilter('status', 1)->addAttributeToFilter('visibility', array('2','3','4'))
	->joinField('inventory_in_stock', 'cataloginventory_stock_item', 'is_in_stock', 'product_id=entity_id');
	$products1->getSelect()->order('updated_at desc')->limit(4);
//echo $products1->getSelect()->__toString();exit;?>
    
	

<?php
//Dekstop view

 }

else{
$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
 
if($breadcrumbs)
{
	$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
 
	$breadcrumbs->addCrumb('cart', array('label'=>'Cart', 'title'=>'Cart'));
 
	echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
}
else {
	echo '<div class="breadcrumbs">
    <ul>
                    <li class="home">
                            <a title="Home Page" href="'.Mage::getBaseUrl().'">Home</a>
                                        <span>&nbsp; <img height="14" width="7" alt="devider" src="http://www.craftsvilla.com/skin/frontend/default/craftsvilla2012/images/breadcrumbs-div.gif">&nbsp;</span>
                        </li>
                    <li class="cart">
                            <strong>Cart</strong>
                                    </li>
            </ul>
</div><div class="breadcrumbs_bottom"></div>';
}	
?>
<br />


<div class="cart">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-title" >
<br>        <h1 style="font-size: 38px;">You’re Purchasing:</h1>
	</div>
	
    <?php echo $this->getChildHtml('form_before') ?>
	<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
		<div  style="float: none;">

			
				<?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endforeach  ?>
				<script type="text/javascript">
					jQuery(document).ready(function(){
						jQuery('.num_up_cart').click(function(){
							var item_id = jQuery(this).parent().attr('data-id');
							var cur_value_plus = jQuery('#qty_cart_'+item_id).attr('value');
							jQuery('.num_down_cart').css('display','block');
							cur_value_plus++;
							jQuery('#qty_cart_'+item_id).attr('value',cur_value_plus);
						});
						jQuery('.num_down_cart').click(function(){
							var item_id = jQuery(this).parent().attr('data-id');
							var cur_value_plus = jQuery('#qty_cart_'+item_id).attr('value');
							cur_value_plus--;
							jQuery('#qty_cart_'+item_id).attr('value',cur_value_plus);
								if(cur_value_plus==1){
									jQuery('.num_down_cart').css('display','none');
								}
						});
					});
				</script>
			
		
				<button type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="newaddcartbutton12092014" style="width: 100%;"> UPDATE </button>
			
		</div>
	</form>

	<div id="checkout-total" style="float: none;width: 99%;margin-top: 100px;">
		<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="newaddcartbutton12092014" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" style="width:100%; background-color: #93C4BE;border: 4px solid #93C49D;">CONTINUE SHOPPING</button>
<br><br>
		<div class="coupon" style="font-size: 38px;">Discount Code</div>
		<div style="width: 100%; height: 100%;" id="coupon" style="display:none;"><?php echo $this->getChildHtml('coupon') ?></div>

		
		<?php echo $this->getChildHtml('totals'); ?>
		
		<?php if(!$this->hasError()): ?>
            
		<?php foreach ($this->getMethods('methods') as $method): ?>
			<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
		   <?php echo $methodHtml; ?>
			<?php endif; ?>
		<?php endforeach; ?>
		
		<?php endif; ?>
	</div>
	
	<div class="clear"></div>
	
    <?php $cat_id = 1137; // set desired category id
	$category = Mage::getModel('catalog/category')->load($cat_id);
	$_helper = $this->helper('catalog/output');
	$products1 = $category->getProductCollection()->addCategoryFilter($category)->addAttributeToSelect('*')->addAttributeToFilter('status', 1)->addAttributeToFilter('visibility', array('2','3','4'))
	->joinField('inventory_in_stock', 'cataloginventory_stock_item', 'is_in_stock', 'product_id=entity_id');
	$products1->getSelect()->order('updated_at desc')->limit(4);
//echo $products1->getSelect()->__toString();exit;?>
    
	
<?php
}

 ?>

