<div class="about_nav"> 
	<div class="AccountLeftNavTop">
		<h3>Our Company</h3>
	</div>
	<!--<?php $_links = $this->getLinks(); ?>
	<ul>
		<?php foreach ($_links as $_link): ?>
		<li class="AccLeftNav">
			<a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong></a>
		</li>
		<?php endforeach; ?>
	</ul>-->
	<ul>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('left_menu_static_pages')->toHTML();?></div>
	</ul>
</div>

<?php /* $_links = $this->getLinks(); ?>
<?php $_index = 1; ?>
<?php $_count = count($_links); ?>
<?php foreach ($_links as $_link): ?>
	<?php $_last = ($_index++ >= $_count); ?>
	<?php if ($this->isActive($_link)): ?>
		<li class="AccLeftNav current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
	<?php else: ?>
		<li class="AccLeftNav" <?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
	<?php endif; ?>
<?php endforeach;  */?>