<?php  
if(Mage::registry('current_category')) {
$categoryName=Mage::registry('current_category')->getName();
//if($categoryName == 'Jewelry' || $categoryName == 'Jewellery'){?>


<?php //}
	if($categoryName == 'Bags'){
	?>
		<!-- Google Code for Bags Re-Market List Remarketing List -->
		<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "dF9TCNm9wgMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
		<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=dF9TCNm9wgMQ996vzgM&amp;guid=ON&amp;script=0"/>
		</div>
		</noscript> 
    
	<?php
	}
    elseif($categoryName == 'Necklaces')
	{
	?>
		<!-- Google Code for Necklaces Remarketing List -->
		<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "nDF-CPmCxwMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=nDF-CPmCxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
		<?php
        }
        elseif($categoryName == 'Anklets')
        {
		?>
		<!-- Google Code for Anklets Remarketing List -->
        <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "4_FsCPGDxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=4_FsCPGDxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
		<?php
        }
        elseif($categoryName == 'Rings')
        {
		?>
        <!-- Google Code for Rings Remarketing List -->
        <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "W5FnCOmExwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=W5FnCOmExwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
        <?php
        }
        elseif($categoryName == 'Earrings')
        {
		?>
        <!-- Google Code for Earrings Remarketing List -->
        <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "EncvCNmGxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=EncvCNmGxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
		<?php
        }
        elseif($categoryName == 'Bracelets & Bangles')
        {
		?>
        <!-- Google Code for Bracelets Remarketing List -->
        <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "2RlqCNGHxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=2RlqCNGHxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
        
	<?php
	}
}
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>



    
<div class="clear"></div>

<div class="category-products">

 

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style floatr" style="left:262px;padding-bottom: 15px;position: absolute;top:0px; *top:3px; top /*\**/: 0px\9">
 <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
 <a class="addthis_button_tweet"></a>
 <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
 <!--<a class="addthis_counter addthis_pill_style"></a>-->
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f34adfd2fa3a766"></script>
<!-- AddThis Button END -->


    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
					<div class="col-1">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						 <?php $vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>
               <?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>
					
					<div class="col-2">
						<div class="desc std">
							<?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
					
                </div>
            </div>
        </li>
    <?php endforeach; ?>

    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode 
		$_collectionSize = $_productCollection->count();
    	$_columnCount = $this->getColumnCount();
    	$i=0; 
		foreach ($_productCollection as $_product):
        if ($i++%$_columnCount==0):
	?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <div class="prCnr">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<!--<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(205,205); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />-->
					<img class="lazy" long-desc="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200,200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" src="<?php echo $this->getSkinUrl('images/lazy_image_loader/loader.gif'); ?>"/>

				</a>
                <h1><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h1>
                <?php
					$vendorinfo = Mage::helper('udropship')->getVendor($_product);
					$storeurl = ''; 
					$storeurl = Mage::helper('umicrosite')->getVendorUrl($vendorinfo->getVendorId());
					if($storeurl) {
				?>
                <p class="vendorname">By: <a href="<?php if($storeurl) echo $storeurl; else echo '#';?>" title="<?php echo $vendorinfo->getVendorName();?>" target="_blank"><?php echo $vendorinfo->getVendorName();?></a></p>
                <?php } ?>
                <!--<div class="vendorname">
				  <?php if ($_product->getShortDescription()):?>
				  <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
				  <?php endif;?>
				</div>-->
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <!-- magento original price -->
                <?php echo $this->getPriceHtml($_product, true);?>
                <!-- magento original price -->
                
                <!-- customize price-->
                <!--<?php //if ($_product->getSpecialPrice()==0):?>
				<h3 id="home"><?php //echo Mage::helper('core')->currency($_product->price, true, false); ?></h3>
               <?php// else: ?>
                <h3 id="home"><?php //echo Mage::helper('core')->currency($_product->SpecialPrice, true, false); ?></h3>
                <h5><?php //echo Mage::helper('core')->currency($_product->price, true, false); ?></h5>
               <?php //endif; ?>-->
                <!-- customize price-->
               <div class="clear"></div>
               
               
		         <?php /*?><div class="shrtDscrption">
                 		<?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
					  <?php if ($_product->getShortDescription()):?>
                      <?php //echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                      <?php endif;?>
                 </div><?php */?>
                 
                 
                 
                <!--<div class="wrapper border1">
                <div class="indent">
                <?php if($_product->isSaleable()): ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart fright" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                
                <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                </div>-->
                </div>
               <!-- <iframe src="http://www.facebook.com/plugins/like.php?layout=button_count&href=<?php// echo $_product->getProductUrl() ?>"  scrolling="no" frameborder="0" allowTransparency="true" class="fblikebtn" title="Like it!"></iframe> <img src="<?php //echo $this->getSkinUrl('images/fblike.gif')?>" class="fbthumbic" alt="" title="Like it!"  />-->
            </li>
            
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div>
<?php endif; ?>
<!--Code for vizury code(Dileswar)-->

<?php
if(Mage::registry('current_category')) { 
$catId=Mage::registry('current_category')->getId();
$category=Mage::getModel('catalog/category')->getCategories($catId);

if($category)
{
	foreach($category as $cat)
	{
		$subcatId1=$cat->getId();
		$subcategory=Mage::getModel('catalog/category')->getCategories($subcatId1);
		if($subcategory)
		{
			foreach($subcategory as $subcat)
			{		
				$subcatId2 = $subcat->getId();break;
			}
		}
		else
		{
			$subcatId2='';
		}
	break;																	
	}
}
else
{
	$subcatId1='';
	$subcatId2='';	
}
}
?>
<iframe src="http://www.vizury.com/analyze/analyze.php?account_id=VIZVRM209&param=e200&catid=<?php echo $catId; ?>&subcat1id=<?php echo $subcatId1 ;?>&subcat2id=<?php echo $subcatId2 ;?>&section=1&level=1" scrolling="no" width="1" height="1" marginheight="0" marginwidth="0" frameborder="0"></iframe>
