<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="detailCotainer">
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div class="product-view">
    	<div>
            <div>
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
		</div>
    </div>
	<div class="details">
		<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        <p>
			<?php if ($_product->getShortDescription()):?>
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
            <?php endif;?>
        </p>
        
     <ul class="shipcost">
        
        <?php 
       
	   $_shipcost = array(); ?>
<?php if ($_product->getTypeId() == "configurable") {
      $associated_products = $_product->getTypeInstance()->getUsedProducts();
   
	      $i=0;
          foreach ($associated_products as $assoc)
            {
                $assocProduct =Mage::getModel('catalog/product')->load($assoc->getId());
                $__shipcost = $assocProduct->getData('shippingcost');
                if (empty($__shipcost))
                $_shipcost[$i]= 0;
                else
                $_shipcost[$i]= $__shipcost;
                $i++; 
            } 
            $_shippingcost = max($_shipcost);
        } else 
        {
            $_shippingcost = $_product->getData('shippingcost');     
        }
	   
	   
	   
	   
	         
        if(empty($_shippingcost) || $_shippingcost=='0')		
        echo "<li>Domestic Shipping : <span>FREE</span></li>";
        else
        echo "<li>Domestic Shipping Cost (Rs): <span>".number_format($_shippingcost,2); "</span></li>" 
		
			
        ?>         
              
            
                     
        
        
        
         <?php
         $_helpv = $this->helper('udropship');
		 $_helpm = $this->helper('umicrosite');
		$vendorIfo = $_helpv->getVendor($_product);
       /* $level = Mage::getStoreConfig('udropship/microsite/subdomain_level');
        $url = parse_url(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB));

        $hostArr = explode('.', trim($url['host'], '.'));
        $baseUrl = $url['scheme'].'://'.join('.', $hostArr).(isset($url['path']) ? $url['path'] : '/').$vendorIfo_ship->getUrlKey();*/
        $storeurl = $_helpm->getVendorUrl($vendorIfo->getData('vendor_id'));
        echo "<li>See similar products from this Seller: ";
        ?> 
        <span> <a href="<?php if($storeurl) echo $storeurl; else echo '#';?>" target="_blank"> <?php echo $vendorIfo->getData('vendor_name') ?> </a></span></li>
		<?php
			if($_product->getInternationalShipping()==1)
				echo "<li>This Product is available for International Shipping.</li>";
			else
				echo "<li>This Product is not available for shipping outside India.</li>";
		?>
		
		</ul>
        
       
       
       
        
        <div id="dtlPrice">
            <ul>
                <li><?php echo $this->getChildHtml('product_type_data') ?>
                
                
                
                
               
                </li>
                <li>
                    <?php $_product = $this->getProduct(); ?>
                    <?php if($_product->isSaleable()): ?>
                    <?php if(!$_product->isGrouped()): ?>
                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" />
                    <?php endif; ?>
                    <?php endif; ?>
                    
                   
                    
                </li>
                <li class="positionrela"><?php $buttonTitle = $this->__('Add to Cart'); ?>
                <input type="submit" value="<?php echo $buttonTitle ?>" class="addToCart" title="<?php echo $buttonTitle ?>" />
                   <a href="JavaScript:newPopup('<?php echo $this->getUrl('size-chart') ?>');" title="Size Chart" class="sizechartlink">Size Chart</a>
                
                
                </li>
                <li class="confprocont">
                <?php if (!$this->hasOptions()):?>
                <?php //echo $this->getChildHtml('extra_buttons') ?>
                <?php else:?>
                <?php //echo $this->getChildHtml('addto') ?>
                <?php endif; ?>
                <?php echo $this->getChildHtml('other');?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
                </li>
            </ul>
        </div>
        
       
        
	</div>
	<div class="clear2"></div>
	<div class="blueScl" style="position:relative; z-index:0;">
       <!-- <ul>
        	<li><a class="fb_share" name="fb_share" type="button" href="http://www.facebook.com/sharer.php?u=<?php// echo $currUrl;?>">Share</a></li>
        	<li style="margin-top:5px"><a href="http://twitter.com/share" class="twitter-share-button" data-count="none" data-via="YourTwitterID">Tweet</a></li>
        	<li><?php// if ($this->canEmailToFriend()): ?>
        	<a href="<?php// echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php// echo $this->__('Email to a Friend') ?>
            </a>
        	<?php// endif; ?>
            </li>
        	<li><?php// echo $this->getChildHtml('addto') ?></li>
        </ul>-->
        
        
        
        <!-- AddThis Button BEGIN -->
<?php
 
 $purl= $this->helper('core/url')->getCurrentUrl();


 
?>

<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_button_pinterest" pi:pinit:layout="horizontal" pi:pinit:media="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" pi:pinit:url="<?php echo $purl; ?>"></a>
<!--<a class="addthis_counter addthis_pill_style"></a>-->
<span style="padding-left:10px;"> <?php echo $this->getChildHtml('extrahint') ?></span>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f34adfd2fa3a766"></script>
<!-- AddThis Button END -->
         
</div>
    
 


    
    
	<div class="clear"></div>
  
    



 <!--tab code start-->      
  <script src="<?php echo $this->getSkinUrl('js/tabs.js')?>"></script>
  <link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/tabcss.css')?>" type="text/css">
       <!--tab code start end--> 
               
<div id="tabs">
  <ul class="talsnew">
    <li class="ui-tabs-nav-item selected" id="tabone"><a onclick="menu(0);">Product Detail</a></li>
    <li class="ui-tabs-nav-item" id="tabtwo"><a onclick="menu(1);">Policies Information</a></li>
    </ul>
<span class="clr"></span>
  <div id="fragment-1" class="ui-tabs-panel displayblock">
  	<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <?php if ($title = $this->getChildData($alias, 'title')):?>
        <?php echo $this->escapeHtml($title); ?>
        <?php endif;?>
        <?php echo $html; ?>
        <?php endforeach;?>
  </div>
  <div id="fragment-2" class="ui-tabs-panel displaynone">
       <?php
		if($vendorIfo) {
		?>
      <ul class="polinfo">
       <?php if($vendorIfo->getShipHandlingTime()) { ?><li><label>Shipping handling Time:</label><p class="value"><?php echo $vendorIfo->getShipHandlingTime();?></p></li><?php } ?>
       <?php if($vendorIfo->getItemLocation()) { ?><li><label>Item Location:</label><p class="value"><?php echo $vendorIfo->getItemLocation();?></p></li><?php } ?>
       <?php if($vendorIfo->getItemReturnInDays()) { ?><li><label>Item to be Returned in:</label><p class="value"><?php echo $vendorIfo->getItemReturnInDays();?></p></li><?php } ?>
       <?php if($vendorIfo->getRefundMadeAs()) { ?><li><label>Refund will be given as:</label><p class="value"><?php echo $vendorIfo->getRefundMadeAs(); ?></p></li><?php } ?>
       <?php if($vendorIfo->getRefundCostBearer()) { ?><li><label>Return cost paid by:</label><p class="value"><?php echo $vendorIfo->getRefundCostBearer(); ?></p></li><?php } ?>
       <?php
			$policyDetails = ''; 
			if($_product->getReturnPolicyDetail())
				$policyDetails = $_product->getReturnPolicyDetail();
			elseif($vendorIfo->getReturnPolicyDetail())
				$policyDetails = $vendorIfo->getReturnPolicyDetail();
			if($policyDetails != '') {
		?>

				<li class="clr"><label>Return Policy Details:</label><p class="value"><?php echo $policyDetails; ?></p></li><?php } ?>
      
      </ul>
      <?php } ?>        
       
       
       
  </div>
 
</div>
<!-- TABS -->
    <!--tab code start end-->      
<!--        <div class="clear"></div>
    <p class="contentBrdr">
		<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <?php if ($title = $this->getChildData($alias, 'title')):?>
        <?php echo $this->escapeHtml($title); ?>
        <?php endif;?>
        <?php echo $html; ?>
        <?php endforeach;?>
    </p>-->
         </form>
        
        
         
    </div>
<div class="product-view">
    <div>
    <script type="text/javascript">
    //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button){
                if (this.validator.validate()) {
                    this.form.submit();
                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
</div>
<!-- Codes by Quackit.com -->
<script type="text/javascript">
// Popup window code
function newPopup(url) {
	popupWindow = window.open(
		url,'popUpWindow','height=400,width=550,left=10,top=10,resizable=no,scrollbars=yes,toolbar=no,menubar=no,location=no,directories=no,status=no')
}
</script>
<!--Code for vizury code(Dileswar)-->
<?php 
$catIds=$_product->getCategoryIds();
$catId=$catIds[0];

$category=Mage::getModel('catalog/category')->getCategories($catIds[0]);

foreach($category as $cat)
{
    if($cat->getId())
  	{
      $subcatId1=$cat->getId();
	}
	/*if(in_array($cat->getId(), $catIds))
    {
        $subcatId1=$cat->getId();
    }
    else
    { 
        $subcatId1="";
    }*/
    
}
?>
<iframe src="http://www.vizury.com/analyze/analyze.php?account_id=VIZVRM209&param=e300&pid=<?php echo $_product->getId(); ?>&catid=<?php echo $catId ;?>&subcat1id=<?php echo $subcatId1;?>&subcat2id=&section=1&level=1" scrolling="no" width="1" height="1" marginheight="0" marginwidth="0" frameborder="0"></iframe>


  
  
  
  
