<?php $hlp = Mage::helper('generalcheck');
$ismobile = $hlp->ismobile();
if(!$ismobile)
{?>
 <?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" id="checkoutBtn" class="spriteimg proceedCheckBtn <?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
    </button>
<?php endif;
//Desktop 

} else{
 if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" id="checkoutBtn" class="newaddcartbutton12092014 <?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';" style="width:100%;height: 140px;border: 4px solid #d02718;">Proceed To Payment
    </button>
<?php endif; }

?>
