<?php /*custom breadcrumbs*/
$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
 
$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
 
$breadcrumbs->addCrumb('cart', array('label'=>'Account Information', 'title'=>'Account Information'));
 
echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
?>
<div class="dashboard">
	<div class="topLine"></div>
    <div class="dashboard_head">
		<h1><?php echo $this->__('Edit Account Information') ?></h1>
		<div class="breadcrumbs_bottom"></div>
    </div>
        
<?php   $url = Mage::getBaseUrl().'craftsvillacustomer/index/customerpicsave'; 
        $_custImgResize=$this->helper('craftsvillacustomer');
        $_customer=Mage::getSingleton('customer/session')->getCustomer();
        $customerId=$_customer->getId();
        
        if($_customer->getCustomerPhoto()!=''){
            $_imageCustomer = $_customer->getCustomerPhoto();
            $imgurl=Mage::getBaseUrl('media');
            $imageCustomerImg=split($imgurl,$_imageCustomer);//trim($_imageCustomer,$url);
            $_image=$_custImgResize->getResizedUrl($imageCustomerImg[1],75);
        }
        else{
            $_image=$this->getSkinUrl('img/messages/default_avatar_75px.png');
        }
        
?>    
    <div class="uploadimg">
        <form action="<?php echo $url; ?>" method="post" id="custpic" enctype="multipart/form-data">
            <div class="cust-pic">
                <p class="fleft"><img width="40" height="40" alt="" class="img-avatar" src="<?php echo $_image; ?>"></p>
                <div class="fleft">
                <input type="file" name="custphoto" id="cutomer_image" class="required-entry" />
                <input type="hidden" name="custid" id="custid" value="<?php echo $customerId; ?>" />
                <input type="submit" value="Upload" name="cust_pic" class="bluebtnsmall" id="cust_pic" />
                </div>
            </div>
        </form>
    </div>
</div>
<p class="clear"></p>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top: 10px;">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
	<p class="required"><?php echo $this->__('* Required Fields') ?></p>	
        <div class="clear"></div>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <!-- <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box"> -->
                    <input placeholder="Email Address*" type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="editInfoInput fleft" />
                <!-- </div> -->
            </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="stroke"></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="saveInfo"></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
   
    var dataForm = new VarienForm('custpic', true); 
      
      
//]]>
</script>