<?php /*custom breadcrumbs*/
$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
 
$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
 
$breadcrumbs->addCrumb('cart', array('label'=>'Forgot Your Password?', 'title'=>'Forgot Your Password?'));
 
echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
?>
<div class="dashboard">
	<div class="topLine"></div>
    <div class="dashboard_head">
		<h1><?php echo $this->__('Forgot Your Password?') ?></h1>
		<div class="breadcrumbs_bottom"></div>
	</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
        <ul class="form-list">
            <li>
                <!--<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>-->
                <div class="input-box">
                    <input placeholder="Email Address" type="text" name="email" alt="email" id="email_address" class="editInfoInput input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
				<button style="float:left;" type="submit" title="<?php echo $this->__('Submit') ?>" class="spriteimg continueMdm"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
    	<p class="stroke"></p>
        <p class="back-link"><a class="links" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        
    </div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>