<?php /*custom breadcrumbs*/
$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
 
$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Home Page'), 'link'=>Mage::getBaseUrl()));
 
$breadcrumbs->addCrumb('cart', array('label'=>'My Dashboard', 'title'=>'My Dashboard'));
 
echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
?>
<div class="dashboard">
	<div class="topLine"></div>
    <div class="dashboard_head">
		<h1><?php echo $this->__('Newsletter Subscription') ?></h1>
		<div class="breadcrumbs_bottom"></div>
	</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top:10px;">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h2>
        <ul class="form-list">
            <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
        </ul>
    </div>
    <div class="buttons-set">
    	<p class="stroke"></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="saveInfo"></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div>