<div id="block_notice_license" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('License'); ?>">
    <?php
    $email = '<a href="mailto:support@m2epro.com">support@m2epro.com</a>';
    $tempString = Mage::helper('M2ePro')->__('M2E Pro extension requires activation for its work.<br/><br/>
	To get the License Key, click the <u>Get License Key</u> link and follow the instructions.<br/>
	When you got your License Key, press the <u>Enter</u> button
	and enter your License Key in appeared text field. Press the <u>Confirm</u> button.<br/><br/>
	<b>Note:</b> If you have not received the License Key, contact us right away at %email%.');
    echo str_replace('%email%',$email,$tempString);
    ?>
</div>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
	}

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/adminhtml_license/save'); ?>';
    M2ePro.url.checkLicense = '<?php echo $this->getUrl('*/adminhtml_license/checkLicense'); ?>';

    M2ePro.text.license_validation_error = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('You must get valid Trial or Live license key.')); ?>';

    Event.observe(window, 'load', function() {
        LicenseHandlersObj = new LicenseHandlers();
        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_license_status" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Status'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Current Status'); ?>: </label>
                            </td>
                            <td class="value">
                                <?php if ($this->status['mode'] == Ess_M2ePro_Model_License_Model::MODE_NONE) echo Mage::helper('M2ePro')->__('None License'); ?>
                                <?php if ($this->status['mode'] == Ess_M2ePro_Model_License_Model::MODE_TRIAL) echo Mage::helper('M2ePro')->__('Trial License'); ?>
                                <?php if ($this->status['mode'] == Ess_M2ePro_Model_License_Model::MODE_LIVE) echo Mage::helper('M2ePro')->__('Live License'); ?>

                                <?php if ($this->status['mode'] != Ess_M2ePro_Model_License_Model::MODE_NONE &&
                                         ($this->status['status'] == Ess_M2ePro_Model_License_Model::STATUS_SUSPENDED ||
                                          $this->status['status'] == Ess_M2ePro_Model_License_Model::STATUS_CLOSED)) { ?>
                                        <span style="color:red;">(
                                        <?php if ($this->status['status'] == Ess_M2ePro_Model_License_Model::STATUS_SUSPENDED) echo Mage::helper('M2ePro')->__('Suspended'); ?>
                                        <?php if ($this->status['status'] == Ess_M2ePro_Model_License_Model::STATUS_CLOSED) echo Mage::helper('M2ePro')->__('Closed'); ?>
                                        )</span>
                                <?php } ?>
                            </td>
                            <td class="value">
                                <?php echo $this->getChildHtml('refresh_status'); ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('Expiration Date'); ?>: </label>
                            </td>
                            <td class="value">
                                <?php echo $this->status['expired_date']; ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="label">
                                <label><?php echo Mage::helper('M2ePro')->__('License Key'); ?>: </label>
                            </td>
                            <td id="license_text_key_container" class="value">
                                <?php echo $this->status['key']; ?>
                                <?php if ($this->status['key'] == '') { echo $this->getChildHtml('enter_key'); } ?>
                                &nbsp;&nbsp;
                            </td>
                            <td id="license_input_key_container" class="value" style="display: none;">
                                <input id="key" name="key" value="<?php echo $this->escapeHtml($this->status['key']); ?>" type="text" class="input-text required-entry" />
                                &nbsp;&nbsp;
                            </td>
                            <td id="change_license_key_container" class="value" <?php if($this->status['key'] == '') { ?>style="display: none;"<?php } ?>>
                                <?php echo $this->getChildHtml('change_key'); ?>
                            </td>
                            <td id="confirm_license_key_container" class="value" style="display: none;">
                                <?php echo $this->getChildHtml('confirm_key'); ?>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <a href="https://m2epro.com/clients/" target="_blank"><?php echo Mage::helper('M2ePro')->__('Get License Key'); ?></a>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <?php if ($this->valid['domain'] != '' || $this->valid['ip'] != '' || $this->valid['directory'] != '') { ?>

        <div class="entry-edit" id="magento_block_license_valid" collapseable="no">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('License Validation'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <colgroup class="label"></colgroup>
                        <colgroup class="value"></colgroup>

                        <tbody>

                            <?php if ($this->valid['domain'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Domain'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->valid['domain']; ?>
                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->valid['ip'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('IP'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->valid['ip']; ?>
                                    </td>
                                </tr>

                            <?php } ?>

                            <?php if ($this->valid['directory'] != '') { ?>

                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('M2ePro')->__('Directory'); ?>: </label>
                                    </td>
                                    <td class="value">
                                        <?php echo $this->valid['directory']; ?>
                                    </td>
                                </tr>

                            <?php } ?>

                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    <?php } ?>

</form>