<div id="block_notice_logs_cleaning" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Logs Clearing'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set preferences of Auto Logs Clearing for different Logs, 
	which can be found in eBay > Activity Logs.<br/>You should set settings and press <u>Save Setting</u>. Enabled tasks will be automatically
	performed according to your Cron job.<br/><br/>
	It is also possible to launch a certain task manually by pressing the <u>Run Now</u> button in appropriate section or all tasks at once by pressing
	<u>Run Enable Now</u> in the top corner.<br/>
	Log records will be deleted according to the Keep For setting.<br/><br/>
	To clear all log records of the certain Log, press <u>Clear All</u> in appropriate section. To clear all log records of all Logs at once
	click <u>Clear All Logs</u> in the top corner.'); ?>
</div>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
	}

    M2ePro.text.clearing_all_logs_started_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The clearing all logs started. Please wait ...')); ?>';
    M2ePro.text.clearing_log_started_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('The clearing of %log% log started. Please wait ...')); ?>';

    Event.observe(window, 'load', function() {
        LogsCleaningHandlersObj = new LogsCleaningHandlers('<?php echo $this->getUrl('*/adminhtml_logsCleaning/save'); ?>');

        LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>');
        LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>');
        LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>');

        editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
    });
    
</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_logs_cleaning_listings">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Listings Log Clearing'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_mode_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <?php $mode = isset($this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS]) ? $this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS] : 1; ?>
                                <select id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_mode" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_mode" onchange="LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>');">
                                    <option value="0"<?php if (0 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if (1 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Performs automatic log records clearing.'); ?></span>
                                </p>
                              </td>
                            <td>
                                <div id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_button_run_now_container">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('run_now_'.Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS); ?>
                                </div>
                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_days_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_days"><?php echo Mage::helper('M2ePro')->__('Keep For (days)'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_days" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_days" value="<?php echo $this->days[Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS]; ?>" type="text" class="required-entry input-text" />
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Time interval for which log records should be kept.'); ?></span>
                                </p>
                            </td>
                            <td>

                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS; ?>_log_button_clear_all_container">
                            <td class="label">
                               
                            </td>
                            <td class="value">
                                <?php echo $this->getChildHtml('view_log_'.Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('clear_all_'.Ess_M2ePro_Model_LogsCleaning::LOG_LISTINGS); ?>
                            </td>
                            <td>

                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>
        
    </div>

    <div class="entry-edit" id="magento_block_logs_cleaning_ebay_listings">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('3rd Party Listings Log Clearing'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_mode_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <?php $mode = isset($this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS]) ? $this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS] : 1; ?>
                                <select id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_mode" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_mode" onchange="LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>');">
                                    <option value="0"<?php if (0 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if (1 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Performs automatic log records clearing.'); ?></span>
                                </p>
                              </td>
                            <td>
                                <div id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_button_run_now_container">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('run_now_'.Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS); ?>
                                </div>
                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_days_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_days"><?php echo Mage::helper('M2ePro')->__('Keep For (days)'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_days" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_days" value="<?php echo $this->days[Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS]; ?>" type="text" class="required-entry input-text" />
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Time interval for which log records should be kept.'); ?></span>
                                </p>
                            </td>
                            <td>

                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS; ?>_log_button_clear_all_container">
                            <td class="label">

                            </td>
                            <td class="value">
                                <?php echo $this->getChildHtml('view_log_'.Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('clear_all_'.Ess_M2ePro_Model_LogsCleaning::LOG_EBAY_LISTINGS); ?>
                            </td>
                            <td>

                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_logs_cleaning_synch">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Synchronization Log Clearing'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>

                    <tbody>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_mode_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <?php $mode = isset($this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS]) ? $this->modes[Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS] : 1; ?>
                                <select id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_mode" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_mode" onchange="LogsCleaningHandlersObj.changeModeLog('<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>');">
                                    <option value="0"<?php if (0 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if (1 == $mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Performs automatic log records clearing.'); ?></span>
                                </p>
                            </td>
                            <td>
                                <div id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_button_run_now_container">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('run_now_'.Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS); ?>
                                </div>
                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_days_container">
                            <td class="label">
                                <label for="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_days"><?php echo Mage::helper('M2ePro')->__('Keep For (days)'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_days" name="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_days" value="<?php echo $this->days[Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS]; ?>" type="text" class="required-entry input-text" />
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Time interval for which log records should be kept.'); ?></span>
                                </p>
                            </td>
                            <td>

                            </td>
                        </tr>

                        <tr id="<?php echo Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS; ?>_log_button_clear_all_container">
                            <td class="label">

                            </td>
                            <td class="value">
                                <?php echo $this->getChildHtml('view_log_'.Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('clear_all_'.Ess_M2ePro_Model_LogsCleaning::LOG_SYNCHRONIZATIONS); ?>
                            </td>
                            <td>

                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </div>

    </div>

</form>