<div id="block_notice_synchronization" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Synchronization'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This section allows you to set preferences of data synchronization.<br/>
	You should enable / disable synchronization tasks, which will be automatically performed for all eBay accounts, and <u>Save Settings</u>.<br/>
	To run necessary task manually, click the <u>Run Now</u> button, to run all tasks at once, click <u>Run Enabled Now</u>.<br/>
	<br/><b>Note:</b> Cron job must be set up for automatic synchronization. Otherwise, you will have to perform the synchronization manually.'); ?>
</div>

<script type="text/javascript">

    if (typeof M2ePro == 'undefined') {
		M2ePro = {};
		M2ePro.url = {};
		M2ePro.formData = {};
		M2ePro.customData = {};
		M2ePro.text = {};
	}

    M2ePro.url.formSubmit = '<?php echo $this->getUrl('*/*/save'); ?>';
    M2ePro.url.logViewUrl = '<?php echo $this->getUrl('*/adminhtml_logs/synchronizations',array('back'=>Mage::helper('M2ePro')->makeBackUrlParam('*/adminhtml_synchronization/index'))); ?>';

    M2ePro.url.runSynchNow = '<?php echo $this->getUrl('*/adminhtml_marketplaces/runSynchNow'); ?>';

    M2ePro.url.runAllEnabledNow = '<?php echo $this->getUrl('*/adminhtml_synchronization/runAllEnabledNow'); ?>';
    M2ePro.url.runNowTemplates = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowTemplates'); ?>';
    M2ePro.url.runNowOrders = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowOrders'); ?>';
    M2ePro.url.runNowFeedbacks = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowFeedbacks'); ?>';
    M2ePro.url.runNowEbayListings = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowEbayListings'); ?>';
    M2ePro.url.runNowMessages = '<?php echo $this->getUrl('*/adminhtml_synchronization/runNowMessages'); ?>';

    M2ePro.url.synchCheckState = '<?php echo $this->getUrl('*/adminhtml_general/synchCheckState'); ?>';
    M2ePro.url.synchGetLastResult = '<?php echo $this->getUrl('*/adminhtml_general/synchGetLastResult'); ?>';
    M2ePro.url.synchGetExecutingInfo = '<?php echo $this->getUrl('*/adminhtml_general/synchGetExecutingInfo'); ?>';

    M2ePro.text.synch_settings_saved_successfully = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization settings have been saved.')); ?>';
    M2ePro.text.synch_running_all_enabled_tasks = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Running All Enabled Tasks')); ?>';
    M2ePro.text.synch_running_templates = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Templates Synchronization')); ?>';
    M2ePro.text.synch_running_orders = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Orders Synchronization')); ?>';
    M2ePro.text.synch_running_feedbacks = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Feedbacks Synchronization')); ?>';
    M2ePro.text.synch_running_3rd_party = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('3rd Party Listings Synchronization')); ?>';
    M2ePro.text.synch_running_messages = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Messages Synchronization')); ?>';

    M2ePro.text.synch_already_running_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Another Synchronization Is Already Running')); ?>';
    M2ePro.text.synch_getting_information_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Getting information. Please wait ...')); ?>';
    M2ePro.text.synch_prepare_to_start_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Preparing to start. Please wait ...')); ?>';

    M2ePro.text.synch_end_success_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization has successfully ended.')); ?>';
    M2ePro.text.synch_end_warning_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with warnings. <a href="%url%">View log</a> for details.')); ?>';
    M2ePro.text.synch_end_error_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__('Synchronization ended with errors. <a href="%url%">View log</a> for details.')); ?>';

    Event.observe(window, 'load', function() {
        setTimeout(function() {
            SynchronizationProgressHandlersObj = new SynchProgressHandlers(SynchProgressBarObj, SynchWrapperObj );
            SynchronizationHandlersObj = new SynchronizationHandlers(SynchronizationProgressHandlersObj);
            SynchronizationProgressHandlersObj.initPageCheckState();

            editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl(); ?>');
        }, 350);
    });

</script>

<form id="<?php echo $this->getForm()->getId(); ?>" action="<?php echo $this->getForm()->getData('action'); ?>" method="post" enctype="multipart/form-data">

    <input name="form_key" value="<?php echo $this->getFormKey(); ?>" type="hidden" />

    <div class="entry-edit" id="magento_block_synchronization_templates">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Templates Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="templates_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $templates_mode = isset($this->templates['mode']) ? $this->templates['mode'] : 0; ?>
                            <select id="templates_mode" name="templates_mode" onchange="SynchronizationHandlersObj.changeTemplatesMode();">
                                <option value="0"<?php if (0 == $templates_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $templates_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Updates and synchronizes eBay Listings according to<br/>Synchronization Templates' rules."); ?></span>
                            </p>
                        </td>

                        <td>
                            <div id="templates_run_now_container" <?php if ($templates_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('templates_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>

                    </tr>

                    <tr id="inspector_mode_container" <?php if(0 == $templates_mode) { echo 'style="display:none;"';} ?>>
                        <td class="label">
                            <label for="inspector_mode"><?php echo Mage::helper('M2ePro')->__('Track Direct Database<br/>Changes'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" colspan="2">
                            <?php $inspector_mode = isset($this->templates['inspector']) ? $this->templates['inspector'] : 0; ?>
                            <select id="inspector_mode" name="inspector_mode">
                                <option value="0"<?php if (0 == $inspector_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $inspector_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Should be enabled if changes in catalog is being made directly to database.<br/>It is performed once per an hour.<br/><b>Note: </b>It is strongly recommended to enable this option if you really need it,<br/>as it is very resource and time consuming and may have affect on<br/>synchronization performance."); ?></span>
                            </p>
                        </td>
                    </tr>

                    <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <?php echo $this->getChildHtml('templates_view_log'); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('templates_clear_log'); ?>
                            </td>
                            <td></td>
                        </tr>
                    <?php } ?>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_synchronization_orders">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Orders Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="orders_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $orders_mode = isset($this->orders['mode']) ? $this->orders['mode'] : 0; ?>
                            <select id="orders_mode" name="orders_mode" onchange="SynchronizationHandlersObj.changeOrdersMode();">
                                <option value="0"<?php if (0 == $orders_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $orders_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes eBay Orders for accounts,<br/>which have enabled Import eBay Orders in their<br/>Accounts settings.'); ?></span>
                            </p>
                        </td>
                        <td>
                            <div id="orders_run_now_container" <?php if ($orders_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('orders_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <?php echo $this->getChildHtml('orders_view_log'); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('orders_clear_log'); ?>
                            </td>
                            <td></td>
                        </tr>
                    <?php } ?>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_synchronization_feedbacks">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Feedbacks Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="feedbacks_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $feedbacks_mode = isset($this->feedbacks['mode'])? $this->feedbacks['mode'] : 0; ?>
                            <select id="feedbacks_mode" name="feedbacks_mode" onchange="SynchronizationHandlersObj.changeFeedbacksMode();">
                                <option value="0"<?php if (0 == $feedbacks_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $feedbacks_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__("Imports buyers' feedbacks and automatically sends<br/>Auto Responses according to eBay Accounts settings."); ?></span>
                            </p>
                        </td>
                        <td>
                            <div id="feedbacks_run_now_container" <?php if ($feedbacks_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('feedbacks_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <?php echo $this->getChildHtml('feedbacks_view_log'); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('feedbacks_clear_log'); ?>
                            </td>
                            <td></td>
                        </tr>
                    <?php } ?>

                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_synchronization_ebay_listings">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('3rd Party Listings Synchronization'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr>
                        <td class="label">
                            <label for="ebay_listings_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value">
                            <?php $ebay_listings_mode = isset($this->ebay_listings['mode'])? $this->ebay_listings['mode'] : 0; ?>
                            <select id="ebay_listings_mode" name="ebay_listings_mode" onchange="SynchronizationHandlersObj.changeEbayListingsMode();">
                                <option value="0"<?php if (0 == $ebay_listings_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                <option value="1"<?php if (1 == $ebay_listings_mode) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                            </select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Imports and synchronizes 3rd Party Listings for eBay<br/>accounts, which have enabled Import 3rd Party Listings<br/>in their Accounts settings.'); ?></span>
                            </p>
                        </td>
                        <td>
                            <div id="ebay_listings_run_now_container" <?php if ($ebay_listings_mode != 1) echo ' style="display: none;"'; ?>>
                                <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('ebay_listings_run_now'); ?>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>

                    <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <?php echo $this->getChildHtml('ebay_listings_view_log'); ?>
                                &nbsp;&nbsp;
                                <?php echo $this->getChildHtml('ebay_listings_clear_log'); ?>
                            </td>
                            <td></td>
                        </tr>
                    <?php } ?>
                    
                </table>

            </div>
        </div>

    </div>

    <?php if ((bool)(int)Mage::helper('M2ePro/Module')->getConfig()->getGroupValue('/messages/', 'mode')): ?>
            
        <div class="entry-edit" id="magento_block_synchronization_messages">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('My Messages Synchronization'); ?></h4>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table class="form-list" cellspacing="0" cellpadding="0">

                        <tr>
                            <td class="label">
                                <label for="messages_mode"><?php echo Mage::helper('M2ePro')->__('Enabled'); ?>: <span class="required">*</span></label>
                            </td>
                            <td class="value">
                                <?php $messages_mode = isset($this->messages['mode'])? $this->messages['mode'] : 0; ?>
                                <select id="messages_mode" name="messages_mode" onchange="SynchronizationHandlersObj.changeMessagesMode();">
                                    <option value="0"<?php if ($messages_mode == 0) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('No'); ?></option>
                                    <option value="1"<?php if ($messages_mode == 1) echo ' selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('Yes'); ?></option>
                                </select>
                                <p class="note">
                                    <span><?php echo Mage::helper('M2ePro')->__('Imports buyers\' messages according to<br />eBay Accounts settings.'); ?></span>
                                </p>
                            </td>
                            <td>
                                <div id="messages_run_now_container" <?php if ($messages_mode != 1) echo ' style="display: none;"'; ?>>
                                    <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <?php echo $this->getChildHtml('messages_run_now'); ?>
                                    <?php } ?>
                                </div>
                            </td>
                        </tr>

                        <?php if (!(Mage::getModel('M2ePro/Wizard')->isActive() && Mage::getModel('M2ePro/Wizard')->getStatus() == Ess_M2ePro_Model_Wizard::STATUS_SYNCHRONIZATION)) { ?>
                            <tr>
                                <td class="label"></td>
                                <td class="value">
                                    <?php echo $this->getChildHtml('messages_view_log'); ?>
                                    &nbsp;&nbsp;
                                    <?php echo $this->getChildHtml('messages_clear_log'); ?>
                                </td>
                                <td></td>
                            </tr>
                        <?php } ?>
                        
                    </table>

                </div>
            </div>

        </div>

    <?php endif; ?>

</form>