<div id="block_notice_eBay_orders_list" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('eBay Orders'); ?>">
    <?php echo Mage::helper('M2ePro')->__('This page contains all orders imported from eBay.
    Use eBay Accounts dropdown to filter eBay orders by accounts.<br/>
    If Magento Order, Invoice or / and Shipment was not created automatically,
    you can create them manually by using appropriate options in the Action dropdown.<br/><br/>
    <b>Note:</b> Automatic creation of Magento Orders, Invoices, and Shipments happens according to the eBay Accounts
    settings in eBay > Configuration > eBay Accounts > Orders.'); ?>
</div>