<script type="text/javascript">window.open();</script>
<?php
   $orderIds = $this->order_ids;
   $order = Mage::getModel('sales/order')->load($orderIds); //load order             
	//	echo '<pre>';print_r($order);exit;
		$entityIdSus = $order->getEntityId();
		$incrementId = $order->getIncrementId();
		$custemail = $order->getCustomerEmail();
		$totalQtyOrder = $order->getTotalQtyOrdered();
		$shipment = Mage::getModel('sales/order_shipment')->getCollection()->addFieldToFilter('order_id', $entityIdSus)->load();
	    
		//$custaddress = Mage::getModel('sales/order_address')->getCollection()->addFieldToFilter('email', $custemail)->load();
		
		$custaddress = $order->getShippingAddress();
		
		
		//foreach($custaddress as $_custaddress)
		//{
		  $custfirstname = $custaddress['firstname'];
		  $custlastname = $custaddress['lastname'];
		  $custstreet = $custaddress['street'];
		  $custcity = $custaddress['city'];
		  $custregion = $custaddress['region'];
		  $custpostcode = $custaddress['postcode'];
		  $custcountryid = $custaddress['country_id'];
		  $countryName = Mage::getModel("directory/country")->load($custcountryid)->getName();
		  $custtelephone = $custaddress['telephone']; 
		//}
if($orderIds)
{
?>
 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
		<body>
	<form id ="print" target="_blank" action="" method="post""><font size="6">
       <strong>Order #: <?php echo $incrementId;?></strong><br>
       <strong>Shipment #: <?php 
       $i = 1;
       foreach($shipment as $_shipment)
		{
		 if($i==1)
		  $shipincrementid = $_shipment['increment_id'];
		 else
		  $shipincrementid = substr($_shipment['increment_id'],-2);
		 $i++;
		 ?><?php echo $shipincrementid.'/';?></strong><?php }?><br>
       <strong>Total Qty Ordered: <?php echo round($totalQtyOrder); ?></strong></br></br>
       
       <strong>To,</strong><br>
       <strong><?php echo $custfirstname.' '.$custlastname;?></strong><br>
       <strong><?php echo $custstreet;?></strong><br>
       <strong><?php echo $custcity;?></strong><br>
       <strong><?php echo $custregion.' '.$custpostcode;?></strong><br>
       <strong><?php echo $countryName;?></strong><br>
       <strong>T: +<?php echo $custtelephone;?></strong><br></font>
       <br><br><br><br>       
       <font size="6">
       <strong>From,</strong><br>
       <strong>Craftsvilla.com,</strong><br>
       <strong>21, Centrium Mall,</strong><br>
       <strong>First Floor, Lokhandwala Complex,</strong><br>
       <strong>Kandivali(East)</strong><br>
       <strong>Mumbai, 400101,</strong><br>
       <strong>T:+91-9892676399</strong><br>
       </font>
       </form>
</body>
</html>

<script type="text/javascript">window.print();</script>
<?php }?>
