<?php
$hlp = Mage::helper('generalcheck');
$ismobile = $hlp->ismobile();

if(!$ismobile)
{?> 
<?php 
/*if(Mage::registry('current_category')) {
echo $categoryName=Mage::registry('current_category')->getName();
//for vizury
$catId=Mage::registry('current_category')->getId();
$category=Mage::getModel('catalog/category')->getCollection($catId) ;//getCategories($catId);
foreach($category as $cat)
	{
	$subcatId1=$cat->getId();
	}
*/

//if($categoryName == 'Jewelry' || $categoryName == 'Jewellery'){
?>

<?php //}
	//if($categoryName == 'Bags'){
	?>
		<!-- Google Code for Bags Re-Market List Remarketing List -->
		<!--<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "dF9TCNm9wgMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
		<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=dF9TCNm9wgMQ996vzgM&amp;guid=ON&amp;script=0"/>
		</div>
		</noscript> -->
    
	<?php
	/*}
    elseif($categoryName == 'Necklaces')
	{*/
	?>
		<!-- Google Code for Necklaces Remarketing List -->
		<!--<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "nDF-CPmCxwMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=nDF-CPmCxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
        /*}
        elseif($categoryName == 'Anklets')
        {*/
		?>
		<!-- Google Code for Anklets Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "4_FsCPGDxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=4_FsCPGDxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
       /* }
        elseif($categoryName == 'Rings')
        {*/
		?>
        <!-- Google Code for Rings Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "W5FnCOmExwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=W5FnCOmExwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
        <?php
       /* }
        elseif($categoryName == 'Earrings')
        {*/
		?>
        <!-- Google Code for Earrings Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "EncvCNmGxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=EncvCNmGxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
        /*}
        elseif($categoryName == 'Bracelets & Bangles')
        {*/
		?>
        <!-- Google Code for Bracelets Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "2RlqCNGHxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=2RlqCNGHxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
       <!--Below Div for showing Offer box on all category and vendor page-->
        <?php
		//$lifetime = 86400;
		//$CacheIdOffer = "categorycache-offer"; 
		  //if ($cacheContentOffer = Mage::app()->loadCache($CacheIdOffer))
		  	//{ 
               //echo $cacheContentOffer;
            //}
          //else 
			//{ 
				$_offerHtml ='<div class= "offertext">'.$this->getLayout()->createBlock('cms/block')->setBlockId('offer_text')->toHtml().'</div>';
			//}
			$cacheContentOffer = $_offerHtml;
    		//Mage::app()->saveCache($cacheContentOffer,$CacheIdOffer, $tags,$lifetime);
			echo $cacheContentOffer; 
			?>
	<?php
	//}
//}

    $_productCollection=$this->getLoadedProductCollection();
	//echo '<pre>';print_r($_productCollection);exit;
	$_helper = $this->helper('catalog/output');
	$_currencyCodeProduct = Mage::app()->getStore()->getCurrentCurrencyCode();
	//$lifetime = 86400;//57600;//28800;	
	$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
	$pinImage = $this->getSkinUrl('img/PinExt.png');

    //echo $this->getChildHtml('featured-prod');
 
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">

     <?php echo $this->getToolbarHtml() ?>
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
    <?php $vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>        
    <?php // Product Image ?>
    <?php 
    	if(!$categoryName)
    	{
    		$category_arr = $_product->getCategoryIds();
	    	if($category_arr[0] != 2)
		    {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
		    } 
		    else {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[1]);
		    }
		    $categoryName = $_category->getName();
    	}
    ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><!-- <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> -->
            	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)."-".$categoryName."Bow Bow-".$vendorinfo->getData('shop_name'); ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
					<div class="col-1">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						 <?php //$vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>
               <?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               		 $storeurl = substr($storeurl, 0, -1);
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>

					<div class="col-2">
						<div class="desc std">
							<?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
					
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    
    <?php $_collectionSize = $_productCollection->count(); ?>
    <?php $_columnCount = 4;//$this->getColumnCount(); //4 ?>
	<?php /* Set columnCount here because of possible Magento bug by doejo*/ ?>
    <?php $i=0; $j=25; ?>
    <?php /*?>descripp-------------------	<?php */?>
 
 
 
<?php    
//		$cat = Mage::getModel('catalog/category')->load(4);
//		echo $description = $cat->getDescription();
//		
// ?>
    <?php foreach ($_productCollection as $_product): ?>
	
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
        
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <?php 
					$productIdCache=$_product->getId();
					//$CacheIdProduct = "categorycache-$productIdCache-currency-$_currencyCodeProduct-$isLoggedIn"; 
					
					?>

           <?php //if ($cacheContentProduct = Mage::app()->loadCache($CacheIdProduct)){ 
                //echo $cacheContentProduct;
            //}
            //else { ?>
            
				<?php
					$_pageHtml = '';
					 
					  
				     
                    $vendorinfo = Mage::helper('udropship')->getVendor($_product);
                    $storeurl = '';				
                    $storeurl = Mage::helper('umicrosite')->getVendorUrl($vendorinfo->getVendorId());
                    $storeurl = substr($storeurl, 0, -1);
                    $productURL =  $_product->getProductUrl();
					$productImageTag =  $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
					$shipptime = $_product->getShippingtime();
					
            	    if($vendorinfo['vendoradmin_payment_methods'][0]=='cashondelivery'){
					$codimage = '';
					} 
					else{
					//$codimage = '<img border="1" src="'.$this->getSkinUrl('images/Cod-3.jpg').'"/>';
					$codimage = '<div class="codimage3" style="float:right">COD<img align="texttop" border="0" src="'.$this->getSkinUrl('images/tickforcod.png').'"/></div>';
					}
					
					$_discImage ='';
					$specialPrice = $_product->getSpecialPrice();
					if(!empty($specialPrice))
						{
							$actualprice = $_product->getPrice();
							$perPrice = ((($actualprice-$specialPrice)/$actualprice)*100);
							if($perPrice >= 5){
							$_discImage ='<p class="codimage3" style="height:14px;width:55px;float:left;text-align:center;">'.round($perPrice).'% Off</p>';
							}
						} 
					
					$_pageHtml .='<div class="prCnr">'.$_discImage.$codimage; ?> <!-- Product html start -->
                
                    <?php $_pageHtml .='<a href="'.$productURL.'" title="'.$productImageTag.'" class="product-image spriteimg">'; 
					
					?>
                    <?php 
                        if(!$categoryName)
                        {
                            $category_arr = $_product->getCategoryIds();
                            if($category_arr[0] != 2)
                            {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
                            } 
                            else {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[1]);
                            }
                            $categoryName = $_category->getName();
                        }
                    ?>
                
            
                   <?php
				   $helperimage = $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,166);
				   $productImagelabel = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
				   $vendorinfoname = $vendorinfo->getVendorName();
				   $vendorname = substr($vendorinfoname,0,12);
				   $lazyLoder = $this->getSkinUrl('images/lazy_image_loader/loader.gif');
				   //$helperimage = $this->helper('catalog/image')->init($_product, 'small_image')->resize(500, 500);
				   $productName = $this->htmlEscape($_product->getName()) ;
				   $productStrip = $this->stripTags($_product->getName(), null, true);
				   $productAttribute = $_helper->productAttribute($_product, $_product->getName(), 'name');
				   if($storeurl) $vendorURL = $storeurl; else $vendorURL = '#';
				   $_pageHtml .= '<img class="lazy" long-desc="'.$helperimage.'"width="166px" height="166" alt="'.$productImagelabel.'"-"'.$categoryName.'"-"'.$vendorinfoname.'" src="'.$lazyLoder.'"/> </a>';
               		
					?>              		
			   
                <!-- AddThis Button BEGIN -->
                  <?php
                  $_pageHtml .= '<ul id="socielicon">' ?>
                      <?php //if($isLoggedIn): ?>
                      <?php //echo "<pre>"; print_r($_product->getData()); ?>
                      <?php
                  $_pageHtml .= '<li class="wishit"><input type="button" value="" title="Add to Wishlist" id="imgwish'.$j.'" class="wishit_buttons" onclick="wishitval('.$productIdCache.',this.id)" /> </li>' ?>
                      <?php //else: ?>      
                       <?php     //$_pageHtml .= '<li class="wishit"> <a href="#wishthis" class="fancybox"><input type="button" value="" title="Add to Wishlist" class="wishit_buttons" /></a></li>' ?>
                      <?php //endif; ?>
                      <?php  $_pageHtml .= '<li> <a href="http://pinterest.com/pin/create/button/?url='.$productURL.'&media='.$helperimage.'&description='.$productName.'"class="pin-it-button" count-layout="none" target="_blank"><img border="0" src="'.$pinImage.'"/></a></li></ul>'?>  
 						           
 					<!-- AddThis Button END --> 
					<?php	               
                    $_pageHtml .='<p class="shopbrief"><a href="'.$productURL.'" title="'.$productStrip.'">'.$productAttribute.'</a></p>'?>
                    <?php if($storeurl){ ?>               
                    <?php 
						if($shipptime>0.5 && $shipptime<10)
					{
						$_pageHtml .='<p class="vendorname">by <a href="'.$vendorURL.'" target="_blank">'.$vendorname.'..</a>';
				       $_pageHtml .= '<span title="The Average Domesting Shipping">('.round($shipptime).' Day)</span></p>';
					}
					else
					{
						$_pageHtml .= '<p class="vendorname">by <a href="'.$vendorURL.'" target="_blank">'.$vendorinfoname.'</a></p>';
					} ?>
                    <?php } ?> 
                  
                    
                    <!-- magento original price -->
                    <?php $_pageHtml .= $this->getPriceHtml($_product, true);?>
                    <!-- magento original price -->
                   <?php $_pageHtml .='<div class="clear"></div>'; ?>
					
                    
                    
            <!--//***----Commented By Dileswar--To below line block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		
					<?php 
						//if($_product->getStockItem()->getIsInStock() == 0){
                    ?>
                     <?php //  $_pageHtml .='<p class="sold_icon spriteimg"></p>'; ?>
                    <?php //} ?>
             <!--//***----Commented By Dileswar--To above block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		       
               
			   <?php $_pageHtml .='</div>'; ?> 
				<?php $_pageHtml .='<div unbxdattr="product" unbxdparam_sku="'.$_product->getSku().'"  unbxdparam_prank="1" ></div>';?>
				<?php $_pageHtml .='<img src="https://sp.analytics.yahoo.com/spp.pl?a=10001487429785&.yp=35012&js=no"/>';?>
        
               <!-- Product html end -->
                
               <?php  $cacheContentProduct = $_pageHtml;
    			$tags = array(
                    //Mage_Catalog_Model_Product::CACHE_TAG,
                    //Mage_Catalog_Model_Product::CACHE_TAG . '_' . $productIdCache
                );
				//$CacheIdProduct = "productcache-$productIdCache-currency-$_currencyCodeProduct";
				//Mage::app()->saveCache($cacheContentProduct, $CacheIdProduct, $tags, $lifetime);
				echo $cacheContentProduct; ?>
    
              <?php //} ?>
            </li>
            
        <?php  if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        
        <?php  endif; ?>
        
        <?php $j++; endforeach; ?>
        
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
    <?php  endif; ?>
</div>
<?php endif; ?>


<div id="wishthis">
  <div id="welcome_img" class="popuphead"><span class="popuoheading">Add to Wishlist</span></div>
  <div id="bg_welcome" class="shortpop">
    <ul class="followshop">
      <li>
        <h2 class="greyheading">Allready Member</h2>
        <a href="#login" class="spriteimg bluesmallbtn fancybox">Login</a></li>
      <li class="nobor">
        <h2 class="greyheading">New Customer </h2>
        <a class="spriteimg bluesmallbtn fancybox" href="#signUpForm">Sign Up</a></li>
    </ul>
    <p class="clr"></p>
    <p align="center" class="clr margintoptwenty"><span class="required">Note:</span> To Wish this product You need to login or register.</p>
  </div>
</div>



<!--------tag fof kiqpush------->
<!--<script type="text/javascript">var _kiq = _kiq || [];</script>
<script type="text/javascript" src="//s3.amazonaws.com/ki.js/27455/5rh.js" async="true"></script>

<?php
       /* Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->getRequest()->getRequestUri());  //save requested URL for later redirection
        if (Mage::getSingleton('customer/session')->isLoggedIn()) {
            $email_unique1 = Mage::getSingleton('customer/session')->getCustomer()->getEmail();*/
            ?>
<script type="text/javascript" charset="utf-8">
_kiq.push(['identify', '<?php //echo $email_unique1; ?>']);
</script>-->
<?php //} ?>

<!--Added by Gayatri to display the category description on footer-->

<div class="category_desc_bot">
<?php 
      $vendor = Mage::helper('umicrosite')->getCurrentVendor();
        if(Mage::registry('current_category')) 
		{
			$catId=Mage::registry('current_category')->getId();
			$cat = Mage::getModel('catalog/category')->load($catId);
				
			if($cat->getId())
			{
			      echo substr($cat->getDescription(),0,800).'<br><br>';
				 /* Added by Gayatri on dated 10-08-2013 to display seocontent randomly on category page*/
				  $seocontentcoll = Mage::getModel('seocontent/seocontent')->getCollection()
				  		->addFieldToFilter('category',$catId)->getData();
						//->addFieldToFilter('seocontent_id',9)->getData();
				 $seocount=sizeof($seocontentcoll);
				  $secindex = rand(-1,($seocount-1));
				echo $seocontentcoll[$secindex]['content'];
				
		        	 
		}
		
				
		}
		elseif($vendor->getId())
		{
			echo substr($vendor->getShopDescription(),0,800);
		}
		?>
       
	</div>

 <script type="text/javascript">
 	
            function wishitval(val,ival) {
				var loggedin = false;
				var u ='<?php echo Mage::getBaseUrl().'wishlist/publicshare/iscustomerlogged' ?>';
				new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
					
                                        if(transport.responseText == 'login'){
										
                                            loggedin = true;
											
											}
											
											if (loggedin){
				
											jQuery('#'+ival).addClass('wishit_hide');
											var u = "<?php echo Mage::getBaseUrl().'wishlist/index/add/product/';?>"+val;
											   new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
																if(transport.responseText == 'wished')
																	var locate = "<?php echo $_SERVER['HTTP_REFERER']; ?>";
																window.location(locate);	
                                								}
                        					});	
                
					
											} else {
				
												jQuery.fancybox({width:'430px', height:'22px',href:"#wishthis"});
											}
				
								}	
                               
                        });	
				 }
				

</script>     

<?php

///DEKSTOP VIEW ENDS
 }else {?>
<!----------------------------------------------------------------------------------------------------------------------------------->
<?php 

    $_productCollection=$this->getLoadedProductCollection();
	//echo '<pre>';print_r($_productCollection);exit;
	$_helper = $this->helper('catalog/output');
	$_currencyCodeProduct = Mage::app()->getStore()->getCurrentCurrencyCode();
	//$lifetime = 86400;//57600;//28800;	
	$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
	$pinImage = $this->getSkinUrl('img/PinExt.png');

    //echo $this->getChildHtml('featured-prod');
 
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">

     <?php echo $this->getToolbarHtml() ?>
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>"  >
    <?php $vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>        
    <?php // Product Image ?>
    <?php 
    	if(!$categoryName)
    	{
    		$category_arr = $_product->getCategoryIds();
	    	if($category_arr[0] != 2)
		    {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
		    } 
		    else {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[1]);
		    }
		    $categoryName = $_category->getName();
    	}
    ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><!-- <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> -->
            	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(500); ?>" width="100%" height="auto" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)."-".$categoryName."Bow Bow-".$vendorinfo->getData('shop_name'); ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
					<div class="col-1">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						 <?php //$vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>
               <?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               		 $storeurl = substr($storeurl, 0, -1);
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>

					<div class="col-2">
						<div class="desc std">
							<?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
					
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    
    <?php $_collectionSize = $_productCollection->count(); ?>
    <?php $_columnCount = 4;//$this->getColumnCount(); //4 ?>
	<?php /* Set columnCount here because of possible Magento bug by doejo*/ ?>
    <?php $i=0; $j=25; ?>
    <?php /*?>descripp-------------------	<?php */?>
 
 
 
<?php    
//		$cat = Mage::getModel('catalog/category')->load(4);
//		echo $description = $cat->getDescription();
//		
// ?>
    <?php foreach ($_productCollection as $_product): ?>
	
        <?php if ($i++%$_columnCount==0): ?>

        <ul class="products-grid first odd you_like">
        <?php endif ?>
        
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="width:48%; ">
<div>
            <?php 
					$productIdCache=$_product->getId();
					//$CacheIdProduct = "categorycache-$productIdCache-currency-$_currencyCodeProduct-$isLoggedIn"; 
					
					?>

           <?php //if ($cacheContentProduct = Mage::app()->loadCache($CacheIdProduct)){ 
                //echo $cacheContentProduct;
            //}
            //else { ?>
            
				<?php
					$_pageHtml = '';
					 
					  
				     
                    $vendorinfo = Mage::helper('udropship')->getVendor($_product);
                    $storeurl = '';				
                    $storeurl = Mage::helper('umicrosite')->getVendorUrl($vendorinfo->getVendorId());
                    $storeurl = substr($storeurl, 0, -1);
                    $productURL =  $_product->getProductUrl();
					$productImageTag =  $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
					$shipptime = $_product->getShippingtime();
					
            	    if($vendorinfo['vendoradmin_payment_methods'][0]=='cashondelivery'){
					$codimage = '';
					} 
					else{
					
					$codimage = '<img border="0" src="'.$this->getSkinUrl("mobileimg/mobile_cod.png").'"/>';
					//	$codimage = '<div class="codimage3" style="float:right">COD<img align="texttop"  border="0" src="'.$this->getSkinUrl('images/tickforcod.png').'"/></div>';
					}
					
					$_discImage ='';
					$specialPrice = $_product->getSpecialPrice();
					if(!empty($specialPrice))
						{
							$actualprice = $_product->getPrice();
							$perPrice = ((($actualprice-$specialPrice)/$actualprice)*100);
							if($perPrice >= 5){
							//$_discImage ='<p class="codimage3" style="height:14px;width:20%;float:left;text-align:center;">'.round($perPrice).'% Off</p>';
							}
						} 
					
					$_pageHtml .='<div class="prCnr" >'.$_discImage.$codimage; ?> <!-- Product html start -->
                
                    <?php $_pageHtml .='<a href="'.$productURL.'" title="'.$productImageTag.'" >'; 
					
					?>
                    <?php 
                        if(!$categoryName)
                        {
                            $category_arr = $_product->getCategoryIds();
                            if($category_arr[0] != 2)
                            {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
                            } 
                            else {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[1]);
                            }
                            $categoryName = $_category->getName();
                        }
                    ?>
                
            
                   <?php
				   $helperimage = $this->helper('catalog/image')->init($_product, 'image')->resize(500,500);
				   $productImagelabel = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
				   $vendorinfoname = $vendorinfo->getVendorName();
				   $vendorname = substr($vendorinfoname,0,12);
				   $lazyLoder = $this->getSkinUrl('images/lazy_image_loader/loader.gif');
				   //$helperimage = $this->helper('catalog/image')->init($_product, 'small_image')->resize(500, 500);
				   $productName = $this->htmlEscape($_product->getName()) ;
				   $productStrip = $this->stripTags($_product->getName(), null, true);
				   $productAttribute = $_helper->productAttribute($_product, $_product->getName(), 'name');
				   if($storeurl) $vendorURL = $storeurl; else $vendorURL = '#';
				  // $_pageHtml .= '<img class="lazy" long-desc="'.$helperimage.'"width="100%" height="auto" alt="'.$productImagelabel.'"-"'.$categoryName.'"-"'.$vendorinfoname.'" src="'.$lazyLoder.'"/> </a>';
               		 $_pageHtml .= '<img width="100%" height="auto"  alt="'.$productImagelabel.'"-"'.$categoryName.'"-"'.$vendorinfoname.'" src="'.$helperimage.'"/> </a>';
					?>              		
			   
                <!-- AddThis Button BEGIN -->
                   						           
 					<!-- AddThis Button END --> 
					<?php	               
                    $_pageHtml .='<p class="shopbrief" style="padding-top: 25px;padding-bottom:15px;"><a href="'.$productURL.'"  style="font-size:30px;line-height: 26px;" title="'.$productStrip.'">'.substr($productAttribute,0,25).'..</a></p>'?>
                    <?php if($storeurl){ ?>               
                    <?php 
						if($shipptime>0.5 && $shipptime<10)
					{
						$_pageHtml .='<p class="vendorname" style="padding-bottom:30px;font-size:30px;">by <font size="+3"><a href="'.$vendorURL.'" target="_blank">'.substr($vendorname,0,25).'..</a></font>';
				       $_pageHtml .= '<span title="The Average Domesting Shipping">('.round($shipptime).' Day)</span></p>';
					}
					else
					{
						$_pageHtml .= '<p class="vendorname"  style="padding-bottom:30px;font-size:30px;" >by <a href="'.$vendorURL.'" target="_blank"><font size="+3">'.substr($vendorinfoname,0,25).'..</a></font></p>';
					} ?>
                    <?php } ?> 
                  
                    
                    <!-- magento original price -->
                    <?php $_pageHtml .= $this->getPriceHtml($_product, true);?>
                    <!-- magento original price -->
                   <?php $_pageHtml .='<div class="clear"></div>'; ?>
					
                    
                    
            <!--//***----Commented By Dileswar--To below line block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		
					<?php 
						//if($_product->getStockItem()->getIsInStock() == 0){
                    ?>
                     <?php //  $_pageHtml .='<p class="sold_icon spriteimg"></p>'; ?>
                    <?php //} ?>
             <!--//***----Commented By Dileswar--To above block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		       
               
			   <?php $_pageHtml .='</div>'; ?> 
        
               <!-- Product html end -->
                
               <?php  $cacheContentProduct = $_pageHtml;
    			$tags = array(
                    //Mage_Catalog_Model_Product::CACHE_TAG,
                    //Mage_Catalog_Model_Product::CACHE_TAG . '_' . $productIdCache
                );
				//$CacheIdProduct = "productcache-$productIdCache-currency-$_currencyCodeProduct";
				//Mage::app()->saveCache($cacheContentProduct, $CacheIdProduct, $tags, $lifetime);
				echo $cacheContentProduct; ?>
    
              <?php //} ?>
            </li>
            
        <?php  if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        
        <?php  endif; ?>
        
        <?php $j++; endforeach; ?>
        
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
    <?php  endif; ?>


</div>
</div>
<?php endif; ?>




<!--------tag fof kiqpush------->
<!--<script type="text/javascript">var _kiq = _kiq || [];</script>
<script type="text/javascript" src="//s3.amazonaws.com/ki.js/27455/5rh.js" async="true"></script>

<?php
       /* Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->getRequest()->getRequestUri());  //save requested URL for later redirection
        if (Mage::getSingleton('customer/session')->isLoggedIn()) {
            $email_unique1 = Mage::getSingleton('customer/session')->getCustomer()->getEmail();*/
            ?>
<script type="text/javascript" charset="utf-8">
_kiq.push(['identify', '<?php //echo $email_unique1; ?>']);
</script>-->
<?php //} ?>

<!--Added by Gayatri to display the category description on footer-->

<!--below content rmove shru
<div class="category_desc_bot" style="font-size:28px;">
<?php 
      $vendor = Mage::helper('umicrosite')->getCurrentVendor();
        if(Mage::registry('current_category')) 
		{
			$catId=Mage::registry('current_category')->getId();
			$cat = Mage::getModel('catalog/category')->load($catId);
				
			if($cat->getId())
			{
			      echo substr($cat->getDescription(),0,800).'<br><br>';
				 /* Added by Gayatri on dated 10-08-2013 to display seocontent randomly on category page*/
				  $seocontentcoll = Mage::getModel('seocontent/seocontent')->getCollection()
				  		->addFieldToFilter('category',$catId)->getData();
						//->addFieldToFilter('seocontent_id',9)->getData();
				 $seocount=sizeof($seocontentcoll);
				  $secindex = rand(-1,($seocount-1));
				echo $seocontentcoll[$secindex]['content'];
				
		        	 
		}
		
				
		}
		elseif($vendor->getId())
		{
			echo substr($vendor->getShopDescription(),0,800);
		}
		?>
       
	</div>-->
<?php
$symbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
$Range1 = 500;
$Range2 = 1000;
$Range3 = 2000;
$Range4 = 5000;
if ($baseCurrencyCode != $currentCurrencyCode) {
        // convert price from current currency to base currency
        $Range1 = round((Mage::helper('directory')->currencyConvert(500, $baseCurrencyCode, $currentCurrencyCode)*1.5),0);
		$Range2 = round((Mage::helper('directory')->currencyConvert(1000, $baseCurrencyCode, $currentCurrencyCode)*1.5),0);
		$Range3 = round((Mage::helper('directory')->currencyConvert(2000, $baseCurrencyCode, $currentCurrencyCode)*1.5),0);
		$Range4 = round((Mage::helper('directory')->currencyConvert(5000, $baseCurrencyCode, $currentCurrencyCode)*1.5),0);

        // convert price from base currency to current currency
        //$priceTwo = Mage::helper('directory')->currencyConvert($amount, $baseCurrencyCode, $currentCurrencyCode);
    }
	
?>

<div id="test2" style="width:98%; position:fixed;background:#E3D7C8;bottom: 120px;  top: 6%; display:none;overflow:scroll; z-index: 75;" >
<div text-align="justify" style="margin-left:5%;" >
       <div class="nearpr" style="margin-left:20px;margin-top:2%;"><input type="button" name="submit" onClick="rewriteUrloffiltersCod2135()" value="<?php echo $this->__('Show Only COD Products') ?>" style="width:98%;height:auto;background-color: #39708E;font-size: 63px;line-height: 67px;color:#ffffff; cursor:pointer; " title="<?php echo $this->__('Show Only COD Products') ?>"/></div>

<div style="cursor:pointer;padding:1%;" onclick="removefiltersCod()" title="Remove COD Filter"  align="center" > <font size="+3"><strong>Clear COD Filter</strong></font></div>
<br>


   
<div	style="font-size:30px;padding:1%;">
<strong><?php echo $this->__('Sort By') ?></strong><br><br>
<div style="cursor:pointer;padding:1%;"  onclick="submitAsc()"><font color="#0192B5" size="+3"><?php echo $this->__('Price Low To High') ?></font></div>
<div style="cursor:pointer;padding:1%;"  onclick="submitDesc()"><font color="#0192B5" size="+3"><?php echo $this->__('Price High To Low') ?></font></div>
<div style="cursor:pointer;padding:1%;"  onclick="submitDisAsc()"><font color="#0192B5" size="+3"><?php echo $this->__('Discount Low To High') ?></font></div>
<div style="cursor:pointer;padding:1%;"  onclick="submitDisDesc()"><font color="#0192B5" size="+3"><?php echo $this->__('Discount High To Low') ?></font></div>
</div>


 <div style="">
         <dl id="narrow-by-list">
            <dt style="font-size:30px;padding:1%;"><?php echo $this->__('Filter By Price') ?></dt>
            <dd style="margin-left:3px; ">

<form><div onclick="submitprice()" style="cursor:pointer;padding:1%; "><font color="#0192B5" size="+4"><?php echo $symbol;?><?php echo   '0'; ?>  - <?php echo $symbol;?><?php echo $Range1;?></font></div></form>
       <form><div onclick="submitprice1()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+4"><?php echo $symbol;?><?php echo $Range1; ?>  - <?php echo $symbol;?><?php echo $Range2;?></font></div></form>
       <form><div onclick="submitprice2()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+4"><?php echo $symbol;?><?php echo $Range2; ?>  - <?php echo $symbol;?><?php echo $Range3;?></font></div></form>
      <form><div onclick="submitprice3()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+4"><?php echo $symbol;?><?php echo $Range3; ?>  - <?php echo $symbol;?><?php echo $Range4;?></font></div></form>
    <form> <div onclick="submitprice4()" style="cursor:pointer;padding:1%;"> <input type="text" id="min_value4" name="min_value" onfocus="this.blur()" class="subreadonly" readonly="readonly" value="" style="font-size:40px; color:#0192B5;border: none;background: transparent;outline:none;cursor:pointer"><input type="text" id="max_value4" name="max_value" onfocus="this.blur()" class="subreadonly" value="Above <?php echo $symbol.''.$Range4;?>" align="center" readonly="readonly" style="font-size:40px; color:#0192B5;border: none;background: transparent;float:left;
    outline:none;cursor:pointer" /></div></form>
    
      
     <div style="color: #0192B5; font-size: 40px;">         
      Rs.<input type="text" name='min_value' placeholder='' id='min_value5' style='width:13%!important;height:74px;color:#000;font-size:50px;' /><font color="#0192B5" > - </font>             
             
      <!--<div style="color: #0192B5; size: 2px; margin-left:5px; margin-top:-15px">         
      To: &nbsp;&nbsp;&nbsp;&nbsp;-->
       
      
      Rs.<input type="text" name='max_value' placeholder='' id='max_value5' style='width:13%!important;height:74px;color:#000;font-size:50px;' />
             
         
        
        <input type="button" name="submit" onClick="submitprice5()" value="Price Search" style='width:50%;height:auto;background-color:#39708E;font-size:60px;line-height:67px;color:#ffffff;cursor:pointer;border:4px solid #51839f; ' />
  </div>

          </dd>
<div style="cursor:pointer;" align="center" onclick="removeUrloffiltersPrice()"  title ="<?php echo $this->__('Remove Price Filter')?>" ><font size="+3"><strong>Clear Price Filter</strong></font></div>
             
        </dl>   </div>
       <br/>
<dl id="narrow-by-list">
 <dt style="font-size:30px;"><?php echo $this->__('Filter By Discount') ?></dt>
<dd style="margin-left:5px">
                    
       
		<form><div onclick="submitdiscount50()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+3">Discount Above 50%</font></div></form>
		<form><div onclick="submitdiscount40()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+3">Discount Above 40%</font></div></form>
		<form><div onclick="submitdiscount30()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+3">Discount Above 30%</font></div></form>
		<form><div onclick="submitdiscount20()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+3">Discount Above 20%</font></div></form>
		<form><div onclick="submitdiscount10()" style="cursor:pointer;padding:1%;"><font color="#0192B5" size="+3">Discount Above 10%</font></div></form>
  
</dd></dl>
<div style="cursor:pointer;"  align="center"  onclick="removefiltersDiscount()"  title ="<?php echo $this->__('Remove Discount Filter')?>" ><font size="+3"><strong>Clear Discount Filter</strong></font></div>

<br/>
<br/>
<div style=" ">
<dl id="narrow-by-list">
 <dt style="font-size:30px;"><?php echo $this->__('Filter By Color') ?></dt>
<dd style="margin-left:5px">
<div onclick="submitcolorred()" style ="float:left; width:12%;height:100px;margin:7px;background:red;cursor:pointer;" title ="Red" ></div>
<div onclick="submitcolorgreen()" style ="float:left;width:12%;height:100px;margin:7px;background:green;cursor:pointer;"title = "Green"></div>
<div onclick="submitcolorwhite()" style ="float:left; width:12%;height:100px;margin:7px;background:white;cursor:pointer;border-color:grey;border: 1px;border-style:groove;"  title ="White" ></div>
<div onclick="submitcolorblack()" style ="float:left;  width:12%;height:100px;margin:7px;background:black;cursor:pointer;" title ="Black" ></div>
<div onclick="submitcoloryellow()" style ="float:left; width:12%;height:100px;background:yellow;cursor:pointer;margin:7px;" title ="Yellow" ></div>
<div onclick="submitcolormagenta()"style="float:left; width:12%;height:100px;background:magenta;cursor:pointer;margin:7px;"title ="Magenta" ></div>
<div onclick="submitcolorpurple()"style="float:left; width:12%;height:100px;background:purple;cursor:pointer;margin:8px;"title ="Purple" ></div>
<div onclick="submitcolorgrey()"style="float:left; width:12%;height:100px;background:grey;cursor:pointer;margin:7px;"title ="Grey" ></div>
<div onclick="submitcolorblue()"style="float:left; width:12%;height:100px;background:blue;cursor:pointer;margin:7px;"title ="Blue" ></div>
<div onclick="submitcolorbrown()"style="float:left;width:12%;height:100px;background:brown;cursor:pointer;margin:7px;"title ="Brown" ></div>
<div onclick="submitcolorsilver()"style="float:left; width:12%;height:100px;background:silver;cursor:pointer;margin:7px;"title ="Silver" ></div>
<div onclick="submitcolorbeige()"style="float:left; width:12%;height:100px;background:beige;cursor:pointer;margin:7px;"title ="Beige" ></div>
<div onclick="submitcolorgold()"style="float:left; width:12%;height:100px;background:gold;cursor:pointer;margin:7px;"title ="Gold" ></div>
<div onclick="submitcolormulticolor()"style="float:left; width:12%;height:100px;background:multicolor;cursor:pointer;margin:7px;"title ="Multicolor" ></div>
</dd></dl>
<br/>
<div style="cursor:pointer;  margin: 7%;" onclick="removefiltersColor()"  align="center"  title ="<?php echo $this->__('Remove Color Filter')?>" ><font size="+3"><strong>Clear Color Filter</strong></font></div>
</div>
</div>
</div>		<!--end filterdiv-->



 <button type="button" title="<?php echo $this->__('Filter') ?>"  id="filterbtn" onclick="filterproductby()" style="width:98%;position:fixed;bottom:10px;background-color: #f24537;border: 4px solid #d02718;height:100px;font-size: 65px;line-height: 67px;  color: #ffffff;cursor: pointer;"><span><span><?php echo $this->__('Filter') ?></span></span></button>

</div>
<script>
// function to detect when scroollbar reaches the bottom of page
var whenScrlBottom = function() {
  // http://coursesweb.net/javascript/
  var win_h = (self.innerHeight) ? self.innerHeight : document.body.clientHeight;    // gets window height

  // gets current vertical scrollbar position
  var scrl_pos = window.pageYOffset ? window.pageYOffset : document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop;

  // if scrollbar reaces to bottom
  if (document.body.scrollHeight <= (scrl_pos + win_h)) {
document.getElementById("filterbtn").style.display='none';   
// alert('Bottom');
  }else{

document.getElementById("filterbtn").style.display='block'; 
}
}

// register event on scrollbar
window.onscroll = whenScrlBottom;
</script>
<script>
function submitAsc(){
var pathname = window.location.pathname;
window.location.href = pathname+"?dir=asc&order=price";
}
function submitDesc(){
var pathname = window.location.pathname;
window.location.href = pathname+"?dir=desc&order=price";
}
function submitDisAsc(){
var pathname = window.location.pathname;
window.location.href = pathname+"?dir=asc&order=discount";
}
function submitDisDesc(){
var pathname = window.location.pathname;
window.location.href = pathname+"?dir=desc&order=discount";
}
</script>


			<script>
				function filterproductby(){

					var disShow = document.getElementById('test2').style.display;
						if(disShow == "none")
						{
							document.getElementById('test2').style.display = "";	 
						}
						else
						{
							document.getElementById('test2').style.display = "none";
						}	 
				}
			</script>


 <script type="text/javascript">
 	
            function wishitval(val,ival) {
				var loggedin = false;
				var u ='<?php echo Mage::getBaseUrl().'wishlist/publicshare/iscustomerlogged' ?>';
				new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
					
                                        if(transport.responseText == 'login'){
										
                                            loggedin = true;
											
											}
											
		if (loggedin){

		jQuery('#'+ival).addClass('wishit_hide');
		var u = "<?php echo Mage::getBaseUrl().'wishlist/index/add/product/';?>"+val;
		new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
		if(transport.responseText == 'wished')
		var locate = "<?php echo $_SERVER['HTTP_REFERER']; ?>";
		window.location(locate);	
		}
		});	


		} else {

		jQuery.fancybox({width:'430px', height:'22px',href:"#wishthis"});
		}

		}	

		});	
		}


</script>     
<style>

#filterbtn{font-size:40px;width:400px;}
#filterbtn{width:400px;height:68px;background:#E3D7C8;border: 2px solid;border-radius: 15px;cursor: pointer;}
	
	#test2{top:0px;z-index:100;}
</style>
<?php } ?>
