<?php  
if(Mage::registry('current_category')) {
$categoryName=Mage::registry('current_category')->getName();
if($categoryName == 'Jewelry' || $categoryName == 'Jewellery'):?>

<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName('script')[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0012/1676.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

<?php endif;
}
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>



<!-- AddThis Button BEGIN 
<div class="addthis_toolbox addthis_default_style floatr" style="left:150px;padding-bottom: 15px;position: absolute;top:40px; *top:28px; top /*\**/: 38px\9">
 <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
 <a class="addthis_button_tweet"></a>
 <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
 <a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f34adfd2fa3a766"></script>-->
<!-- AddThis Button END -->

    
<div class="clear"></div>

<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
					<div class="col-1">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						 <?php $vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>
               <?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>
					
					<div class="col-2">
						<div class="desc std">
							<?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
					
                </div>
            </div>
        </li>
    <?php endforeach; ?>

    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $vendorinfo = Mage::helper('udropship')->getVendor($_product);?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <div class="prCnr">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<!--<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(205,205); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />-->
					<img class="lazy" long-desc="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200,200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" src="<?php echo $this->getSkinUrl('images/lazy_image_loader/loader.gif'); ?>"/>

				</a>
                <h1><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h1>
                <?php $storeurl = Mage::helper('umicrosite')->getVendorUrl($vendorinfo->getVendorId());?>
                <p class="vendorname">By: <a href="<?php echo $storeurl; ?>" target="_blank"><?php echo $vendorinfo->getVendorName();?></a></p>
                
                <div class="vendorname">
				  <?php if ($_product->getShortDescription()):?>
				  <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
				  <?php endif;?>
				</div>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <!-- magento original price -->
                <?php echo $this->getPriceHtml($_product, true);?>
                <!-- magento original price -->
                
                <!-- customize price-->
                <!--<?php //if ($_product->getSpecialPrice()==0):?>
				<h3 id="home"><?php //echo Mage::helper('core')->currency($_product->price, true, false); ?></h3>
               <?php// else: ?>
                <h3 id="home"><?php //echo Mage::helper('core')->currency($_product->SpecialPrice, true, false); ?></h3>
                <h5><?php //echo Mage::helper('core')->currency($_product->price, true, false); ?></h5>
               <?php //endif; ?>-->
                <!-- customize price-->
               <div class="clear"></div>
               
               
		         <?php /*?><div class="shrtDscrption">
                 		<?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
					  <?php if ($_product->getShortDescription()):?>
                      <?php //echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                      <?php endif;?>
                 </div><?php */?>
                 
                 
                 
                <!--<div class="wrapper border1">
                <div class="indent">
                <?php if($_product->isSaleable()): ?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart fright" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                
                <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                </div>-->
                </div>
               <!-- <iframe src="http://www.facebook.com/plugins/like.php?layout=button_count&href=<?php// echo $_product->getProductUrl() ?>"  scrolling="no" frameborder="0" allowTransparency="true" class="fblikebtn" title="Like it!"></iframe> <img src="<?php //echo $this->getSkinUrl('images/fblike.gif')?>" class="fbthumbic" alt="" title="Like it!"  />-->
            </li>
            
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div>
<?php endif; ?>
<?php 


?>
