<?php 
/*if(Mage::registry('current_category')) {
echo $categoryName=Mage::registry('current_category')->getName();
//for vizury
$catId=Mage::registry('current_category')->getId();
$category=Mage::getModel('catalog/category')->getCollection($catId) ;//getCategories($catId);
foreach($category as $cat)
	{
	$subcatId1=$cat->getId();
	}
*/

//if($categoryName == 'Jewelry' || $categoryName == 'Jewellery'){
?>

<?php //}
	//if($categoryName == 'Bags'){
	?>
		<!-- Google Code for Bags Re-Market List Remarketing List -->
		<!--<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "dF9TCNm9wgMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
		<div style="display:inline;">
		<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=dF9TCNm9wgMQ996vzgM&amp;guid=ON&amp;script=0"/>
		</div>
		</noscript> -->
    
	<?php
	/*}
    elseif($categoryName == 'Necklaces')
	{*/
	?>
		<!-- Google Code for Necklaces Remarketing List -->
		<!--<script type="text/javascript">
		/* <![CDATA[ */
		var google_conversion_id = 969666423;
		var google_conversion_language = "en";
		var google_conversion_format = "3";
		var google_conversion_color = "ffffff";
		var google_conversion_label = "nDF-CPmCxwMQ996vzgM";
		var google_conversion_value = 0;
		/* ]]> */
		</script>
		<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
		</script>
		<noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=nDF-CPmCxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
        /*}
        elseif($categoryName == 'Anklets')
        {*/
		?>
		<!-- Google Code for Anklets Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "4_FsCPGDxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=4_FsCPGDxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
       /* }
        elseif($categoryName == 'Rings')
        {*/
		?>
        <!-- Google Code for Rings Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "W5FnCOmExwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=W5FnCOmExwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
        <?php
       /* }
        elseif($categoryName == 'Earrings')
        {*/
		?>
        <!-- Google Code for Earrings Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "EncvCNmGxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=EncvCNmGxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
		<?php
        /*}
        elseif($categoryName == 'Bracelets & Bangles')
        {*/
		?>
        <!-- Google Code for Bracelets Remarketing List -->
        <!--<script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 969666423;
        var google_conversion_language = "en";
        var google_conversion_format = "3";
        var google_conversion_color = "ffffff";
        var google_conversion_label = "2RlqCNGHxwMQ996vzgM";
        var google_conversion_value = 0;
        /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/969666423/?label=2RlqCNGHxwMQ996vzgM&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>-->
        
	<?php
	//}
//}
    $_productCollection=$this->getLoadedProductCollection();
	//echo '<pre>';print_r($_productCollection);exit;
	$_helper = $this->helper('catalog/output');
	$_currencyCodeProduct = Mage::app()->getStore()->getCurrentCurrencyCode();
	$lifetime = 86400;//57600;//28800;	
	$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
	$pinImage = $this->getSkinUrl('img/PinExt.png');

    //echo $this->getChildHtml('featured-prod');
 
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">

	<div class="topLine"></div>
    <?php echo $this->getToolbarHtml() ?>
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
    <?php $vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>        
    <?php // Product Image ?>
    <?php 
    	if(!$categoryName)
    	{
    		$category_arr = $_product->getCategoryIds();
	    	if($category_arr[0] != 2)
		    {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
		    } 
		    else {
		    	$_category = Mage::getModel('catalog/category')->load($category_arr[1]);
		    }
		    $categoryName = $_category->getName();
    	}
    ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><!-- <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> -->
            	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)."-".$categoryName."Bow Bow-".$vendorinfo->getData('shop_name'); ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
					<div class="col-1">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						 <?php //$vendorinfo = Mage::helper('udropship')->getVendor($_product); ?>
               <?php $storeurl= Mage::helper('umicrosite')->getVendorUrl($_product->getUdropshipVendor());
               		 $storeurl = substr($storeurl, 0, -1);
               echo "<a href='$storeurl' title=".$vendorinfo->getData('vendor_name')."> By:- ".$vendorinfo->getData('shop_name');//."theme202/template/catalog/product/list.phtml</a>"
               ?>
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>

					<div class="col-2">
						<div class="desc std">
							<?php //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
					
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    
    <?php $_collectionSize = $_productCollection->count(); ?>
    <?php $_columnCount = 4;//$this->getColumnCount(); //4 ?>
	<?php /* Set columnCount here because of possible Magento bug by doejo*/ ?>
    <?php $i=0; $j=25; ?>
    <?php /*?>descripp-------------------	<?php */?>
 
 
 
<?php    
//		$cat = Mage::getModel('catalog/category')->load(4);
//		echo $description = $cat->getDescription();
//		
// ?>
    <?php foreach ($_productCollection as $_product): ?>
	
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
        
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <?php 
					$productIdCache=$_product->getId();
					$CacheIdProduct = "categorycache-$productIdCache-currency-$_currencyCodeProduct-$isLoggedIn"; 
					
					?>

           <?php if ($cacheContentProduct = Mage::app()->loadCache($CacheIdProduct)){ 
                echo $cacheContentProduct;
            }
            else { ?>
            
				<?php 
				    $_pageHtml = ''; 
                    $vendorinfo = Mage::helper('udropship')->getVendor($_product);
                    $storeurl = '';				
                    $storeurl = Mage::helper('umicrosite')->getVendorUrl($vendorinfo->getVendorId());
                    $storeurl = substr($storeurl, 0, -1);
                    $productURL =  $_product->getProductUrl();
					$productImageTag =  $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
            	    $_pageHtml .='<div class="prCnr">'; ?> <!-- Product html start -->
            
                    
                    <?php $_pageHtml .='<a href="'.$productURL.'" title="'.$productImageTag.'" class="product-image spriteimg">'; 
					
					?>
                    <?php 
                        if(!$categoryName)
                        {
                            $category_arr = $_product->getCategoryIds();
                            if($category_arr[0] != 2)
                            {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[0]);	
                            } 
                            else {
                                $_category = Mage::getModel('catalog/category')->load($category_arr[1]);
                            }
                            $categoryName = $_category->getName();
                        }
                    ?>
                
            
                   <?php
				   $productCatalog = $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,166);
				   $productImagelabel = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true);
				   $vendorinfoname = $vendorinfo->getVendorName();
				   $lazyLoder = $this->getSkinUrl('images/lazy_image_loader/loader.gif');
				   $helperimage = $this->helper('catalog/image')->init($_product, 'small_image')->resize(500, 500);
				   $productName = $this->htmlEscape($_product->getName()) ;
				   $productStrip = $this->stripTags($_product->getName(), null, true);
				   $productAttribute = $_helper->productAttribute($_product, $_product->getName(), 'name');
				   if($storeurl) $vendorURL = $storeurl; else $vendorURL = '#';
				   $_pageHtml .= '<img class="lazy" long-desc="'.$productCatalog.'"width="166" height="166" alt="'.$productImagelabel.'"-"'.$categoryName.'"-"'.$vendorinfoname.'" src="'.$lazyLoder.'"/> </a>';
               		
					?>              		
			   
                <!-- AddThis Button BEGIN -->
                  <?php
                  $_pageHtml .= '<ul id="socielicon">' ?>
                      <?php //if($isLoggedIn): ?>
                      <?php //echo "<pre>"; print_r($_product->getData()); ?>
                      <?php
                  $_pageHtml .= '<li class="wishit"><input type="button" value="" title="Add to Wishlist" id="imgwish'.$j.'" class="wishit_buttons" onclick="wishitval('.$productIdCache.',this.id)" /> </li>' ?>
                      <?php //else: ?>      
                       <?php     //$_pageHtml .= '<li class="wishit"> <a href="#wishthis" class="fancybox"><input type="button" value="" title="Add to Wishlist" class="wishit_buttons" /></a></li>' ?>
                      <?php //endif; ?>
                      <?php  $_pageHtml .= '<li> <a href="http://pinterest.com/pin/create/button/?url='.$productURL.'&media='.$helperimage.'&description='.$productName.'"class="pin-it-button" count-layout="none" target="_blank"><img border="0" src="'.$pinImage.'"/></a></li></ul>'?>  
 						           
 					<!-- AddThis Button END --> 
					<?php	               
                    $_pageHtml .='<p class="shopbrief"><a href="'.$productURL.'" title="'.$productStrip.'">'.$productAttribute.'</a></p>'?>
                    <?php if($storeurl) { ?>               
                    <?php $_pageHtml .='<p class="vendorname">by <a href="'.$vendorURL.'" target="_blank">'.$vendorinfoname.'</a></p>' ?>
                    <?php } ?> 
                    
                    
                    <!-- magento original price -->
                    <?php $_pageHtml .= $this->getPriceHtml($_product, true);?>
                    <!-- magento original price -->
                   <?php $_pageHtml .='<div class="clear"></div>'; ?>
			
            <!--//***----Commented By Dileswar--To below line block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		
					<?php 
						//if($_product->getStockItem()->getIsInStock() == 0){
                    ?>
                     <?php //  $_pageHtml .='<p class="sold_icon spriteimg"></p>'; ?>
                    <?php //} ?>
             <!--//***----Commented By Dileswar--To above block the `Sold Out` Banner on List page On Dated 22-03-2013........---***//-->		       
               
			   <?php $_pageHtml .='</div>'; ?> 
              <?php //$_pageHtml .='<iframe src="http://www.vizury.com/analyze/analyze.php?account_id=VIZVRM209&param=e200&catid='.$catId.'&subcat1id='.$subcatId1.'&subcat2id=&section=1&level=1" scrolling="no" width="1" height="1" marginheight="0" marginwidth="0" frameborder="0"></iframe>' ;?>
               <!-- Product html end -->
                
               <?php  $cacheContentProduct = $_pageHtml;
    			$tags = array(
                    //Mage_Catalog_Model_Product::CACHE_TAG,
                    //Mage_Catalog_Model_Product::CACHE_TAG . '_' . $productIdCache
                );
				//$CacheIdProduct = "productcache-$productIdCache-currency-$_currencyCodeProduct";
				Mage::app()->saveCache($cacheContentProduct, $CacheIdProduct, $tags, $lifetime);
				echo $cacheContentProduct; ?>
    
              <?php } ?>
            </li>
            
        <?php  if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        
        <?php  endif; ?>
        
        <?php $j++; endforeach; ?>
        
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
    <?php  endif; ?>
</div>
<?php endif; ?>


<div id="wishthis">
  <div id="welcome_img" class="popuphead"><span class="popuoheading">Add to Wishlist</span></div>
  <div id="bg_welcome" class="shortpop">
    <ul class="followshop">
      <li>
        <h2 class="greyheading">Allready Member</h2>
        <a href="#login" class="spriteimg bluesmallbtn fancybox">Login</a></li>
      <li class="nobor">
        <h2 class="greyheading">New Customer </h2>
        <a class="spriteimg bluesmallbtn fancybox" href="#signUpForm">Sign Up</a></li>
    </ul>
    <p class="clr"></p>
    <p align="center" class="clr margintoptwenty"><span class="required">Note:</span> To Wish this product You need to login or register.</p>
  </div>
</div>



<!--------tag fof kiqpush------->
<!--<script type="text/javascript">var _kiq = _kiq || [];</script>
<script type="text/javascript" src="//s3.amazonaws.com/ki.js/27455/5rh.js" async="true"></script>

<?php
       /* Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->getRequest()->getRequestUri());  //save requested URL for later redirection
        if (Mage::getSingleton('customer/session')->isLoggedIn()) {
            $email_unique1 = Mage::getSingleton('customer/session')->getCustomer()->getEmail();*/
            ?>
<script type="text/javascript" charset="utf-8">
_kiq.push(['identify', '<?php //echo $email_unique1; ?>']);
</script>-->
<?php //} ?>

<!--Added by Gayatri to display the category description on footer-->

<div class="category_desc_bot">
<?php 
      $vendor = Mage::helper('umicrosite')->getCurrentVendor();
        if(Mage::registry('current_category')) 
		{
			$catId=Mage::registry('current_category')->getId();
			$cat = Mage::getModel('catalog/category')->load($catId);
				
			if($cat->getId())
			{
			      echo $cat->getDescription();
				 
			}
				
		}
		elseif($vendor->getId())
		{
			echo $vendor->getShopDescription();
		}
		
		
		?>
	</div>

<!---------Vizury Code--------->



 <script type="text/javascript">
 	
            function wishitval(val,ival) {
				var loggedin = false;
				var u ='<?php echo Mage::getBaseUrl().'wishlist/publicshare/iscustomerlogged' ?>';
				new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
					
                                        if(transport.responseText == 'login'){
										
                                            loggedin = true;
											
											}
											
											if (loggedin){
				
											jQuery('#'+ival).addClass('wishit_hide');
											var u = "<?php echo Mage::getBaseUrl().'wishlist/index/add/product/';?>"+val;
											   new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
																if(transport.responseText == 'wished')
																	var locate = "<?php echo $_SERVER['HTTP_REFERER']; ?>";
																window.location(locate);	
                                								}
                        					});	
                
					
											} else {
				
												jQuery.fancybox({width:'430px', height:'22px',href:"#wishthis"});
											}
				
								}	
                               
                        });	
				 }
				

</script>     
