<div id="contactseller">
  <div id="welcome_img" class="popuphead"><span class="popuoheading">Contact This Seller</span></div>
  <div id="bg_welcome" class="shortpop">
    <ul class="followshop">
      <li>
        <h2 class="greyheading">Already Member</h2>
        <a href="#login" class="spriteimg bluesmallbtn fancybox">Login</a></li>
      <li class="nobor">
        <h2 class="greyheading">New Customer </h2>
        <a class="spriteimg bluesmallbtn fancybox" href="#signUpForm">Sign Up</a></li>
    </ul>
    <p class="clr"></p>
    <p align="center" class="clr margintoptwenty"><span class="required">Note:</span> To Contact this Seller You need to login or register.</p>
  </div>
</div>
<div id="wishthis">
  <div id="welcome_img" class="popuphead"><span class="popuoheading">Add to Wishlist</span></div>
  <div id="bg_welcome" class="shortpop">
    <ul class="followshop">
      <li>
        <h2 class="greyheading">Already Member</h2>
        <a href="#login" class="spriteimg bluesmallbtn fancybox">Login</a></li>
      <li class="nobor">
        <h2 class="greyheading">New Customer </h2>
        <a class="spriteimg bluesmallbtn fancybox" href="#signUpForm">Sign Up</a></li>
    </ul>
    <p class="clr"></p>
    <p align="center" class="clr margintoptwenty"><span class="required">Note:</span>To Wish this product You need to login or register.</p>
  </div>
</div>

<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript" ></script>
<?php //$_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct();
?>
<?php $my_tier_rocks = $this->getTierPrices($_product);?>

<?php
$_productInventoryData = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getData();
$_currencyCodeProduct = Mage::app()->getStore()->getCurrentCurrencyCode();
$productIdCache=$_product->getId();
$CacheIdProduct = "productcache-$productIdCache-currency-$_currencyCodeProduct";
$lifetime = 864000;//28800
$_helpv = $this->helper('udropship');
$vendorIfo = $_helpv->getVendor($_product);
$cats = $_product->getCategoryIds();
$catid2 = array();
foreach ($cats as $category_id){
	
    $_cat = Mage::getModel('catalog/category')->load($category_id) ;
    $catid2[] = $_cat->getName();
}
$catTitle = $catid2[1];

$skuProduct = $_product->getSku();
$qty = $_product->getQty();
$productshortdescext = 'Online Shopping for ';
$shopdesc = $vendorIfo->getData('shop_description');//getShopDescription()
$productnameext = ' - Online Shopping for '.$catTitle.' by '.$vendorIfo->getData('vendor_name');
//$newProducTitle = $_product->getName().$productnameext;

if($_product->getTypeId() == 'configurable'){
$newProducTitle = $_product->getName().$productnameext;

}else{

$newProducTitle = $_product->getProductName().$productnameext;

}

/******** Code added by Mandar for vendor product Stats on 4-05-2012 ********/
       //  Mage::getModel('udropship/vendor_stats')->setStats($vendorIfo->getData('vendor_id'),'product');
         /****************************************************************************/
/*Below lines Commented by dileswar for not using any where
---------------------------------------------------*/
/*if(Mage::registry('current_category')) { 
			$catId = Mage::registry('current_category')->getId();
			$catIds=$_product->getCategoryIds();
			$catId=$catIds[0];
			}*/
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml(); ?></div>
<?php
        $_pageHtml = '';
        $_helper = $this->helper('catalog/output');
        $storeId = (int) $this->getStoreId();
$_pageHtml .=
'<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice('.$this->getJsonConfig().')
</script>';

$_pageHtml .= '<div class="detailCotainer">';
if($_product->getOptions()):
    $multiData='enctype="multipart/form-data"';
else:
    $multiData='';
endif;
$_pageHtml .='<form action="'.$this->getAddToCartUrl($_product).'" method="post" id="product_addtocart_form"'.$multiData.'>';

$_pageHtml .='<div class="details">
      <p class="heading_css">'.$_helper->productAttribute($_product, $newProducTitle, 'name').'</p>
      <div class="breadcrumbs_bottom"></div>
      <p class="sort_description">';
      if ($_product->getShortDescription()):
           $_pageHtml .= $_helper->productAttribute($_product, nl2br($productshortdescext.$_product->getShortDescription().' CV-SKU :'.$skuProduct), 'short_description');
      endif;
$_pageHtml .='</p>
      <ul class="shipcost">';
      $_shipcost = array();
      if ($_product->getTypeId() == "configurable") {
      $associated_products = $_product->getTypeInstance()->getUsedProducts();
     
	      $i=0;
	      
	      /*Start
	       * Craftsvilla Comment
	       * added international shipping cost by Suresh on 27-06-2012
	       */
	      $j=0;
	      /*End
	       * Craftsvilla Comment
	       * added international shipping cost by Suresh on 27-06-2012
	       */
		  
	  $stockConfig=array();    
          foreach ($associated_products as $assoc)
            {
				 $assocProduct =Mage::getModel('catalog/product')->load($assoc->getId());
				
                $__shipcost = $assocProduct->getData('shippingcost');
                
               $stockConfig .=$assocProduct->isSaleable();
				
                /*Start
	       		* Craftsvilla Comment
	       		* added international shipping cost by Suresh on 27-06-2012
	       		*/
                $__intershipcost = $assocProduct->getData('intershippingcost');
                /*End
	       		* Craftsvilla Comment
	       		* added international shipping cost by Suresh on 27-06-2012
	       		*/
                
                if (empty($__shipcost))
                $_shipcosta[$i]= 0;
                else
                $_shipcosta[$i]= $__shipcost;
                $i++;
				
				/*Start
	       		* Craftsvilla Comment
	       		* added international shipping cost by Suresh on 27-06-2012
	       		*/
                if (empty($__intershipcost))
                $__intershipcosta[$j]= 0;
                else
                $__intershipcosta[$j]= $__intershipcost;
                $j++;
                /*End
	       		* Craftsvilla Comment
	       		* added international shipping cost by Suresh on 27-06-2012
	       		*/
            }
            
            $_shippingcost = max($_shipcosta);
            /*Start
	       * Craftsvilla Comment
	       * added international shipping cost by Suresh on 27-06-2012
	       */
            $_intershippingcost = max($__intershipcosta);
            /*End
	       * Craftsvilla Comment
	       * added international shipping cost by Suresh on 27-06-2012
	       */
        } else 
        {
            $_shippingcost = $_product->getData('shippingcost');
            /*Start
	       	* Craftsvilla Comment
	       	* added international shipping cost by Suresh on 27-06-2012
	       	*/
            $_intershippingcost = $_product->getData('intershippingcost');  
            /*End
	       	* Craftsvilla Comment
	       	* added international shipping cost by Suresh on 27-06-2012
	       	*/   
        }  
        
        $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
		$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
		if($_shippingcost>0)
		{
			$_shippingcost = Mage::helper('directory')->currencyConvert($_shippingcost, $baseCurrencyCode, $currentCurrencyCode);
		}
		
        if($_intershippingcost>0)
		{
			$_intershippingcost = Mage::helper('directory')->currencyConvert($_intershippingcost, $baseCurrencyCode, $currentCurrencyCode);
		}
		
		if(empty($_shippingcost) || $_shippingcost=='0')
                {
                    $_pageHtml .='<li>Shipping Cost in India : <span>FREE</span></li>';
                }    
                else
                {
                    $_currSym=Mage::app()->getLocale()->currency($currentCurrencyCode)->getSymbol();
                    $_numformatShippingCost=number_format($_shippingcost,2);
                    $_pageHtml .='<li>Shipping Cost in India ('.$_currSym.'): <span>'.$_numformatShippingCost.'</span></li>';
                }
        /*Start
	    * Craftsvilla Comment
	    * added international shipping cost by Suresh on 27-06-2012
	    */
        if(!empty($_intershippingcost) && $_intershippingcost!='0'){		
        //echo "<li>International Shipping : <span>FREE</span></li>";
        //else
            $_currSym=Mage::app()->getLocale()->currency($currentCurrencyCode)->getSymbol();
            $_numforInterShippingCost=number_format($_intershippingcost,2);
            $_pageHtml .='<li>Shipping Cost Outside of India ('.$_currSym.'): <span>'.$_numforInterShippingCost.'</span></li>';
        }
		/*End
	    * Craftsvilla Comment
	    * added international shipping cost by Suresh on 27-06-2012
	    */
        
        ?>
        <?php
         
         $_helpm = $this->helper('umicrosite');
		 
         /******** Code added by Mandar for vendor product level Stats on 4-05-2012 ********/
        // Mage::getModel('udropship/vendor_productstats')->setProductStats($vendorIfo->getData('vendor_id'),$_product->getId());
         /****************************************************************************/
        $storeurl = $_helpm->getVendorUrl($vendorIfo->getData('vendor_id'));
        if(substr($storeurl, -1) == '/')
        {
        	$storeurl = substr($storeurl, 0, -1);
        }
        $_pageHtml .= '<li>See similar products from this Seller: ';
        if($storeurl):
            $storeurl=$storeurl;
        else:
            $storeurl='#';
        endif;
        $_pageHtml .=
            '<span><a href="'.$storeurl.'" target="_blank">.'.$vendorIfo->getData('vendor_name').'</a></span>
        </li>';
        if($_product->getInternationalShipping()==1)
            $_pageHtml .='<li>This Product is available for International Shipping.</li>';
	else
            $_pageHtml .='<li>This Product is not available for shipping outside India.</li>';
		
    /*Start Of COD : Commented On 17-04-2013 for static*/	        
			/*$_prouctForbiddenPaymentMethods = '';
            $_prouctForbiddenPaymentMethods = Mage::helper('payfilter')->getForbiddenPaymentMethodsFromProduct($_product);*/
		//	print_r($vendorPaymentMethods = $vendorIfo->getVendoradminPaymentMethods());
			$vendorAdminPaymentMethods = $vendorIfo->getVendoradminPaymentMethods();
			$vendorCOD = true;
			foreach ($vendorAdminPaymentMethods as $method)
				{
				   if($method == 'cashondelivery')
					{
						$vendorCOD = false;
						break;
					}
				
				}
			/*if ($vendorCOD)
				{
				   $_pageHtml .= '<br><a href="#" class="craftsvilla_cash_on_delivery">Cash On Delivery Available</a>';
				}*/
			
	?>
	<?php 
		/* get the data    Added By Dileswar On dated 07/01/2013 for get the quantity &  price of tier prices..*/
		$my_tier_rocks = $this->getTierPrices($_product);
		if (!empty($my_tier_rocks))
			{
			$my_tier_rocks = $this->getTierPrices($_product);
			foreach($my_tier_rocks as $_tierprice)
				{
				$my_tier_rocks1 = $_tierprice['formated_price_incl_tax'];
				$my_tier_rocks2 = $_tierprice['price_qty'];
				}
			$_pageHtml .='<li>Wholesale Price : <span class="price">'.$my_tier_rocks1.'</span> &nbsp;Min Order Qty : <span class="price">'.$my_tier_rocks2.'</span></span></li>';
			} /*end showing tier prices */ 
	?>
	<?php
	  
      $_pageHtml .='</ul>
      <div id="dtlPrice">';
      
        /*********SIZE***************/
        
			/*$attribute = $_product->getResource();
			var_dump($attribute);*/
$_pageHtml .=
      '<div id="dtlSize">';
          	$group = $_product->isComposite();
		if ($group != true) { 
            /*<span>Size</span><br /> 
					<span class="size"> //echo($_product['size']);?></span>*/
           } else {
          if ($_product->isSaleable() && $this->hasOptions()):
                $_pageHtml .= $this->getChildChildHtml('container2', '', true, true);
          endif;
          }
$_pageHtml .='</div>
        <div id="dtlQty">';
		
		
          $_product = $this->getProduct();
          //if($_product->isSaleable()):
            if(!$_product->isGrouped()):
$_pageHtml .='<label for="qty">'.$this->__('Quantity:').'</label>';

$_pageHtml .='<input type="text" name="qty" id="qty" maxlength="12" value="1" />';
            endif;
        // endif;
     $_pageHtml .=
         '<div id="numbers">
            <div id="num_up"><script type="text/javascript">
                    var cur_value_plus = jQuery("#qty").attr("value");
                    jQuery("#num_up").click(function(){
                            jQuery(".num_down").css("display","block");
                            cur_value_plus++;
                            jQuery("#qty").attr("value",cur_value_plus);
                    });
                    jQuery(".num_down").click(function(){
                            cur_value_plus--;
                            jQuery("#qty").attr("value",cur_value_plus);
                                    if(cur_value_plus==1){
                                            jQuery(".num_down").css("display","none");
                                    }
                    });
            </script> 
        </div>
            <div id="num_down" class="num_down" style="display:none;"></div>
          </div>';

   $_pageHtml .= '<div id="quantity"><input type="hidden" name="pid" id="qtyproductid12" value="'.$productIdCache.'" /></div>';
   
/*Commented on dated 24-03-2014  for block product_type_data to get the price we added getPriceHtml()*/
/*   $_pageHtml .='</div>
        <div id="Price">'.$this->getChildHtml('product_type_data').'
        </div>
        <br />
        <div style="clear:both;"></div>
        <div class="fleft">';*/
   
   $_pageHtml .='</div>
        <div id="Price">'.$this->getPriceHtml($_product,true).' 
        </div>
        <br />
        <div style="clear:both;"></div>
        <div class="fleft">';
   
        $stockConfigProd=strpos($stockConfig,'1');
			if($_productInventoryData['is_in_stock']==1 && $_product->getTypeId() != "configurable"){
                            $_pageHtml .= '<button class="spriteimg" type="submit" id="dtlAddCart"></button>';
                        }
			elseif($stockConfigProd!=false && $_product->getTypeId() == "configurable"){
				
                                $_pageHtml .= '<button class="spriteimg" type="submit" id="dtlAddCart"></button>';
                        }        
                        else{
				$_pageHtml .= '<p class="spriteimg pro_soldout" title="Sold Out"></p>';
                        }        
        $_pageHtml .= '</div>';
        
$_pageHtml .='<div id="dtlSocialLink">
             Confused?';
            //if(Mage::getSingleton('customer/session')->isLoggedIn()):
              //  $_pageHtml .='<a rel="nofollow" class="fancybox contactseller" href="#contact_seller">Contact Seller</a>';
            //else:
                $_pageHtml .='<a rel="nofollow" class="contactseller" onclick="contactseller()" >Contact Seller</a>';
           // endif;
		$metaTitle = $_product->getData('meta_title');
		
    $_pageHtml .='</div>
        
     <!--<div class="wholesale">
        	<a rel="nofollow" class="fancybox" href="#wholesale">Buy This Item Wholesale</a>
        </div>-->
        
        <div class="clear"></div>
        <div class="tabs_social">
           <ul id="socielicon" class="visible fleft">';
$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
$_pageHtml .='<li class="wishit" onclick="wishthisprod()" ><input type="button" id="imgwish" class="wishit_buttons" /></li>';
$_pageHtml .='<li><a class="addthis_button_facebook_like" fb:like:layout="button_count" addthis:url="'.$_product->getProductUrl().'"></a></li>';
$_pageHtml .='<li><a class="addthis_button_tweet"></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f34adfd2fa3a766"></script></li>';
$prodImage=$this->helper('catalog/image')->init($_product, 'image')->resize(500, 500);
$_pageHtml .='<li><a href="http://pinterest.com/pin/create/button/?url='.$_product->getProductUrl().'&media='.$prodImage.'&description='.$metaTitle.'" class="pin-it-button" count-layout="none" target="_blank"><img border="0" src="//assets.pinterest.com/images/PinExt.png"/></a></li>';
$_pageHtml .='</ul>
    </div>
	
             <p class="clr"></p>';
			  if ($vendorCOD)
				{
					$_pageHtml .= "<div id='cash'>";
 $_pageHtml .= "<div id='craftsvilla_cash_on_delivery'><div class='active'>Cash On Delivery Available</div></div><br>";
				
$_pageHtml .= "
 <br><div id='pincode_form'>
 <label id='check'><font size='-1'>
 Check Cash On Delivery Below:</font></label><br>
 <input type='text' name='pincode_value' placeholder='Enter Pincode' id='pincode_value' style='width:90px;height:30px'>
  
<a href='#pincode' class='craftsvilla_pincode' onClick='submitform();return false;'> CHECK </a>
</div><br>";
$_pageHtml .="<div id='pincode' style='display:none'></div>";
$_pageHtml .= "</div>";
$_pageHtml .='<div id="display"></div>';
		}

$_pageHtml .='<div class="clearer"></div><br>';
$_pageHtml .='<div class="clearer"></div><br>';
$_pageHtml .= '<div id="policy"><img src="'.Mage::getDesign()->getSkinUrl('images/5-shipping-icon1.png').'" class="hovertext" />
<div><p><strong>Shipping Policy:</strong><br>
  We deliver in India  within 10 days and outside of India within 21 days.<br> Currently our average delivery time in India is around 4 days and outside<br> of India within 18 days. You will get email and sms of tracking details of <br>domestic shipments within 5-7 days. You can also request seller for<br> expedited shipping by clicking the "Contact Seller" button on the product<br> page after you place the order. We deliver to over 100 countries<br> globally including USA, UK, Australia and Canada. </p>
</div>&nbsp;&nbsp;
<img src="'.Mage::getDesign()->getSkinUrl('images/return-icon.jpg').'" class="hovertext1" />
<div><p><strong>Refund Policy:</strong><br>
We have a friendly return policy whereby we refund for products which are damaged,<br> broken, have manufacturing defects, wrong size or does not match with photo/description<br> as given on Craftsvilla. The customer/buyer has to get back to Craftsvilla customer care through<br> phone/email within 24 hours of receipt of damaged goods or goods not meeting description.<br> Craftsvilla will then log a dispute and initiate a process of resolution between the artisan/designer<br> and the customer. Customer will have to send an image of product on email in case she is claiming<br> that the product is damaged or not meeting description. </p>
</div>&nbsp;
<img src="'.Mage::getDesign()->getSkinUrl('images/40by40.png').'" class="hovertext2" />
<div><p><strong>100% Secured Payments:</strong><br>
We guarantee that your payment is 100% secured with us as your payment details<br> are never shared to anyone during the payment process. You transparently pay through<br> our payment gateway or Paypal and all the data is transferred through high level encryption<br> technology. Please note you pay to "Kribha Handicrafts Pvt Ltd" since that is the company <br>which owns Craftsvilla.com brand and online store. Craftsvilla.com is a brand you can<br> 100% trust. We have been convered widely in Indian and Western Media including newspapers<br> like Timesofindia, Economic Times, Hindu ad TV channels like CNBC, ETNow and Zee and<br> Western Media like Dow Jones and Techcruch.</p>
</div></div>';
$_pageHtml .=  '<div id="dtlGift">';

$couponread = Mage::getSingleton('core/resource')->getConnection('core_read');
			$coupon="select * from `salesrule` where `vendorid`='".$vendorIfo['vendor_id']."' AND `is_active`=1 AND `to_date` > NOW()";
			$result=$couponread->query($coupon)->fetchAll();
			if($result)
			{
			$vendorcoupon['code']=array();
			$vendorcoupon['description']=array();
			$vendorcoupon['vendor_name']=array();
			$ruleid = $result[0]['rule_id'];
				$coupondesc = "select `code` from `salesrule_coupon` where `rule_id` = '".$ruleid."'";
				$resultc=$couponread->query($coupondesc)->fetchAll();
					$vendorcoupon['vendor_name'] = substr($result[0]['vendor_name'],0,30);
					$vendorcoupon['code'] =$resultc[0]['code'];
					$vendorcoupon['description'] =$result[0]['description'];
					$expirydate = $result[0]['to_date'];
		
				 if(sizeof($vendorcoupon['vendor_name'])>0)
		    {  
			   $_pageHtml .= '<div id="dtlCompanyLogo"><table border="1"><tr><td rowspan="2"><div id="craftsvilla_coupons_product"><div class="active">Offers</div></div></td>';
			$_pageHtml .= '<td style="padding-right: 6px;padding-left: 6px;vertical-align: center"><font size="2px">COUPON</font>: <strong>'.$vendorcoupon['code'].'</strong></td></tr><tr><td style="padding-right: 6px;padding-left: 6px;"><font size="1px"><strong>'.$vendorcoupon['description'].'</strong></td></tr></table>';
			
				 $_pageHtml .= '</div>';
			}
			}
          /*<a href=""><img src="<?php //echo $this->getSkinUrl('images/dtl_gift.jpg') ?>" /></a>*/
$_pageHtml .='</div>
        <div id="dtlCompanyLogo">';
            $url= $_helpm->getVendorUrl($data->vendor_id);
            $storeurl = $_helpm->getVendorUrl($vendorIfo->getData('vendor_id'));
            $vendorLogo = $vendorIfo->getShopLogo()!='' ? $vendorIfo->getShopLogo() : 'vendor/noimage/noimage.jpg';
                                    
									$Feedback = Mage::getModel('feedback/vendor_feedback')->getCollection()
                                    ->addFieldToFilter('vendor_id',$vendorIfo->getData('vendor_id'))
                                    ->addFieldToFilter('feedback_type',1)
                                    ->addExpressionFieldToSelect('total','count({{feedback_id}})','feedback_id');
									
$_pageHtml .='          
          <span class="seller_image"><a href="'.(substr($storeurl, 0, -1)).'" target="_blank"><img src="'.($_helpm->getResizedUrl($vendorLogo,70)).'" /></a></span>
          <div class="fleft seller-right">';
$_pageHtml .='<p class="vendorName"><a href="'.(substr($storeurl, 0, -1)).'" target="_blank">'.($vendorIfo['vendor_name']).'</a></p>
            <span class="dtlLink-select">';

                $countries = Mage::getModel('directory/country_api')->items();
                $country = '';
                $region = '';
                $country = $vendorIfo["country_id"];
                if($country!=''){
                    $state_list = Mage::getModel('directory/region_api')->items($country);
                    $region = $vendorIfo['region_id'];
                    if($region!=''){
                        foreach($state_list as $key => $value) {
                            if ($value['region_id'] == $region) {
                                $state_name = $value['name'];
                                break;
                            }
                        }
                    }
                } 
$_pageHtml .='<span>'.($vendorIfo['city']).','.$state_name.'</span></span>';

// Removed Feedback On dated 13-12-12
            /*$_totalFeedbackData = $Feedback->getData();
            $_totalFeedback = $_totalFeedbackData[0]['total'];
            $positiveFeedbackCollection = Mage::getModel('feedback/vendor_feedback')->getCollection()
                                                    ->addFieldToFilter('vendor_id',$vendorIfo->getData('vendor_id'))
                                                    ->addFieldToFilter('rating',2)
                                                    ->addFieldToFilter('feedback_type',1)

                                                    ->addExpressionFieldToSelect('total','count({{feedback_id}})','feedback_id');
            $positiveFeedbackData = $positiveFeedbackCollection->getData();
            $positiveFeedbackPercent = round(($positiveFeedbackData[0]['total'] * 100)/$_totalFeedback);
    
            if($positiveFeedbackData[0]['total'] > 0)
            { 
                $feedbck= "href=".$storeurl."feedback target='_blank'"; 
            }*/
//Below two lines added by dileswar to get the rating of feedback values on dated 23-10-2013***********stasrt

            $vendorTotaldata = Mage::getModel('udropship/vendor')->load($vendorIfo['vendor_id']);
			$feedbackRatingVendor = $vendorTotaldata->getData('feedback_vendorrating');

//Below two lines added by dileswar to get the rating of feedback values on dated 23-10-2013***********END
			

			$positiveFeedbackPercent = $feedbackRatingVendor;
            
 $_pageHtml .='<a'.$feedbck.'>
            <div class="classification">
              <div class="tooltip">
                <p class="arowtooltip spriteimg"></p>';
$_pageHtml .='Feedback:'.$_totalFeedback.",".$positiveFeedbackPercent.'% pos. </div>
              <div class="cover"></div>
              <div class="progress" style="width:'.$positiveFeedbackPercent.'%;"></div>
            </div>
            </a>';

			
          $_pageHtml .='</div> <div class="clr follo-countainer">';

            
        // $_pageHtml .='<div id="followshopprod"></div>';
	 
		 
         //$_pageHtml .=$this->getLayout()->createBlock('follow/follow')->setTemplate('follow/follow.phtml')->toHtml();
            
   // Commented below line for block Recent sales path      
	//$_pageHtml .='<p class="links"><a rel="nofollow" href="'.$storeurl.'thoughtyard/policies/" target="_blank">Seller Policies</a> | <a rel="nofollow" class="selectedrecentsales" href="'.$storeurl.'thoughtyard/recentsales/" target="_blank">Recent Sales</a></p>

    $_pageHtml .='<p class="links"><a rel="nofollow" href="'.$storeurl.'thoughtyard/policies/" target="_blank">Seller Policies</a></p>
		  </div>
        </div>';
   
	
	
			//echo $result['code'];
          //if (!$this->hasOptions()):
          //echo $this->getChildHtml('extra_buttons') 
           //else:
          //echo $this->getChildHtml('addto')
          //endif;
		 
         $_pageHtml .=$this->getChildHtml('other');
     //commented on dated 24-03-2014 for block container1 html....    
		  if ($_product->isSaleable() && $this->hasOptions()):
           // $_pageHtml .=$this->getChildChildHtml('container1', '', true, true);
          endif;


  /*if(isset($_POST['submit']) && array_key_exists('pincode', $_POST)):
	
    $pincode  = $_POST['pincode'];
    $read = Mage::getSingleton('core/resource')->getConnection('core_read');
			$pincodeQuery = "SELECT * FROM `checkout_cod_craftsvilla` where `pincode` = '".$pincode."'";
			$rquery = $read->query($pincodeQuery)->fetch();
	  $cod = $rquery['is_cod'];
	  if($cod=='0')
	  {
		echo 'COD is Available';
	  }
	   else
	  {
		echo 'COD is Not Available';
	  }
	  
endif;*/
$_pageHtml .='<div class="clearer"></div>';
        /* if ($_product->isSaleable() && $this->hasOptions()):?>
				<?php  echo $this->getChildChildHtml('container2', '', true, true) ?>
			<?php endif; */
$_pageHtml .='</div>
      </div>';
 
$_pageHtml .='<div class="product-view setwidth">
      <div>
        <div>
		   <input type="hidden" name="product" value="'.$_product->getId().'" />
          <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>';
$_pageHtml .='<div class="product-img-box">'.$this->getChildHtml('media')
          /*<div class="product-img-box-zoom"></div>*/.'
        </div>
      </div>
	 <div id="dtlText">';
  
        foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):
            if ($title = $this->getChildData($alias, 'title')):
               $_pageHtml .= $this->escapeHtml($title);
            endif;
$_pageHtml .= $html;
        endforeach;
$_pageHtml .='</div>
    </div>
	
    <div class="clear"></div>
	
  </form>
</div> ';

$_pageHtml .='<div class="product-view">
  <div> 

 </div>

</div>';
//$_pageHtml .=$this->getChildHtml('contactseller');


//$_pageHtml .=$this->getLayout()->createBlock('wholesale/index')->setTemplate('wholesale/index.phtml')->toHtml();


//$_pageHtml .= '<iframe src="http://www.vizury.com/analyze/analyze.php?account_id=VIZVRM209&param=e300&pid='.$productIdCache.'&catid='.$catId.'&subcat1id=&subcat2id=&section=1&level=1" scrolling="no" width="1" height="1" marginheight="0" marginwidth="0" frameborder="0"></iframe>';
    


?>
<!--code for vizury--->
<?php 

//if(Mage::registry('current_category')) { 
//$catId = Mage::registry('current_category')->getId();
//$category=Mage::getModel('catalog/category')->getChildrenCategories();
//$catIds=$_product->getCategoryIds();
//$catId=$catIds[0];
/*$category=Mage::getModel('catalog/category')->getCategories($catIds[0]);

foreach($category as $cat)
{
    if($cat->getId())
  	{
      $subcatId1=$cat->getId();
	}
	/*if(in_array($cat->getId(), $catIds))
    {
        $subcatId1=$cat->getId();
    }*/
   /* else
    { 
        $subcatId1="";
    }*/
    
//}
//}
?>
<?php 
$cacheContentProduct = $_pageHtml;
    $tags = array(
                    //Mage_Catalog_Model_Product::CACHE_TAG,
                    //Mage_Catalog_Model_Product::CACHE_TAG . '_' . $productIdCache
                );
    $CacheIdProduct = "productcache-$productIdCache-currency-$_currencyCodeProduct";
    //Mage::app()->saveredisCache($cacheContentProduct, $CacheIdProduct, $tags, $lifetime);
    echo $cacheContentProduct;
 
 echo $this->getChildHtml('contactseller');
 
?>

<script type="text/javascript">
    
    //jQuery(document).ready(new function() {
      // var vendorId='<?php //echo $vendorIfo->getData('vendor_id')?>';
      // var u ='<?php //echo Mage::getBaseUrl().'follow/index/followshopproduct/' ?>';
       // new Ajax.Request(u, {method:'post', parameters: {vendorid:vendorId}, onSuccess: function(transport) {
         //          jQuery('#followshopprod').html(transport.responseText);
           //    }
       // });
        
   // });
    
     function contactseller(){
         jQuery.fancybox({width:'430px', height:'22px',href:"#contact_seller"});
          
       } 
	   
	  
    function wishthisprod(){
        <?php //if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
               var u ='<?php echo Mage::getBaseUrl().'wishlist/publicshare/wishthisprod' ?>';
        new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
	if(transport.responseText == 'notlogged')
				{
				 jQuery.fancybox({width:'430px', height:'22px',href:"#wishthis"});
				}
			else{

                   jQuery('#imgwish').addClass('wishit_hide');
                    var u = "<?php echo $_wishlistSubmitUrl ?>" ;
                            new Ajax.Request(u, {method:'post', parameters: {}, onSuccess: function(transport) {
                                            if(transport.responseText == 'wished')

                                                var locate = "<?php echo $_SERVER['HTTP_REFERER']; ?>";
                                            window.location(locate);	
                                    }
                            });
		               }		
				}
        });
            <?php //else:?>
                //jQuery.fancybox({width:'430px', height:'22px',href:"#wishthis"});
            <?php //endif;?>
    }
    
    
    //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button){
                if (this.validator.validate()) {
                    this.form.submit();
                    if (button && button != '.undefined.') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);
    //]]>
	
	
	
      function submitform() {
		jQuery('#pincode').show();
		 var pincode = document.getElementById("pincode_value").value;

	 var param = 'pincode='+pincode;
	var pincodeurl = '<?php echo Mage::getBaseUrl().'generalcheck/pincode/pincodecheck' ?>';

	jQuery.ajax({
		url : pincodeurl,
		type: "post",
		//cache : false,
		data : param,
		success : function(data) {
			jQuery('#pincode').html(data);
		// window.scrollTo(0, 0);
			return false;
  
					
		},
		error:function(){
            alert("failure");
            jQuery("#pincode").html('There is error while submit');
        }
	})
      }
	  
	  
	  jQuery(document).ready(new function() {
		  var pidvalue = document.getElementById("qtyproductid12").value;
		  
      var u ='<?php echo Mage::getBaseUrl().'generalcheck/inventory/inventorycheck/' ?>';
       new Ajax.Request(u, {method:'post', parameters: {pidvalue:pidvalue}, onSuccess: function(transport) {
                  jQuery('#quantity').html(transport.responseText);
               }
        })
	});
	
	
    </script> 
