<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript" ></script>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="detailCotainer">
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
	<div class="product-view">
    	<div>
            <div>
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
		</div>
    </div>
	<div class="details">
		<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        <p>
			<?php if ($_product->getShortDescription()):?>
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
            <?php endif;?>
        </p>
        <div id="dtlPrice">
            <ul>
                <li><?php echo $this->getChildHtml('product_type_data') ?></li>
                <li>
                    <?php $_product = $this->getProduct(); ?>
                    <?php if($_product->isSaleable()): ?>
                    <?php if(!$_product->isGrouped()): ?>
                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" />
                    <?php endif; ?>
                    <?php endif; ?>
                </li>
                <li><?php $buttonTitle = $this->__('Add to Cart'); ?>
                <input type="submit" value="<?php echo $buttonTitle ?>" class="addToCart" title="<?php echo $buttonTitle ?>" />
                </li>
                <li class="confprocont">
                <?php if (!$this->hasOptions()):?>
                <?php //echo $this->getChildHtml('extra_buttons') ?>
                <?php else:?>
                <?php //echo $this->getChildHtml('addto') ?>
                <?php endif; ?>
                <?php echo $this->getChildHtml('other');?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
                </li>
            </ul>
        </div>
	</div>
	<div class="clear2"></div>
	<div class="blueScl">
       <!-- <ul>
        	<li><a class="fb_share" name="fb_share" type="button" href="http://www.facebook.com/sharer.php?u=<?php// echo $currUrl;?>">Share</a></li>
        	<li style="margin-top:5px"><a href="http://twitter.com/share" class="twitter-share-button" data-count="none" data-via="YourTwitterID">Tweet</a></li>
        	<li><?php// if ($this->canEmailToFriend()): ?>
        	<a href="<?php// echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php// echo $this->__('Email to a Friend') ?>
            </a>
        	<?php// endif; ?>
            </li>
        	<li><?php// echo $this->getChildHtml('addto') ?></li>
        </ul>-->
        
        
        
        <!-- AddThis Button BEGIN -->


<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f34adfd2fa3a766"></script>
<!-- AddThis Button END -->
        
	</div>
    
 


    
    
	<div class="clear"></div>
  
      
  <!--tab code start-->      
  <!--<script src="<?php echo $this->getSkinUrl('js/jquery.js')?>"></script>
 <script src="<?php echo $this->getSkinUrl('js/ui.js')?>"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/tabcss.css')?>" type="text/css">
<script type="text/javascript">	
		$(function(){
			//tabs
			$('#tabs ul').tabs();
		});
	</script> 
               
<div id="tabs">
  <ul>
    <li class="ui-tabs-nav-item"><a href="#fragment-1">Product Detail</a></li>
    <li class="ui-tabs-nav-item"><a href="#fragment-2">Policies Information</a></li>
    </ul>
<span class="clr"></span>
  <div id="fragment-1">
  	<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <?php if ($title = $this->getChildData($alias, 'title')):?>
        <?php echo $this->escapeHtml($title); ?>
        <?php endif;?>
        <?php echo $html; ?>
        <?php endforeach;?>
  </div>
  <div id="fragment-2">
       <?php
		$_helpm = $this->helper('umicrosite');
		$vendorIfo = $_helpm->getCurrentVendor(); 
		//echo "<pre>"; print_r($vendorIfo->getData()); exit;
		?>
      <ul class="polinfo">
       <?php if($vendorIfo->getShipHandlingTime()) { ?><li><label>Shipping handling Time:</label><p class="value"><?php echo $vendorIfo->getShipHandlingTime();?></p></li><?php } ?>
       <?php if($vendorIfo->getItemLocation()) { ?><li><label>Item Location:</label><p class="value"><?php echo $vendorIfo->getItemLocation();?></p></li><?php } ?>
       <?php if($vendorIfo->getItemReturnInDays()) { ?><li><label>Item to be Returned in:</label><p class="value"><?php echo $vendorIfo->getItemReturnInDays();?></p></li><?php } ?>
       <?php if($vendorIfo->getRefundMadeAs()) { ?><li><label>Refund will be given as:</label><p class="value"><?php echo $vendorIfo->getRefundMadeAs(); ?></p></li><?php } ?>
       <?php if($vendorIfo->getRefundCostBearer()) { ?><li><label>Return cost paid by:</label><p class="value"><?php echo $vendorIfo->getRefundCostBearer(); ?></p></li><?php } ?>
       <?php
			$policyDetails = ''; 
			if($_product->getReturnPolicyDetail())
				$policyDetails = $_product->getReturnPolicyDetail();
			elseif($vendorIfo->getReturnPolicyDetail())
				$policyDetails = $vendorIfo->getReturnPolicyDetail();
			if($policyDetails != '') {
		?>

				<li class="clr"><label>Return Policy Details:</label><p class="value"><?php echo $policyDetails; ?></p></li><?php } ?>
      
      </ul>
                   
       
       
       
  </div>
 
</div>-->
<!-- TABS -->
    <!--tab code start end-->      
        <div class="clear"></div>
    <p class="contentBrdr">
		<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <?php if ($title = $this->getChildData($alias, 'title')):?>
        <?php echo $this->escapeHtml($title); ?>
        <?php endif;?>
        <?php echo $html; ?>
        <?php endforeach;?>
    </p>
         </form>
        
        
         
    </div>
<div class="product-view">
    <div>
    <script type="text/javascript">
    //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button){
                if (this.validator.validate()) {
                    this.form.submit();
                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
</div>

  
