<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_DropshipPo
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>
<?php $_item  = $this->getItem() ?>
<?php $_order = $_item->getOrder() ?>
<tr>
    <td align="left" valign="top" style="padding:3px 9px">
        <strong><?php echo $this->htmlEscape($_item->getName()) ?></strong>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $this->htmlEscape($_item->getDescription()) ?>
    </td>
    <td align="left" valign="top" style="padding:3px 9px"><?php echo $this->htmlEscape($this->getSku($_item)) ?></td>
    <td align="right" valign="top" style="padding:3px 9px"><?php echo $_order->formatPrice($_item->getBaseCost()) ?></td>
    <td align="center" valign="top" style="padding:3px 9px"><?php echo $_item->getQty()*1 ?></td>
    <td align="right" valign="top" style="padding:3px 9px"><?php echo $_order->formatPrice($_item->getBaseCost()*$_item->getQty()) ?></td>
</tr>
