<?php
$_vendor = Mage::helper('umicrosite')->getCurrentVendor();
$_productListBlock = $this->getChild('product_list');
$storeCode = Mage::app()->getStore()->getCode();
?>
<h1 class="headingvendor homeprite">
<?php //echo $this->htmlEscape(Mage::helper('umicrosite')->getLandingPageTitle($_vendor)) 
		echo $_vendor->getVendorName();
?> Products
</h1>
<!--<div class="generic-box vendor-description">
<img src="<?php echo Mage::getBaseDir('media').DS.$_vendor->getLogo() ?>" class="vendor-img"/>
<?php echo $this->htmlEscape($_vendor->getDescription()) ?>
</div>-->

<div id="our-products">
<?php echo $_productListBlock->toHtml() ?>
</div>
