<div class="wrapper footer_wrapper">
<div>
<div class="bdyShadow2">
<div class="bodyWpr">
<div class="footer">
<div class="ftrCnr">
<div class="ftrTpBg" style="height:35px;">
   
</div>
<div class="ftrBgClr">
<div class="ftrBg">
<div class="card_fb_tw">
<p>FOLLOW US</p>
<a href="http://facebook.com"><img src="<?php echo $this->getSkinUrl('images/fb_new.png')?>" alt="" /></a> <a href="http://twitter.com"><img src="<?php echo $this->getSkinUrl('images/tweet_new.png')?>" alt="" /><br /></a></div>
                         <ul>
                            <li id="brdrNo"><h3>our company</h3></li>
                            <li><a href="<?php echo $baseurl;?>/about-us-craftsvilla">About us</a></li>
                           <!-- <li>Home decors</li>-->
                            <li><a href="<?php echo $baseurl;?>/how-to-buy-craftsvilla">How to buy</a></li>
                            <li><a href="http://blog.craftsvilla.com" target="_blank">Blog</a></li>
                            <li><a href="<?php echo $baseurl;?>/secure-shopping-craftsvilla">Secure Shopping</a></li>
                        </ul>

                        <ul>
                            <li id="brdrNo"><h3>useful info</h3></li>
                            <li><a href="<?php echo $baseurl;?>/faq-craftsvilla">FAQ's</a></li>
                            <li><a href="<?php echo $baseurl;?>/catalog/seo_sitemap/category">Sitemap</a></li>
                            <li><a href="<?php echo $baseurl;?>/Contact Us"</a></li>
                          <li><a href="<?php echo $baseurl;?>/Resources"</a></li>
                        </ul>

                        <ul>
                            <li id="brdrNo"><h3>Policies &amp; Info</h3></li>
                           <li><a href="<?php echo $baseurl;?>/terms-and-conditions-craftsvilla">Terms and Conditions</a></li>
                           <!-- <li><a href="{{store url="privacy-policy-craftsvilla"}}">Privacy Policy</a></li>-->
                            <li><a href="<?php echo $baseurl;?>/policy-for-sellers">Policy for Sellers</a></li>
                            <li><a href="<?php echo $baseurl;?>policy-for-buyers">Policy for Buyers</a></li>
                           <!--  <li><a href="{{store url="shipping-craftsvilla"}}">Shipping by Craftsvilla</a></li> -->
                            <li><a href="<?php echo $baseurl;?>/shipping-artisans-designers">General Shipping Policies</a></li>                                             
                           
                        </ul>
                        
                        <ul>
                            <li id="brdrNo"><h3>Sellers</h3></li>
                            <li><a href="<?php echo $baseurl;?>/uagent/">Agent Login</a></li>
                            <li><a href="<?php echo $baseurl;?>/uagent/register/register/">Agent Sign up</a></li>
<li><a href="<?php echo $baseurl;?>/sell">Agent on Craftsvilla</a></li>
<li><a href="http://craftsvilla.yolasite.com" target="_blank">Agent Control Panel</a></li>  </ul>
</div>
</div>
<div class="ftrbottom">
<div class="floatl"><img src="<?php echo $this->getSkinUrl('images/visa_mc_cards.png')?>" alt="" /> <span>Debit Cards, Net Banking - All Leading banks, Cash On Delivery</span>
<p class="paygateway"><img style="vertical-align: middle;" src="<?php echo $this->getSkinUrl('images/wtf_img.png')?>" alt="" />
<span style="font-size: 10px; padding: 5px 0pt 0pt;"> certified payment gateway</span></p></div>
<div class="floatr"><span>&copy; Craftsvilla.com. All rights reserved.</span> </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>