<?php
$_session = Mage::getSingleton('uagent/session');
$_agent = Mage::registry('reset_agent');
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('uagent/register/passwordPost')?>" method="post" id="password-form">
<div class="login-box generic-box" style="width:300px">
	<div class="box-head"><h3><?php echo $this->__('Agent Password Reset') ?></h3></div>
    <div class="col-1 registered-users">
        <div class="content">
            <ul class="form-list">
                <li>
                    <label><?php echo $this->__('Email Address/User name') ?></label>
                    <input value="" title="<?php echo $this->__('Email') ?>" type="text" class="input-text" id="email" name="email" style="width:250px;"  />
                </li>
                <li>
                    <label for="password"><?php echo $this->__('New Password') ?> <span class="required">*</span></label>
                    <input name="password" value="" title="<?php echo $this->__('New Password') ?>" id="password" type="password" class="input-text required-entry validate-password" style="width:250px;" />
                </li>
                <li>
                    <label for="password_confirm"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label><br />
                    <input name="password_confirm" value="" title="<?php echo $this->__('Confirm Password') ?>" id="password_confirm" type="password" class="input-text required-entry validate-cpassword" style="width:250px;" />
                </li>
            </ul>
            <p class="required clr"><?php echo $this->__('* Required Fields') ?></p>
        </div>
            <button class="form-button" type="submit" name="send"><span><?php echo $this->__('Reset Password') ?></span></button>
    </div>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('password-form', true);
</script>