<script type=""text/javascript"">// <![CDATA[
function sendReminder(invite_friends) {
//var invite_friends = document.getElementById('Invite1_txtEmail').value;
//alert(invite_friends);
if(invite_friends=='')
{
 alert("email errror!");
}
else {
 var reloadurl = '<?php echo $this->getUrl('referfriend/index/reminder') ?>';
 new Ajax.Request(reloadurl, {
 method: 'post',
 parameters: {invite_friends:invite_friends,invite_box:'1',Submit:'Send Invites',homeInvite:'1'},
 onComplete: function(transport) {
 //alert('ashu');
 //$('output-div').innerHTML = """";
 //$('output-div').innerHTML = transport.responseText;
  alert('Reminder mail has been sent!');
 }
 });
}


}
// ]]></script>
<div class="page-title">
    <h1><?php echo $this->__('My Referrals') ?></h1>
</div>

<?php $referrals = $this->getReferrals()->getdata(); ?>
<?php //echo $this->getPagerHtml(); ?>
<?php if(!empty($referrals)): ?>
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
	<col width="1" />
    <thead>
        <tr>
            <!--<th><?php echo $this->__('Referal No.') ?></th>-->
            
            <th><?php echo $this->__('Friends') ?></th>
	    <th><?php echo $this->__('Last Invitation Sent') ?></th>
            <th><span class="nobr"><?php echo $this->__('Send Reminder') ?></span></th>
            <!--<th><span class="nobr"><?php echo $this->__('Has Purchased') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Earnings') ?></span></th>-->

        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; $i=''; ?>
        <?php foreach ($referrals as $referral): 
				$i++;
				$this->registration_status = $referral['referral_register_status'];
				$this->purchase_status = $referral['referral_purchase_status'];

				if($this->getRegistrationStatus()!='Yes') :
		?>
        <tr>
            <!--<td><?php echo $i ?></td>-->
            
            <td><?php echo $referral['referral_email'] ?></td>
	    <td><span class="nobr"><?php echo $referral['created_ts'] ?></span></td>

            <td><a href="#" onClick="sendReminder('<?php echo $referral['referral_email'] ?>')"><?php echo 'Send Reminder'; ?></a></td>
           <!-- <td><?php echo $this->getPurchaseStatus() ?></td>
            <td><?php echo $ii; ?></td>-->
        </tr>
        <?php endif; endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php //echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>

<!-- accepted invitation list -->
<?php if(!empty($referrals)): ?>
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
	<col width="1" />
    <thead>
        <tr>
            <!--<th><?php echo $this->__('Referal No.') ?></th>-->
            
            <th><?php echo $this->__('Friends') ?></th>
	    <th><?php echo $this->__('Last Invitation Sent') ?></th>
            <th><span class="nobr"><?php echo $this->__('Is Member') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Has Purchased') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Earnings') ?></span></th>

        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; $i=''; ?>
        <?php foreach ($referrals as $referral): 
				$i++;
				$this->registration_status = $referral['referral_register_status'];
				$this->purchase_status = $referral['referral_purchase_status'];
				if($this->getRegistrationStatus()=='Yes') :
		?>
        <tr>
            <!--<td><?php echo $i ?></td>-->
            
            <td><?php echo $referral['referral_email'] ?></td>
	    <td><span class="nobr"><?php echo $referral['created_ts'] ?></span></td>

            <td><?php echo $this->getRegistrationStatus(); ?></td>
            <td><?php echo $this->getPurchaseStatus() ?></td>
            <td><?php echo $ii; ?></td>
        </tr>
        <?php endif; endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php //echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>