<div class="right-box-form">
	<div id="content-colum-var">
		<div class="leftarea">
			<div><?php echo $this->getMessagesBlock()->getGroupedHtml(); ?> </div>
			<?php $referrals = $this->getReferrals()->getdata(); ?>
			<div class="grid-top-menu">
			<?php if(!empty($referrals)): ?>
			<table border="0" cellspacing="0" cellpadding="2" class="table-border" width="100%">
                <tr >
                    <th><?php echo $this->__('Referal No.') ?></th>
                    <th><?php echo $this->__('Friends') ?></th>
                    <th><?php echo $this->__('Date') ?></th>
                    <th><span class="nobr"><?php echo $this->__('Is Member') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Has Purchased') ?></span></th>
                </tr>
				<tbody>
				<?php $_odd = ''; $i=''; ?>
				<?php foreach ($referrals as $referral): 
					$i++;
					$this->registration_status = $referral['referral_register_status'];
					$this->purchase_status = $referral['referral_purchase_status'];
				?>
                <tr>
                    <td><?php echo $i ?></td>
                    <td><?php echo $referral['referral_email'] ?></td>
                    <td><span class="nobr"><?php echo $referral['created_ts'] ?></span></td>
                    <td><?php echo $this->getRegistrationStatus(); ?></td>
                    <td><?php echo $this->getPurchaseStatus() ?></td>
                    <!--<td><?php echo $ii; ?></td>-->
                </tr>
				<?php endforeach; ?>
			</table>
			
			<script type="text/javascript">decorateTable('my-orders-table');</script>
			<script type="text/javascript">decorateTable('my-orders-table');</script>
			<?php echo $this->getPagerHtml(); ?>
			<?php else: ?>
			<p class="noinvfound"><?php echo $this->__('No invitation found.'); ?></p>
			<?php endif ?>
		</div>
	</div>
</div></div>
<script type="text/javascript">// <![CDATA[
function sendInvite() {
	var invite_friends = document.getElementById('Invite1_txtEmail').value;
	var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

	if(invite_friends=='')
	{
		alert("Please enter invite email");
	}
	else if(reg.test(invite_friends) == false) {
		alert('Please enter valid email');      
	}
	else {
		var reloadurl = "<?php echo $this->getUrl('referfriend/index/send/')?>";
		new Ajax.Request(reloadurl, {
			method: 'post',
			parameters: {invite_friends:invite_friends,invite_box:'1',Submit:'Send Invites',homeInvite:'1'},
			onComplete: function(transport) {
				alert('Invite mail has been sent!');
			}
		});
	}
}
// ]]>
</script>