<?php /*  if($this->getCurrencyCount()>1): ?>
<!-- <div class="block block-currency"> 
    <div class="block-content">-->
        <select name="currency" title="<?php echo $this->__('Select Your Currency') ?>" onchange="setLocation(this.value)" class="slct">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>
 <!--  </div>
 </div> -->
<?php endif;  */?>

<!--<span class="icon icon-dollar" title="Dollar"></span>
<span class="icon icon-rupee" title="Rupee"></span>-->
<?php if($this->getCurrencyCount()>1): ?>
<?php foreach ($this->getCurrencies() as $_code => $_name): ?>
<a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" title="<?php echo $_name ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> class="selected"<?php endif; ?>><span id="<?php echo $_code ?>"></span></a>
<?php endforeach; ?>
<?php endif; ?>
