<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @version    2.4.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<div class="ajaxcartpro_confirm" style="display: none;">
	<p><span id="acp_product_name"><?php echo $this->__('Item(s)') ?></span><?php echo $this->__(' added to cart') ?></p>
	<!-- Start... 
		Craftsvilla Comment
		Added by Suresh on 26-05-2012 commented original and redirect to home page on continue shopping
	-->
		<!-- <a href="#" id="aw_acp_continue" class="focus" onclick="$$('.ajaxcartpro_confirm')[0].style.display='none';return false;"><?php echo $this->__('Continue shopping')?><?php echo Mage::helper('ajaxcartpro')->displayCountdown() ?></a> -->
        <?php 
            if(isset($_SERVER['HTTP_REFERER'])){
                $urlstring=$_SERVER['HTTP_REFERER'];

            }
            else{
                $urlstring=Mage::getBaseUrl();
            }
            //echo $urlstring;
            preg_match("/^(http:\/\/)?([^\/]+)/i", $urlstring, $result);
            $domain = $result[2];
            // Remove any subdomains from domain
            $domain = explode (".", $domain);
            $i = count($domain);
            $domain = $domain[$i-2] . "." . $domain[$i-1];
            // Referral checking
            if ($domain != 'craftsvilla.com')
            {
                $redirectUrlProdPage=Mage::getBaseUrl();
            }
            else
            {
                $redirectUrlProdPage=$_SERVER['HTTP_REFERER'];
            }

        ?>
        
		<a href="<?php echo $redirectUrlProdPage ; ?>" id="aw_acp_continue" class="focus"><?php echo $this->__('Continue shopping')?><?php echo Mage::helper('ajaxcartpro')->displayCountdown() ?></a>
		
	<!-- End... 
		Craftsvilla Comment
		Added by Suresh on 26-05-2012 commented original and redirect to home page on continue shopping
	-->
	<?php echo $this->__('or')?>

	<a href="http://www.craftsvilla.com/dreamjwell" id="aw_acp_continue">
		<?php echo $this->__('Shop Amazing Jewelry')?></a>

	<?php echo $this->__('or')?>

	<a href="<?php echo Mage::getUrl('checkout/cart')?>" id="aw_acp_checkout">
		<?php echo $this->__('View cart &amp; checkout')?>
		
		
	</a>
</div>
