<div class="fieldsetCntnr marginRt">
    <div class="fieldset minHt">
        <h2 class="legend">Address Book</h2>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a><br/>
        <h5><?php echo $this->__('Default Billing Address') ?></h5>
        <address>
            <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
        </address>
    </div>
</div>

<div class="fieldsetCntnr">
    <div class="fieldset minHt">
        <h2 class="legend">Default Shipping Address</h2>
        <h5>Shipping Address</h5>
        <address>
            <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
        </address>
    </div>
</div>
