<?php $data = $this->getData(); ?>

<?php if ($data['linked_mode'] == '2'): ?>

    <?php if ($data['image_counter'] == 'first'): ?>

        <style type="text/css">
            .gallery-thumbnail {
                padding: 0;
                margin: 0;
                display: table;
            }
            .gallery-image {
                margin-bottom: 20px;
            }
            .gallery-image div {
                margin-top: 10px;
            }
            .gallery-thumbnail li {
                list-style: none;
                margin: 5px;
                text-align: right;
            }
            .gallery-column-view .gallery-thumbnail {
                width: 20%;
                float: left;
            }
            .gallery-column-view .gallery-image {
                width: 78%;
                float: right;
                text-align: left;
            }
            .gallery-row-view .gallery-thumbnail li {
                float: left;
            }
        </style>

    <center class="<?php if ($data['layout'] == 'column'): echo ' gallery-column-view'; else: echo ' gallery-row-view'; endif; ?>">
        <div class="gallery-image">
            <img name="view<?php echo $data['attribute_counter']; ?>" id="image<?php echo $data['attribute_counter']; ?>" src="<?php echo $data['src']; ?>"<?php if ($data['width'] != ''): echo " width={$data['width']}"; endif; ?><?php if ($data['height'] != ''): echo " height={$data['height']}"; endif; ?> style="<?php if ($data['margin'] != ''): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?>" />
            <br />
            <div style="<?php if ($data['width'] != ''): echo "width: {$data['width']}px"; endif; ?>"><?php echo Mage::helper('M2ePro')->escapeHtml($data['gallery_hint']); ?></div>
        </div>

        <ul class="gallery-thumbnail">

    <?php endif; ?>

            <li>
                <img width="68" height="68" style="margin: 2px; cursor: pointer;" onclick="document.images['view<?php echo $data['attribute_counter']; ?>'].src='<?php echo $data['src']; ?>';" src="<?php echo $data['src']; ?>" />
            </li>

    <?php if ($data['image_counter'] == 'last'): ?>

        </ul>
    </center>
            
    <?php endif; ?>

<?php else: ?>

    <?php if ($data['linked_mode'] == '1'): ?>
        <a href="<?php echo $data['src']; ?>" target="_blank">
    <?php endif; ?>

        <img src="<?php echo $data['src']; ?>"<?php if ($data['width'] != ''): echo ' width="'.$data['width'].'"'; endif; ?><?php if ($data['height'] != ''): echo ' height="'.$data['height'].'"'; endif; ?> style="<?php if ($data['margin'] != ''): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?><?php if ($data['linked_mode'] == '1'): echo ' cursor: pointer; border: none;'; endif; ?>" />

    <?php if ($data['linked_mode'] == '1'): ?>
        </a>
    <?php endif; ?>

    <?php if ($data['layout'] == 'column'): ?>
        <br />
    <?php endif; ?>

<?php endif; ?>