<?php $data = $this->getData(); ?>

<?php if ($data['linked_mode'] == 1): ?>
    <a href="<?php echo $data['src']; ?>" target="_blank" style="cursor: pointer;">
<?php endif; ?>

<img src="<?php echo $data['src']; ?>" border="0"<?php if ($data['width'] != 0): echo ' width="'.$data['width'].'"'; endif; ?><?php if ($data['height'] != 0): echo ' height="'.$data['height'].'"'; endif; ?> style="<?php if ($data['margin'] != 0): echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;"; endif; ?>" />

<?php if ($data['linked_mode'] == 1): ?>
    </a>
<?php endif; ?>