<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php $collection = $this->getCollection(); ?>
<?php $currentPage = (int)$this->getRequest()->getParam('page'); ?>
<?php if(!$currentPage): ?>
<?php $currentPage = 1; ?>
<?php endif; ?>
<?php $pages = ceil(count($collection) / 2); ?>
<?php $links = ""; ?>
<?php if ($currentPage != 1): ?>
<?php echo '<a href="' . $this->getUrl('blog/page') . ($currentPage - 1) . '" >' . Mage::helper('blog')->__('Newer Posts') . '</a>'; ?>
<?php endif; ?>
<?php if ($currentPage != $pages): ?>
<?php echo '<a href="' . $this->getUrl('blog/page') . ($currentPage + 1) . '" >' . Mage::helper('blog')->__('Older Posts') . '</a>'; ?>
<?php endif; ?>