<div class="wrapper">
    <div> <?php echo $this->getChildHtml('footer_block') ?> </div>
</div>
<div class="btmShadow"></div>
<div class="ftrCnr">
    <div class="cprts">
        <div class="pmt">Debit Cards, Net Banking - <br/>All Leading banks, Cash On Delivery</div>
        <div class="flw">
            <ul>
                <li id="flwTxt">Follow Us:</li>
                <li><a href="http://www.facebook.com/craftsvilla" target="_blank"><img src="<?php echo $this->getSkinUrl('images/fb.png') ?>" width="27" height="26" alt="Facebook" title="Facebook"/></a></li>
                <li><a href="http://www.twitter.com/craftsvilla" target="_blank"><img src="<?php echo $this->getSkinUrl('images/twitter.png') ?>" width="27" height="27" alt="Twitter" title="Twitter"/></a></li>
                <li><!--Gplus Code--><a class="gplusicon" href="https://plus.google.com/108801490299597047118?prsrc=3" style="text-decoration:none;" target="_blank"><img src="https://ssl.gstatic.com/images/icons/gplus-16.png" alt="" style="border:0;width:16px;height:16px;"/></a><!--Gplus Code end--></li>
            </ul>
        </div>
        <div class="rtTxt">© <a href="http://www.craftsvilla.com">craftsvilla.com.</a> All rights reserved.</div>
    </div>
    
    <p class="clear">certified payment gateway</p>
    
    
</div>

<!--<a href="http://www.slideshare.net/slideshow/embed_code/11381653" title="valentine's day catalog" class="vday" target="_blank"></a>-->

