<?php
    $formData = Mage::registry('M2ePro_data') ? Mage::registry('M2ePro_data')->toArray() : array();
    $defaults = array(
		'condition_value' => '',
        'condition_attribute' => '',

        'product_details_isbn_mode' => 0,
        'product_details_isbn_cv' => '',
        'product_details_isbn_ca' => '',

        'product_details_epid_mode' => 0,
        'product_details_epid_cv' => '',
        'product_details_epid_ca' => '',

        'product_details_upc_mode' => 0,
        'product_details_upc_cv' => '',
        'product_details_upc_ca' => '',

        'product_details_ean_mode' => 0,
        'product_details_ean_cv' => '',
        'product_details_ean_ca' => ''
    );
    $formData = array_merge($defaults, $formData);

    $isEdit = !!$this->getRequest()->getParam('id');
?>

<script type="text/javascript">

    // Data for current tab
    //-----------------------------
    M2ePro.formData.condition_value = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['condition_value']); ?>';
    M2ePro.formData.condition_attribute = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['condition_attribute']); ?>';

    M2ePro.formData.item_specifics = <?php echo json_encode($formData['item_specifics']); ?>;

	M2ePro.formData.product_details_isbn_ca = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['product_details_isbn_ca']); ?>';
    M2ePro.formData.product_details_epid_ca = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['product_details_epid_ca']); ?>';
    M2ePro.formData.product_details_upc_ca  = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['product_details_upc_ca']); ?>';
    M2ePro.formData.product_details_ean_ca  = '<?php echo Mage::helper('M2ePro')->escapeJs($formData['product_details_ean_ca']); ?>';

    M2ePro.customData.attributesReceiving.push(
        {
            id : 'product_details_isbn_ca',
            container : 'product_details_isbn_ca_td'
        }, {
            id : 'product_details_epid_ca',
            container : 'product_details_epid_ca_td'
        }, {
            id : 'product_details_upc_ca',
            container : 'product_details_upc_ca_td'
        }, {
            id : 'product_details_ean_ca',
            container : 'product_details_ean_ca_td'
        }
    );

    M2ePro.text.category_without_item_specific_message = '<?php echo Mage::helper('M2ePro')->escapeJs(Mage::helper('M2ePro')->__("The category <b>%cat%</b> doesn't have Item Specific.")); ?>';

    Event.observe(window, 'load', function() {

        SpecificsHandlersObj = new SpecificsHandlers();
        SpecificsHandlersObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_ListingsTemplatesSpecifics'); ?>');

        $('listingTemplatesTabs_tab_specifics').observe('click', TabsHandlersObj.checkAttributeSetSelection);
        $('listingTemplatesTabs_tab_specifics').observe('click', TabsHandlersObj.checkCategoriesSelection);

	    $('product_details_isbn_mode')
            .observe('change', SpecificsHandlersObj.product_details_isbn_mode_change)
            .simulate('change');

        $('product_details_epid_mode')
            .observe('change', SpecificsHandlersObj.product_details_epid_mode_change)
            .simulate('change');

        $('product_details_upc_mode')
            .observe('change', SpecificsHandlersObj.product_details_upc_mode_change)
            .simulate('change');

        $('product_details_ean_mode')
            .observe('change', SpecificsHandlersObj.product_details_ean_mode_change)
            .simulate('change');
    });
    //-----------------------------

</script>

<div id="listing_template_specifics_condition_container">

    <div id="block_notice_listing_template_specifics_condition" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Item Condition'); ?>">
        <?php echo Mage::helper('M2ePro')->__('The Item Condition setting depends on the way of the Primary Category choosing.
        If it is chosen from eBay Categories list, the list of Item Condition is uploaded from eBay and you are required to choose from it.
        If the Primary Category is set via Custom Attribute, the list of attributes related to the previously chosen Attribute Set is uploaded and
        you are required to choose the Item Condition by choosing appropriate attribute.<br/><br/>
        <b>Note:</b> Attribute must contain an ID of the Item Condition.'); ?>
    </div>

    <div class="entry-edit" id="magento_block_listing_template_specifics_condition">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Condition'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr id="item_condition_value_container" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Item Condition'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="condition_value" name="condition_value"></select>
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Condition of the product(s) you want to list on eBay'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="item_condition_attribute_container" style="display: none;">
                        <td class="label nobr">
                            <label><?php echo Mage::helper('M2ePro')->__('Item Condition Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="item_condition_attribute_container_td" class="value"></td>
                        <td id="item_condition_attribute_container_td_note" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The Condition Attribute must have condition ID as value.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

<div id="listing_template_specifics_details_container" style="display: none;">

    <div id="block_notice_listing_template_specifics_details" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Product Details'); ?>">
        <?php echo Mage::helper('M2ePro')->__('To make easier finding your Listing in eBay search results specify products\' identifiers,
        such as ISBN, ePID (Product Reference ID), UPC, EAN.
        <br/>Use the Custom Value option to enter necessary value, or choose a Custom Attribute that contains it.<br/><br/>
        <b>Note:</b> These options correspond to the Primary eBay Category, NOT the Secondary Category.'); ?>
    </div>

    <div class="entry-edit" id="magento_block_listing_template_specifics_details">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Product Details'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0" cellpadding="0">

                    <tr id="product_details_isbn">
                        <td class="label">
                            <label for="product_details_isbn_mode"><?php echo Mage::helper('M2ePro')->__('ISBN'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="product_details_isbn_mode" name="product_details_isbn_mode" class="required-entry">
                                <option value="0" <?php if ($formData['product_details_isbn_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="1" <?php if ($formData['product_details_isbn_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="2" <?php if ($formData['product_details_isbn_mode'] == 2): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="product_details_isbn_cv" style="display: none;">
                        <td class="label">
                            <label for="product_details_isbn_cv"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input name="product_details_isbn_cv" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['product_details_isbn_cv']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Unique books\' identifier, includes 10 or 13 characters.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_isbn_ca_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="product_details_isbn_ca_td" class="value" style="width: auto;"></td>
                        <td id="product_details_isbn_ca_td_note" class="value" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose the ISBN attribute that contains unique books\' identifier.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_epid">
                        <td class="label">
                            <label for="product_details_epid_mode"><?php echo Mage::helper('M2ePro')->__('ePID (Product Reference ID)'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="product_details_epid_mode" name="product_details_epid_mode" class="required-entry">
                                <option value="0" <?php if ($formData['product_details_epid_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="1" <?php if ($formData['product_details_epid_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="2" <?php if ($formData['product_details_epid_mode'] == 2): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="product_details_epid_cv" style="display: none;">
                        <td class="label">
                            <label for="product_details_epid_cv"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input name="product_details_epid_cv" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['product_details_epid_cv']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('The eBay\'s short global reference ID for a catalog product. i.e. EPID235742 or 235742'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_epid_ca_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="product_details_epid_ca_td" class="value" style="width: auto;"></td>
                        <td id="product_details_epid_ca_td_note" class="value" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose the ePid attribute that contains eBay\'s short global reference ID.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_upc">
                        <td class="label">
                            <label for="product_details_upc_mode"><?php echo Mage::helper('M2ePro')->__('UPC'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="product_details_upc_mode" name="product_details_upc_mode" class="required-entry">
                                <option value="0" <?php if ($formData['product_details_upc_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="1" <?php if ($formData['product_details_upc_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="2" <?php if ($formData['product_details_upc_mode'] == 2): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="product_details_upc_cv" style="display: none;">
                        <td class="label">
                            <label for="product_details_upc_cv"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input name="product_details_upc_cv" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['product_details_upc_cv']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Unique 12-character identifier that many industries use to identify products.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_upc_ca_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="product_details_upc_ca_td" class="value" style="width: auto;"></td>
                        <td id="product_details_upc_ca_td_note" class="value" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose the UPC attribute that contains unique 12-character identifier.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_ean">
                        <td class="label">
                            <label for="product_details_ean_mode"><?php echo Mage::helper('M2ePro')->__('EAN'); ?>:</label>
                        </td>
                        <td class="value" style="width: auto;">
                            <select id="product_details_ean_mode" name="product_details_ean_mode" class="required-entry">
                                <option value="0" <?php if ($formData['product_details_ean_mode'] == 0): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
                                <option value="1" <?php if ($formData['product_details_ean_mode'] == 1): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
                                <option value="2" <?php if ($formData['product_details_ean_mode'] == 2): echo ' selected="selected"'; endif; ?>><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr id="product_details_ean_cv" style="display: none;">
                        <td class="label">
                            <label for="product_details_ean_cv"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
                        </td>
                        <td class="value" style="width: auto;">
                            <input name="product_details_ean_cv" value="<?php echo Mage::helper('M2ePro')->escapeHtml($formData['product_details_ean_cv']); ?>" type="text" class="M2ePro-required-when-visible input-text" />
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Unique 8 or 13 digit identifier that many industries (such as book publishers) use to identify products.'); ?></span>
                            </p>
                        </td>
                    </tr>

                    <tr id="product_details_ean_ca_tr" style="display: none;">
                        <td class="label">
                            <label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
                        </td>
                        <td id="product_details_ean_ca_td" class="value" style="width: auto;"></td>
                        <td id="product_details_ean_ca_td_note" class="value" style="display: none;">
                            <p class="note">
                                <span><?php echo Mage::helper('M2ePro')->__('Choose the EAN attribute that contains unique 8 or 13 digit identifier.'); ?></span>
                            </p>
                        </td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</div>

<div id="listing_template_specifics_item_specifics_container" style="display: none;">

    <div id="block_notice_listing_template_specifics_item_specifics" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__('Item Specifics'); ?>">
        <?php echo Mage::helper('M2ePro')->__('Adding specific item details will attract your buyers and help them to find your item in a search.
        You can set item detail from the list uploaded from eBay by choosing eBay Recommended option, or create custom detail
        by choosing the Custom Attribute	that contains the item specific ID or typing necessary text into the Custom Value field.<br/><br/>
        <b>Note:</b> These options correspond to the Primary eBay Category, NOT the Secondary Category.'); ?>
    </div>

    <div class="entry-edit" id="magento_block_listing_template_specifics_item_specifics">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Item Specifics'); ?></h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <div id="item_specifics_container"></div>
            </div>
        </div>

    </div>

</div>

<div id="item_specifics_template" style="display: none;">

    <input id="item_specifics_mode_%i%" name="item_specifics_mode_%i%" value="%relation_mode%" type="hidden" />
    <input id="item_specifics_mode_relation_id_%i%" name="item_specifics_mode_relation_id_%i%" value="%relation_id%" type="hidden" />

    <input id="item_specifics_attribute_id_%i%" name="item_specifics_attribute_id_%i%" value="%attribute_id%" type="hidden" />
    <input id="item_specifics_attribute_title_%i%" name="item_specifics_attribute_title_%i%" value="%attribute_title%" type="hidden" />

	<table class="form-list" cellspacing="0" cellpadding="0">

		<tr>
			<td class="label">
				<label>%attribute_title%:</label>
			</td>
			<td class="value">
				<select id="item_specifics_value_mode_%i%" name="item_specifics_value_mode_%i%" onchange="SpecificsHandlersObj.item_specific_mode_change(this);">
					<option id="item_specifics_value_mode_%i%_option_<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_NONE; ?>" value="<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_NONE; ?>"><?php echo Mage::helper('M2ePro')->__('None'); ?></option>
					<option id="item_specifics_value_mode_%i%_option_<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_EBAY_RECOMMENDED; ?>" value="<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_EBAY_RECOMMENDED; ?>"><?php echo Mage::helper('M2ePro')->__('eBay Recommended'); ?></option>
					<option id="item_specifics_value_mode_%i%_option_<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_CUSTOM_VALUE; ?>" value="<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_CUSTOM_VALUE; ?>"><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?></option>
					<option id="item_specifics_value_mode_%i%_option_<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_CUSTOM_ATTRIBUTE; ?>" value="<?php echo Ess_M2ePro_Model_ListingsTemplatesSpecifics::VALUE_MODE_CUSTOM_ATTRIBUTE; ?>"><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?></option>
				</select>
			</td>
		</tr>

		<tr id="item_specifics_value_ebay_recommended_container_%i%" style="display: none;">
			<td class="label">
				<label><?php echo Mage::helper('M2ePro')->__('eBay Recommended'); ?>: <span class="required">*</span></label>
			</td>
			<td class="value">
				<select id="item_specifics_value_ebay_recommended_%i%" name="item_specifics_value_ebay_recommended_%i%" class="M2ePro-required-when-visible"></select>
			</td>
		</tr>

        <tr id="item_specifics_value_custom_value_container_%i%" style="display: none;">
			<td class="label">
				<label><?php echo Mage::helper('M2ePro')->__('Custom Value'); ?>: <span class="required">*</span></label>
			</td>
			<td class="value">
				<input id="item_specifics_value_custom_value_%i%" name="item_specifics_value_custom_value_%i%" value="" type="text" class="M2ePro-required-when-visible input-text" />
			</td>
		</tr>
        
		<tr id="item_specifics_value_custom_attribute_container_%i%" style="display: none;">
			<td class="label">
				<label><?php echo Mage::helper('M2ePro')->__('Custom Attribute'); ?>: <span class="required">*</span></label>
			</td>
			<td id="item_specifics_value_custom_attribute_td_%i%" class="value">
				<select id="item_specifics_value_custom_attribute_%i%" name="item_specifics_value_custom_attribute_%i%" class="M2ePro-required-when-visible"></select>
			</td>
		</tr>

        <tr>
			<td class="value" colspan="2" style="padding: 10px 0 !important;">
				<hr style="border: 1px solid silver; border-bottom: none;" />
			</td>
		</tr>

	</table>

</div>