<script type="text/javascript">
    if (typeof M2ePro == 'undefined') {
        M2ePro = {};
        M2ePro.url = {};
        M2ePro.formData = {};
        M2ePro.customData = {};
        M2ePro.text = {};
	}

    M2ePro.url.setStatus = '<?php echo $this->getUrl('*/adminhtml_wizard/setStatus'); ?>';
    M2ePro.url.startMigration = '<?php echo $this->getUrl('*/adminhtml_wizard/startMigration'); ?>';

    WizardHandlersObj = new WizardHandlers();
    WizardHandlersObj.setConstants('<?php echo Mage::helper('M2ePro')->getClassConstantAsJson('Model_Wizard'); ?>');
    WizardHandlersObj.skip_confirm_text = '<?php echo Mage::helper('M2ePro')->__('Note: If you close the wizard, it never starts again. All settings you will be required to set manually. Press Cancel to continue working with wizard.'); ?>';
</script>

<div id="block_notice_wizard_welcome_description" class="block_notices_module" title="<?php echo Mage::helper('M2ePro')->__(''); ?>" subtitle="" collapseable="no" hideblock="no" always_show="yes">
    <?php $tempString = Mage::helper('M2ePro')->__('<strong>You have successfully installed M2E Pro v. %ver%.</strong><br/><br/>
    The next step is setting up the main settings, such as Cron job, Licensing (extension does not work without license),
    data Migration from the last M2E module and others to enable proper work of extension.<br/>
    In the table below there are recommended server settings, which guaranties stable working of the extension. <br/><br/>
    Press the <u>Start Configuration</u> button to start setting M2E Pro configuration.');
    echo str_replace('%ver%',$this->version,$tempString); ?>
</div>