<style type="text/css">
    .column_condition {
        color: gray;
    }
    .column_value_fail {
        color: red;
    }
    .column_value_success {
        color: green;
    }
</style>

<div class="entry-edit" id="magento_block_wizard_welcome_requirements" collapseable="no">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('System Requirements'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label" style="width:200px;">
                        <strong><?php echo Mage::helper('M2ePro')->__('Properties'); ?></strong>
                    </td>
                    <td class="value" style="width:200px;">
                        <strong><?php echo Mage::helper('M2ePro')->__('Recommended Value'); ?></strong>
                    </td>
                    <td class="value" style="width:200px;">
                        <strong><?php echo Mage::helper('M2ePro')->__('Current Value'); ?></strong>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('Magento Version'); ?>
                    </td>
                    <td class="value column_condition">
                        >= 1.4.0.0
                    </td>
                    <td class="value <?php echo $this->magento_version_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo $this->magento_version_value; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('Memory Limit'); ?>
                    </td>
                    <td class="value column_condition">
                        <?php echo '>= 256 '.Mage::helper('M2ePro')->__('Mb'); ?>
                    </td>
                    <td class="value <?php echo $this->memory_limit_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo $this->memory_limit_value.' '.Mage::helper('M2ePro')->__('Mb'); ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('Max Execution Time'); ?>
                    </td>
                    <td class="value column_condition">
                        <?php echo '>= 360 '.Mage::helper('M2ePro')->__('sec'); ?>
                    </td>
                    <td class="value <?php echo $this->max_execution_time_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo is_int($this->max_execution_time_value) ? $this->max_execution_time_value.' '.Mage::helper('M2ePro')->__('sec') : $this->max_execution_time_value; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('JSON support'); ?>
                    </td>
                    <td class="value column_condition">
                        <?php echo Mage::helper('M2ePro')->__('enabled'); ?>
                    </td>
                    <td class="value <?php echo $this->json_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo $this->json_value; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('SimpleXML support'); ?>
                    </td>
                    <td class="value column_condition">
                        <?php echo Mage::helper('M2ePro')->__('enabled'); ?>
                    </td>
                    <td class="value <?php echo $this->simple_xml_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo $this->simple_xml_value; ?>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?php echo Mage::helper('M2ePro')->__('CURL support'); ?>
                    </td>
                    <td class="value column_condition">
                        <?php echo Mage::helper('M2ePro')->__('enabled'); ?>
                    </td>
                    <td class="value <?php echo $this->curl_validation ? 'column_value_success' : 'column_value_fail'; ?>">
                        <?php echo $this->curl_value; ?>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>

<?php echo $this->getChildHtml('start_installation'); ?>